//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PgsExt.rc
//
#define IDCANCEL2                       4
#define IDR_ADD_DELETE_POPUP            147
#define IDD_SPANGIRDERREPORT            150
#define IDD_BOUNDARY_CONDITIONS         191
#define IDD_REFINEDANALYSIS             216
#define IDC_SLIDER                      221
#define IDC_LOCATION                    222
#define IDD_CONFIGUREPGSUPER            244
#define IDD_CATALOGSERVER               255
#define IDD_SERVERDATA                  256
#define IDB_HINGES                      289
#define IDB_ROLLERS                     290
#define IDB_CONTINUOUS                  291
#define IDB_IP_HINGES                   292
#define IDB_IP_ROLLERS                  293
#define IDB_COLUMN_FIXITY               294
#define IDB_HAUNCH_SQUARE               295
#define IDI_EARTH                       296
#define IDB_BITMAP2                     296
#define IDB_HAUNCH_FILLETED             296
#define IDD_SELECT_GIRDER               297
#define IDD_SELECT_SEGMENT              298
#define IDD_SELECT_POI                  299
#define IDD_CONCRETE_DETAILS            300
#define IDC_CONCRETE_TYPE               301
#define IDD_FHWAUHPC_CONCRETE           301
#define IDC_FC_LABEL                    302
#define IDC_FC                          303
#define IDC_FC_UNIT                     304
#define IDC_DS_TITLE                    305
#define IDC_DS                          306
#define IDC_DS_UNIT                     307
#define IDC_DW                          308
#define IDC_DW_UNIT                     309
#define IDC_MOD_E                       310
#define IDC_EC                          311
#define IDC_EC_UNIT                     312
#define IDC_AGG_SIZE                    313
#define IDC_AGG_SIZE_UNIT               314
#define IDC_COPY_MATERIAL               315
#define IDD_AASHTO_CONCRETE             316
#define IDC_EC_K1_LABEL                 317
#define IDD_AASHTO_CONCRETE2            317
#define IDC_EC_K1                       318
#define IDC_EC_K2_LABEL                 319
#define IDC_EC_K2                       320
#define IDC_CREEP_K1_LABEL              321
#define IDC_CREEP_K1                    322
#define IDC_CREEP_K2_LABEL              323
#define IDC_CREEP_K2                    324
#define IDC_SHRINKAGE_K1_LABEL          325
#define IDC_SHRINKAGE_K1                326
#define IDC_SHRINKAGE_K2_LABEL          327
#define IDC_SHRINKAGE_K2                328
#define IDC_HAS_AGG_STRENGTH            329
#define IDC_AGG_STRENGTH                330
#define IDC_AGG_STRENGTH_T              331
#define IDD_ACI_CONCRETE                332
#define IDC_USER                        333
#define IDC_CURE_METHOD_LABEL           334
#define IDC_CURE_METHOD                 335
#define IDC_CEMENT_TYPE_LABEL           336
#define IDC_CEMENT_TYPE                 337
#define IDC_ALPHA_LABEL                 338
#define IDC_ALPHA                       339
#define IDC_BETA_LABEL                  340
#define IDC_BETA                        341
#define IDC_ALPHA_UNIT                  342
#define IDC_COMPUTE                     343
#define IDD_CEBFIP_CONCRETE             344
#define IDC_S_LABEL                     347
#define IDC_S                           348
#define IDC_BETA_SC_LABEL               349
#define IDC_BETA_SC                     350
#define IDD_ACI_PARAMETERS              352
#define IDC_T1                          353
#define IDC_FCI                         354
#define IDC_FCI_UNIT                    355
#define IDC_RESULT                      358
#define IDD_CEBFIP_PARAMETERS           359
#define IDD_COPY_CONC_ENTRY             360
#define IDC_CONC_ENTRIES                361
#define IDD_PCIUHPC_CONCRETE            361
#define IDC_LABEL                       362
#define IDI_WARNING2                    363
#define IDC_WARNING                     364
#define IDC_WARNOTE                     365
#define IDS_NWC_MESSAGE                 366
#define IDS_LWC_MESSAGE                 367
#define IDC_RADIO_IGNORE_LEVER          1010
#define IDC_LIST                        1012
#define IDC_E_CU                        1017
#define IDC_ECU                         1017
#define IDC_SPAN                        1049
#define IDC_GIRDER                      1050
#define IDC_TEST_SERVER                 1101
#define IDC_RADIO_LEVER                 1110
#define IDC_ENGINEER_NAME               1139
#define IDC_COMPANY_NAME                1142
#define IDC_WORKGROUP_TEMPLATE_LOCATION 1145
#define IDC_WORKGROUP_TEMPLATE_BROWSE   1147
#define IDC_LIBRARY_FILE_LOCATION       1149
#define IDC_LIBRARY_FILE_BROWSE         1152
#define IDC_ADD                         1169
#define IDC_EDIT                        1263
#define IDC_NAME                        1265
#define IDC_SERVER_TYPE                 1267
#define IDC_DESCRIPTION                 1336
#define ID_C_HELP                       1361
#define IDC_RADIO1                      1362
#define IDC_HELP                        1363
#define IDC_FFC                         1364
#define IDC_FFC_UNIT                    1365
#define IDC_FRR                         1366
#define IDC_FRR_UNIT                    1367
#define IDC_CHECK1                      1368
#define IDC_PCTT                        1368
#define IDC_ECU_CHECK                   1368
#define IDC_AGG_SIZE_LABEL              1369
#define IDC_BOUNDARY_CONDITION          1407
#define IDC_UPDATE_FREQUENCY            1412
#define IDC_SERVERS                     1429
#define IDC_RADIO_INPUT                 1442
#define IDC_RADIO_IGNORE                1443
#define IDC_DELETE                      1444
#define IDS_E_NOCHAPTERS                1492
#define IDC_GENERIC                     1504
#define IDC_DOWNLOAD                    1505
#define IDC_PUBLISHERS                  1506
#define IDC_FIRST_RUN                   1508
#define IDC_URL                         1518
#define IDC_UPDATENOW                   1519
#define IDC_URL_STATIC                  1535
#define IDC_UPDATES_STATIC              1536
#define IDC_TEMPLATE_STATIC             1536
#define IDC_PUBLISHER_HYPERLINK         1537
#define IDC_STATIC_EARTH                1539
#define IDC_SEGMENT                     1624
#define IDC_SERVERS_STATIC              1637
#define IDC_SERVERS_STATIC2             1639
#define IDC_GROUP                       1655
#define IDC_FIBER_LABEL                 1733
#define IDC_FIBER                       1734
#define IDC_FIBER_UNIT                  1735
#define IDC_AUTOGENOUS_SHRINKAGE        1737
#define IDC_ALPHA_U                     1738
#define IDC_CONFIGURATION_GROUP         1804
#define IDC_TITLE                       1805
#define IDC_FT_CRI                      2021
#define IDC_FT_CRI_UNIT                 2022
#define IDC_FT_CR                       2023
#define IDC_FT_CR_UNIT                  2024
#define IDC_FT_LOC                      2025
#define IDC_FT_LOC_UNIT                 2026
#define IDC_ET_LOC                      2027
#define IDC_INTERVAL                    3016
#define ID_EDIT_INSERTROW               36894
#define ID_EDIT_REMOVEROWS              36897

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        303
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1370
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
