// IEPluginExample.idl : IDL source for IEPluginExample.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (IEPluginExample.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "PGSuperIEPlugin.idl";  // for the Importer/Exporter plugins

[
	uuid(1C5B5FB1-1643-4b4f-983F-F7B680709018),
	version(1.0),
	helpstring("KDOTExport 1.0 Type Library")
]
library KDOTExport
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(B03DA246-D6F6-4d35-91D1-B93FFAE7241A),
		helpstring("KDOT DataExporter Class")
	]
	coclass PGSuperDataExporter
	{
		[default] interface IPGSuperDataExporter;
	};

   [
      uuid(9C945C73-1FBB-4003-B31A-24BE9D850B99)
   ]
   coclass KDOTComponentInfo
   {
      [default] interface IUnknown;
   };
};
