//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PGSuper.rc
//
#define IDS_DDXFOLDER_TT_MODIFY         1
#define IDS_DDXFILE_TT_MODIFY           2
#define IDS_DDXFOLDER_EDIT_TEXT         3
#define IDS_DDXFILE_OK                  4
#define IDS_DDXFILE_EDIT_TEXT           5
#define IDS_DDXFOLDER_REQUIRE_VALID_FOLDER 6
#define IDS_GIRDER_SHEAR                6
#define IDS_DDXFILE_OVERWRITE_PROMPT    7
#define IDS_E_ONLINERESOURCES           7
#define IDS_DDXFILE_REQUIRE_VALID_FILE  8
#define ID_INDICATOR_MODIFIED           8
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_SPLASH                      102
#define IDB_LIGHTBULB                   103
#define IDD_TIP                         104
#define CG_IDS_TIPOFTHEDAY              105
#define CG_IDS_TIPOFTHEDAYMENU          106
#define CG_IDS_DIDYOUKNOW               107
#define CG_IDS_FILE_ABSENT              108
#define CG_IDP_FILE_CORRUPT             109
#define CG_IDS_TIPOFTHEDAYHELP          110
#define IDR_MAINFRAME                   128
#define IDR_PGSUPETYPE                  129
#define IDR_PGSUPERTYPE                 129
#define IDD_PROJECTPROPERTIES           130
#define IDR_BRIDGEMODELEDITOR           130
#define IDD_UNITS                       131
#define IDR_GIRDERMODELEDITOR           131
#define IDD_POI                         132
#define IDR_ANALYSISMODELEDITOR         132
#define IDR_LIBRARYEDITOR               133
#define IDR_ANALYSISRESULTS             134
#define IDD_ENVIRONMENT                 134
#define IDR_REPORT                      135
#define IDD_BRIDGEDESC_GENERAL          135
#define IDD_BRIDGEDESC_ROADWAY          136
#define IDR_LIBRARTYPE                  136
#define IDR_FACTOROFSAFETY              137
#define IDD_BRIDGEDESC_PIERS            138
#define IDB_WSDOTLOGO                   139
#define IDR_ADD_DELETE_POPUP            140
#define IDD_BRIDGEDESC_XSECTION         141
#define IDD_BRIDGEDESC_SUPERSTRUCTURE   142
#define IDD_DESIGNOPTIONS               143
#define IDD_BRIDGEDESC_PRESTRESS        144
#define IDD_GIRDERDESC_PRESTRESS        144
#define IDD_SPECIFICATION               145
#define IDB_LPFRAME                     146
#define IDD_USER_INFO                   147
#define IDD_FILE_LOCATIONS              148
#define IDD_BRIDGE_EDITOR_PLAN_PAGE     149
#define IDD_BRIDGE_EDITOR_SECTION_PAGE  150
#define IDD_TOOLBARS                    151
#define IDD_GIRDER_EDITOR_SECTION_PAGE  152
#define IDD_GIRDER_EDITOR_ELEVATION_PAGE 153
#define IDR_GIRDER_SECTION              154
#define IDR_BRIDGE_PLAN_CTX             155
#define IDB_IN_USE                      156
#define IDB_IN_USE_AND_READ_ONLY        157
#define IDB_READ_ONLY                   158
#define IDR_BRIDGE_XSECTION_CTX         159
#define IDR_GIRDER_CTX                  160
#define IDB_LIBRARY                     161
#define IDD_DESIGN_GIRDER               162
#define IDD_DESIGN_COMPLETE             163
#define IDD_DESIGN_DETAILS              164
#define IDD_BRIDGE_DESCR_LIFTING_PAGE   173
#define IDD_GIRDERDESC_LIFTING_PAGE     173
#define IDD_LIBRARY_ENTRY_CONFLICT      175
#define IDD_RENAME_LIBRARY_ENTRY        176
#define IDD_GIRDER_DESC_FIRST_PAGE      177
#define IDD_BRIDGE_DESC_MISC            178
#define IDD_COPY_GIRDER_PROPERTIES      179
#define IDD_GIRDER_ELEVATION_BAR        180
#define IDD_VALUE_DIALOG                181
#define IDD_SECTION_CUT_DIALOG          181
#define IDD_ANALYSIS_RESULTS_BAR        182
#define IDD_BRIDGEDESC_SHEAR_STEEL      183
#define IDD_GIRDERDESC_SHEAR_STEEL      183
#define IDB_NORTH_ARROW                 184
#define IDD_LICENSEWIZ_1                184
#define IDD_SECTION_CUT_DIALOG_EX       185
#define IDD_LICENSEWIZ_2                186
#define IDI_WSDOT                       188
#define IDI_BSS                         189
#define IDR_LEGAL                       190
#define IDB_GIRDER_DESIGNER             191
#define IDD_DESIGN_OUTCOME              192
#define IDD_STABILITY_BAR               193
#define IDD_LLDF                        194
#define IDD_BRIDGEDESC_ENVIRONMENTAL    195
#define IDI_DEFAULT_ENTRY               196
#define IDI_FOLDER                      197
#define IDI_OPEN_FOLDER                 198
#define IDI_LIBRARY_MANAGER             199
#define IDD_COPY_CONC_ENTRY             201
#define IDI_WARNING2                    202
#define IDD_SELECT_LIVE_LOAD            203
#define IDD_STATUSCENTER                204
#define IDD_EDIT_POINTLOAD              205
#define IDD_EDIT_DISTRIBUTEDLOAD        207
#define IDD_EDIT_LOADS                  209
#define IDD_DEAL_WITH_LOADS_DLG         210
#define IDR_EDITLOADS                   211
#define IDI_EDIT_LOADS                  212
#define IDR_LOADS_CTX                   214
#define IDB_POINT_LOAD                  215
#define IDD_REFINEDANALYSIS             216
#define IDI_POINT_LOAD                  216
#define IDI_DISTRIBUTED_LOAD            218
#define IDB_DISTRIBUTED_LOAD            219
#define IDD_DIALOG1                     222
#define IDD_DEBOND                      226
#define IDD_ALIGNMENT_HORIZONTAL        227
#define IDD_PROFILE_PAGE                228
#define IDD_SUPERELEVATIONS             229
#define IDD_SPAN_LENGTHS                230
#define IDR_SELECTED_GIRDER_CONTEXT     231
#define IDD_STATION_CUT_DIALOG          232
#define IDR_SELECTED_DECK_CONTEXT       233
#define IDD_SELECT_GIRDER               234
#define IDD_BRIDGEDESCR_GIRDER_CONCRETE 235
#define IDD_BRIDGEDESCR_GIRDER_MATERIALS 235
#define IDD_GIRDERDESC_GENERAL          235
#define IDD_BRIDGEDESC_DECKREINFORCEMENT 236
#define IDI_TXDOT                       237
#define IDD_BRIDGEDESC_LONGITUDINAL_REBAR 238
#define IDD_GIRDERDESC_LONGITUDINAL_REBAR 238
#define IDD_PIER_CONNECTIONS            239
#define IDD_PGSUPER_CATALOG             242
#define IDD_CONFIGUREPGSUPER            243
#define IDD_BRIDGEDESC_DECKDETAILS      246
#define IDI_MOMENT_LOAD                 248
#define IDB_MOMENT_LOAD                 249
#define IDD_EDIT_MOMENTLOAD             250
#define IDD_CATALOGSERVER               255
#define IDD_SERVERDATA                  256
#define IDD_MOVEPIER                    258
#define IDD_CONCRETE_DETAILS            259
#define IDD_STRUCTURAL_ANALYSIS_METHOD  260
#define IDR_SELECTED_PIER_CONTEXT       262
#define IDR_SELECTED_SPAN_CONTEXT       263
#define IDD_GIRDERLAYOUT                264
#define IDR_GIRDER_GRID_CONTEXT         265
#define IDD_SPANCONNECTIONS             268
#define IDD_SPANLAYOUT                  269
#define IDD_PIERLAYOUT                  270
#define IDD_PIERCONNECTIONS             271
#define IDD_GIRDERSPACING               272
#define IDD_BRIDGEDESC_FRAMING          274
#define IDR_FRAMING_GRID_CONTEXT        275
#define IDD_BRIDGEDESC_RAILINGSYSTEM    276
#define IDD_SELECT_ITEM                 277
#define IDD_UIHINTS                     278
#define IDD_SCREEN_SIZE                 280
#define IDD_RESOLVE_GIRDER_SPACING      281
#define IDB_HINGES                      289
#define IDB_ROLLERS                     290
#define IDB_CONTINUOUS                  291
#define IDD_STATUS_DIALOG               292
#define IDR_REPORTS                     293
#define IDD_GIRDERLABELFORMAT           294
#define IDR_PGSUPER_TEMPLATE_ICON       500
#define IDC_BRIDGE                      1000
#define IDC_BULB                        1000
#define IDC_BRIDGEID                    1001
#define IDC_STARTUP                     1001
#define IDC_JOBNUMBER                   1002
#define IDC_NEXTTIP                     1002
#define IDC_ENGINEER                    1003
#define IDC_COMPANY                     1004
#define IDC_TIPSTRING                   1004
#define IDC_FC                          1005
#define IDC_COMMENTS                    1006
#define IDC_DS                          1006
#define IDC_SI_UNITS                    1007
#define IDC_MILD_STEEL_SELECTOR         1007
#define IDC_DW                          1007
#define IDC_RADIO2                      1008
#define IDC_AGG_SIZE                    1008
#define IDC_POI                         1009
#define IDC_VALUE                       1009
#define IDC_TF_SPACING                  1009
#define IDC_RADIO3                      1010
#define IDC_UPDATEDESIGN                1010
#define IDC_PROFILE                     1010
#define IDC_RADIO_IGNORE_LEVER          1010
#define IDC_NUMERIC                     1010
#define IDC_LIST                        1012
#define IDC_VALUE_UNITS                 1012
#define IDC_EXPOSURE                    1013
#define IDC_RELHUMIDITY                 1014
#define IDC_INSERTROW                   1014
#define IDC_REFDIR                      1015
#define IDC_REMOVEROWS                  1015
#define IDC_DIRECTION                   1015
#define IDC_PIER1_STATION               1016
#define IDC_RESTORE_DEFAULTS            1016
#define IDC_APPEND_ROW                  1016
#define IDC_PIER2_STATION               1017
#define IDC_STATIONFMT                  1018
#define IDC_LONG_GRID                   1018
#define IDC_PIER1_ORIENTATION           1019
#define IDC_PIER1_TYPE                  1021
#define IDC_PIER2_ORIENTATION           1022
#define IDC_PIER2_TYPE                  1023
#define IDC_ORIENTATIONFMT              1024
#define IDC_PIER1_GDRSPACING            1025
#define IDC_PIER2_GDRSPACING            1026
#define IDC_FC_UNIT                     1026
#define IDC_PIER2_GDRSPACING_UNIT       1027
#define IDC_DS_UNIT                     1027
#define IDC_PIER1_GDRSPACING_UNIT       1028
#define IDC_DW_UNIT                     1028
#define IDC_NUMGDR                      1029
#define IDC_AGG_SIZE_UNIT               1029
#define IDC_NUMGDR_SPIN                 1030
#define IDC_GDR_TYPE                    1031
#define IDC_NUMGDR_AHEAD                1031
#define IDC_NUMGDR_NEXT_SPAN            1031
#define IDC_GDR_CONCTYPE                1032
#define IDC_CBSLAB_TYPE                 1032
#define IDC_NUMGDR_SPIN_AHEAD           1032
#define IDC_NUMGDR_SPIN_NEXT_SPAN       1032
#define IDC_GROSS_DEPTH                 1033
#define IDC_OVERHANG                    1034
#define IDC_LEFTOVERHANG                1034
#define IDC_ADIM                        1035
#define IDC_SLAB_CONCRETE               1036
#define IDC_SLAB_FC                     1036
#define IDC_LAST_ZONE                   1038
#define IDC_OLAY_DENSITY_LABEL          1039
#define IDC_OLAY_DENSITY                1040
#define IDC_SACDEPTH                    1041
#define IDC_SHEAR_GRID                  1041
#define IDC_OLAY_DENSITY_UNIT           1042
#define IDC_SACDEPTH_UNIT               1043
#define IDC_ADIM_UNIT                   1044
#define IDC_BAR_SIZE                    1044
#define IDC_OVERHANG_UNIT               1045
#define IDC_TF_BAR_SIZE                 1045
#define IDC_LEFTOVERHANG_UNIT           1045
#define IDC_GROSS_DEPTH_UNIT            1046
#define IDC_SLAB_FC_UNIT                1047
#define IDC_DIAPHRAGM_LAYOUT            1048
#define IDC_SLAB_DS                     1048
#define IDC_SPAN                        1049
#define IDC_SLAB_DS_UNIT                1049
#define IDC_OLAY_WEIGHT_LABEL           1050
#define IDC_GIRDER                      1050
#define IDC_SLAB_MA                     1050
#define IDC_OLAY_DEPTH_LABEL            1051
#define IDC_DETAIL_STIRRUPS             1051
#define IDC_LOAD_CASE                   1051
#define IDC_SLAB_MA_UNIT                1051
#define IDC_LOSSES                      1052
#define IDC_ACTION                      1052
#define IDC_RIGHTOVERHANG               1052
#define IDC_OLAY_WEIGHT                 1053
#define IDC_STAGE                       1053
#define IDC_RIGHTOVERHANG_UNIT          1053
#define IDC_OLAY_WEIGHT_UNIT            1054
#define IDC_FCI                         1054
#define IDC_TRAFFICBARRIER2             1054
#define IDC_OLAY_DEPTH                  1055
#define IDC_FCI_UNIT                    1055
#define IDC_OLAY_DEPTH_UNIT             1056
#define IDC_GRADE250                    1058
#define IDC_GRADE1725                   1058
#define IDC_SLAB_DW                     1058
#define IDC_GRADE270                    1059
#define IDC_GRADE1860                   1059
#define IDC_SLAB_DW_UNIT                1059
#define IDC_LOWRELAX                    1060
#define IDC_STRESSREL                   1061
#define IDC_STRAND_SIZE                 1062
#define IDC_XFERTIME                    1063
#define IDC_XFERTIME_SPIN               1064
#define IDC_XFERTIME_UNIT               1065
#define IDC_HPOFFSET_END                1066
#define IDC_HP_CB_END                   1066
#define IDC_HPOFFSET_END_UNIT           1067
#define IDC_HPOFFSET_HP                 1068
#define IDC_HPOFFSET_HP_UNIT            1069
#define IDC_NUM_SS                      1070
#define IDC_NUM_SS_SPIN                 1071
#define IDC_NUM_HS                      1072
#define IDC_NUM_HS_SPIN                 1073
#define IDC_SS_JACK                     1074
#define IDC_SS_JACK_FORCE               1075
#define IDC_HS_JACK                     1076
#define IDC_HS_JACK_FORCE               1077
#define IDC_SS_JACK_FORCE_UNIT          1078
#define IDC_HS_JACK_FORCE_UNIT          1079
#define IDC_TRAFFICBARRIER              1080
#define IDC_SPEC                        1080
#define IDC_NUM_TEMP                    1080
#define IDC_LEFT_TRAFFICBARRIER         1080
#define IDC_SPACING                     1081
#define IDC_NUM_TEMP_SPIN               1081
#define IDC_SPACING_UNIT                1082
#define IDC_TEMP_JACK                   1082
#define IDC_ENGINEER_NAME               1083
#define IDC_TEMP_JACK_FORCE             1083
#define IDC_RIGHT_TRAFFICBARRIER        1083
#define IDC_COMPANY_NAME                1084
#define IDC_TEMP_JACK_FORCE_UNIT        1084
#define IDC_USER_TEMPLATE_BROWSE        1085
#define IDC_WORKGROUP_TEMPLATE_LOCATION 1086
#define IDC_LABEL_PIERS                 1086
#define IDC_WORKGROUP_TEMPLATE_BROWSE   1087
#define IDC_LABEL_GIRDERS               1087
#define IDC_LIBRARY_FILE_LOCATION       1088
#define IDC_LABEL_ALIGNMENT             1088
#define IDC_SHOW_DIMENSIONS             1088
#define IDC_LIBRARY_FILE_BROWSE         1089
#define IDC_TIP_FILE_LOCATION           1089
#define IDC_SHOW_STIRRUPS               1089
#define IDC_SHOW_SCHEMATIC              1090
#define IDC_TOOLTIPS                    1090
#define IDC_SHOW_STRANDS                1091
#define IDC_SHOW_PS_CG                  1092
#define IDC_SHOW_LONG_REINF             1093
#define IDC_SHOW_SHOW_LONG_REINF        1093
#define IDC_CHANGE_SECTION              1096
#define IDC_SECTION_CUT                 1097
#define IDC_GRID                        1100
#define IDC_BUTTON1                     1101
#define IDC_PRINT                       1101
#define IDC_VIEWDETAILS                 1101
#define IDC_COPY_MATERIAL               1101
#define IDC_EDIT_LOAD                   1101
#define IDD_ADD                         1101
#define IDC_ADD                         1101
#define IDC_ADD_PIER                    1101
#define IDC_RESTORE_DEFAULTS1           1101
#define IDC_BACK_COPY                   1101
#define IDC_AHEAD_COPY                  1102
#define IDC_UPDATE_STIRRUPS             1105
#define IDC_OUTCOME                     1106
#define IDC_BROWSER                     1108
#define IDC_DETAILS                     1109
#define IDC_LEFT_END                    1110
#define IDC_RADIO4                      1110
#define IDC_UPDATEDESIGN_NO             1110
#define IDC_RADIO_LEVER                 1110
#define IDC_LEFT_HARP                   1111
#define IDC_GIRDER_MIDDLE               1112
#define IDC_VERSION                     1112
#define IDC_RIGHT_HARP                  1113
#define IDC_DESIGN_FLEXURE              1113
#define IDC_RIGHT_END                   1114
#define IDC_DESIGN_SHEAR                1114
#define IDC_SS_TITLE                    1114
#define IDC_USER_CUT                    1115
#define IDC_HS_TITLE                    1115
#define IDC_DESIGN_A                    1115
#define IDC_TEMP_TITLE                  1116
#define IDC_HPOFFSET_END_TITLE          1117
#define IDC_HPOFFSET_END_NOTE           1118
#define IDC_HPOFFSET_HP_TITLE           1119
#define IDC_HPOFFSET_HP_NOTE            1120
#define IDC_LIFTING_LOOP_LOCATION       1121
#define IDC_TRUCK_SUPPORT_LOCATION      1122
#define IDC_TRAILINGOVERHANG            1122
#define IDC_LIFTING_LOOP_LOCATION_UNITS 1123
#define IDC_TRUCK_SUPPORT_LOCATION_UNITS 1124
#define IDC_TRAILINGOVERHANG_UNITS      1124
#define IDC_ALIGNMENT                   1125
#define IDC_LEADINGOVERHANG             1125
#define IDC_PI_STATION                  1126
#define IDC_LEADINGOVERHANG_UNITS       1126
#define IDC_FWD_TANGENT                 1127
#define IDC_BK_TANGENT                  1128
#define IDC_RADIUS                      1129
#define IDC_GRADE                       1130
#define IDC_G1                          1131
#define IDC_GRADE_TAG                   1132
#define IDC_G1_TAG                      1133
#define IDC_G2                          1134
#define IDC_PVI_STATION                 1135
#define IDC_PVI_ELEVATION               1136
#define IDC_PVI_ELEVATION_TAG           1137
#define IDC_LENGTH                      1138
#define IDC_LENGTH_TAG                  1139
#define IDC_LEFT_CROWN                  1140
#define IDC_LEFT_CROWN_TAG              1141
#define IDC_RIGHT_CROWN                 1142
#define IDC_PI_STATION_LABEL            1143
#define IDC_FWD_TANGENT_LABEL           1144
#define IDC_BK_TANGENT_LABEL            1145
#define IDC_RADIUS_LABEL                1146
#define IDC_DIRECTION_LABEL             1147
#define IDC_DIRECTION_TAG               1148
#define IDC_PI_STATION_TAG              1149
#define IDC_FWD_TANGENT_TAG             1150
#define IDC_BK_TANGENT_TAG              1151
#define IDC_TF_SPACING_UNITS            1151
#define IDC_RADIUS_TAG                  1152
#define IDC_GRADE_LABEL                 1153
#define IDC_G1_LABEL                    1154
#define IDC_G2_LABEL                    1155
#define IDC_FILLET                      1156
#define IDC_PVI_STATION_LABEL           1156
#define IDC_FILLET_UNIT                 1157
#define IDC_PVI_ELEVATION_LABEL         1157
#define IDC_LENGTH_LABEL                1158
#define IDC_G2_TAG                      1159
#define IDC_PVI_STATION_TAG             1160
#define IDC_CURVED_ALIGNMENT            1161
#define IDC_VC_PROFILE                  1162
#define IDC_STATION_LABEL               1163
#define IDC_STATION                     1164
#define IDC_ELEVATION_LABEL             1165
#define IDC_ELEVATION                   1166
#define IDC_ELEVATION_TAG               1167
#define IDC_STATION_TAG                 1168
#define IDC_RIGHT_CROWN_TAG             1169
#define ID_RENAME_ENTRY                 1170
#define IDC_ENTRY_TEXT                  1171
#define ID_OVERWRITE                    1172
#define IDC_EDIT1                       1173
#define IDC_LOCATION                    1173
#define IDC_K1                          1173
#define IDC_TOP_COVER                   1173
#define IDC_EDIT                        1173
#define IDC_SUPERSTRUCTURE_DESCRIPTION  1173
#define IDC_NAME                        1173
#define IDC_DESIGN_TRUCK_IMPACT         1173
#define IDC_SPAN_LENGTH                 1173
#define IDC_ORIENTATION                 1173
#define IDC_LEFT_SIDEWALK_LEFT_DEPTH    1173
#define IDC_WIDTH                       1173
#define IDC_REFSTATION                  1173
#define IDC_ADIM_START                  1173
#define IDC_START_SLAB_OFFSET           1173
#define IDC_TOP_COVER_UNIT              1174
#define IDC_MAGNITUDE                   1174
#define IDC_LOCATION2                   1174
#define IDC_RIGHT_MAGNITUDE             1174
#define IDC_RIGHT_SIDEWALK_LEFT_DEPTH   1174
#define IDC_ALIGNMENTOFFSET_LABEL       1174
#define IDC_ADIM_END                    1174
#define IDC_FATIGUE_TRUCK_IMPACT        1174
#define IDC_PERMIT_TRUCK_IMPACT         1175
#define IDC_BOTTOM_COVER                1175
#define IDC_SPAN_GIRDER                 1175
#define IDC_LOCATION3                   1175
#define IDC_RIGHT_LOCATION              1175
#define IDC_BOTTOM_COVER_UNIT           1176
#define ID_APPLY                        1176
#define IDC_LOCATION4                   1176
#define IDC_LEFT_MAGNITUDE              1176
#define IDC_TOP_MAT_BAR_SPACING         1177
#define ID_CLOSE                        1177
#define IDC_TOP_MAT_BAR_SPACING_UNIT    1178
#define IDC_TOP_MAT_LUMP_SUM            1179
#define IDC_FROM_LIST                   1179
#define IDC_TOP_MAT_LUMP_SUM_UNIT       1180
#define IDC_TO_LIST                     1180
#define IDC_BOTTOM_MAT_BAR_SPACING      1181
#define IDC_COPY_PRESTRESSING           1181
#define IDC_BOTTOM_MAT_BAR_SPACING_UNIT 1182
#define IDC_COPY_TRANSVERSE             1182
#define IDC_CONFLICT_TOP                1182
#define IDC_BOTTOM_MAT_LUMP_SUM         1183
#define IDC_COPY_HANDLING               1183
#define IDC_CONFLICT_BOTTOM             1183
#define IDC_BOTTOM_MAT_LUMP_SUM_UNIT    1184
#define IDC_LIC_TEXT                    1184
#define IDC_ALIGNMENTOFFSET             1185
#define IDC_DECK                        1185
#define IDC_DISCLAIMER                  1185
#define IDC_CHECK                       1186
#define ID_OK                           1189
#define IDC_STATIC_BOX                  1190
#define IDC_LEFT_DENSITY_LABEL          1190
#define IDC_END_SLAB_OFFSET2            1190
#define IDC_RIGHT_DENSITY_LABEL         1191
#define IDC_STATIC_TEXT                 1192
#define IDC_GDR_SECTION                 1193
#define IDC_SLAB_TYPE                   1194
#define IDC_DEPTH_LABEL                 1195
#define IDC_GROSS_DEPTH_LABEL           1195
#define IDC_PANEL_DEPTH                 1196
#define IDC_PANEL_DEPTH_UNIT            1197
#define IDC_PANEL_SUPPORT               1198
#define IDC_PANEL_SUPPORT_UNIT          1199
#define IDC_DEPTH_LABEL2                1200
#define IDC_LLDF_COMPUTE                1200
#define IDC_LLDF_LEVER_RULE             1201
#define IDC_LLDF_INPUT                  1202
#define IDC_LLDF_MOMENT                 1202
#define IDC_INT_LLDF_MOMENT             1202
#define IDC_LLDF_SHEAR                  1203
#define IDC_INT_LLDF_SHEAR              1203
#define IDC_LLDF_REACTION               1204
#define IDC_INT_LLDF_REACTION           1204
#define IDC_EXT_LLDF_MOMENT             1205
#define IDC_EXT_LLDF_SHEAR              1206
#define IDC_EXT_LLDF_REACTION           1207
#define IDC_CONC_ENTRIES                1208
#define IDC_WARNING                     1209
#define IDC_WARNOTE                     1210
#define IDC_STATUSLIST                  1211
#define IDC_DESIGN_LL_LIST              1211
#define IDC_SPANS                       1212
#define IDC_DESIGN_HL93                 1212
#define IDC_GIRDERS                     1213
#define IDC_FATIGUE_LL_LIST             1213
#define IDC_STRENGTH_LL_LIST            1214
#define IDC_MEASURED_FROM               1214
#define IDC_STRENGTH_HL93               1214
#define IDC_LOCATION_UNITS              1215
#define IDC_FRACTIONAL                  1216
#define IDC_MAGNITUDE_UNITS             1217
#define IDC_LOADCASE                    1218
#define IDC_STIRRUPS_ENGAGE_DECK        1218
#define IDC_TEMPORARY                   1219
#define IDC_MAGNITUDE_UNITS2            1219
#define IDC_LOADTYPE                    1220
#define IDC_LOADS_LIST                  1221
#define IDC_ANALYSIS                    1221
#define IDC_DELETE_LOAD                 1222
#define IDC_ADD_POINTLOAD               1223
#define IDC_ADD_NEW_DISTRIBUTED         1224
#define IDC_LEFT_LOCATION               1225
#define IDC_LEFT_ENDSTATIC              1226
#define IDC_RIGHT_END_STATIC            1227
#define IDC_LOCATION_STATIC             1228
#define ID_DELETE_LOAD                  1229
#define ID_EDIT_LOAD                    1230
#define IDC_MESSAGE                     1231
#define IDC_SPAN_LENGTH_CTRL            1232
#define IDC_LOAD_STATIC                 1234
#define IDC_SELSTAGE                    1235
#define IDC_LOADS                       1236
#define IDC_POINT_LOAD_DRAG             1237
#define IDC_GIRDER_FC                   1238
#define IDC_DISTRIBUTED_LOAD_DRAG       1238
#define IDC_GIRDER_FC_UNIT              1239
#define IDC_MOMENT_LOAD_DRAG            1239
#define IDC_GIRDER_MA                   1240
#define IDC_GIRDER_MA_UNIT              1241
#define IDC_GIRDER_DS                   1242
#define IDC_GIRDER_DS_UNIT              1243
#define IDC_GIRDER_DW                   1244
#define IDC_GIRDER_DW_UNIT              1245
#define IDC_CHOICE                      1246
#define IDC_SHOW_LEGEND                 1247
#define IDC_HAULINGOVERHANGS            1250
#define IDC_GIRDERLENGTH                1251
#define IDC_GIRDERLENGTH_UNIT           1252
#define IDC_MAXOVERHANG                 1253
#define IDC_OVERHANG_LABEL              1256
#define IDC_LEFTOVERHANG_LABEL          1256
#define IDC_FILLET_LABEL                1257
#define IDC_PANEL_DEPTH_LABEL           1258
#define IDC_PANEL_SUPPORT_LABEL         1259
#define IDC_ADIM_LABEL                  1260
#define IDC_SLAB_FC_LABEL               1261
#define IDC_SLAB_DS_LABEL               1262
#define IDC_SLAB_DW_LABEL               1263
#define IDC_SLAB_MA_LABEL               1264
#define IDC_SACDEPTH_LABEL              1265
#define IDC_RIGHTOVERHANG_LABEL         1266
#define IDC_COMBO1                      1267
#define IDC_GIRDER_ORIENTATION          1267
#define IDC_PIER                        1267
#define IDC_HP_COMBO_END                1267
#define IDC_TOP_MAT_BAR                 1267
#define IDC_UPDATE_FREQUENCY            1267
#define IDC_OVERHANG_TAPER              1267
#define IDC_GIRDER_END                  1267
#define IDC_RESIZEOPTIONS               1267
#define IDC_GIRDER_NAME                 1267
#define IDC_PREV_PIER_SPACING_MEASUREMENT_LOCATION 1267
#define IDC_MOVE_PIER                   1267
#define IDC_BACK_PIER_SPACING_MEASUREMENT 1267
#define IDC_PREV_SPAN_SPACING_MEASUREMENT 1267
#define IDC_ROA_CB                      1267
#define IDC_FROM_SPAN                   1267
#define IDC_COMBO2                      1268
#define IDC_HP_COMBO_HP                 1268
#define IDC_BOTTOM_MAT_BAR              1268
#define IDC_LEFT_CONNECTION             1268
#define IDC_GIRDER_SPACING_MEASURE      1268
#define IDC_WEARINGSURFACETYPE          1268
#define IDC_SERVERS                     1268
#define IDC_NEXT_PIER_SPACING_MEASUREMENT_LOCATION 1268
#define IDC_LINK_SOURCE                 1268
#define IDC_AHEAD_PIER_SPACING_MEASUREMENT 1268
#define IDC_NEXT_SPAN_SPACING_MEASUREMENT 1268
#define IDC_MEASUREMENT_DATUM           1268
#define IDC_FROM_GIRDER                 1268
#define IDC_RIGHT_CONCRETE_LABEL        1268
#define IDC_RIGHT_CONNECTION            1269
#define IDC_PREV_PIER_SPACING_MEASUREMENT_TYPE 1269
#define IDC_NEXT_PIER_SPACING_MEASUREMENT_TYPE 1270
#define IDC_K1_LABEL                    1272
#define IDC_DEBOND_HARPED               1273
#define IDC_DEBOND_STRAIGHT             1274
#define IDC_DEBOND_GRID                 1274
#define IDC_DELETE                      1275
#define IDC_PICTURE                     1276
#define IDC_CHECK1                      1277
#define IDC_SYMMETRIC_DEBOND            1277
#define IDC_FUTURE_WS                   1277
#define IDC_MOD_ECI                     1277
#define IDC_CHECK_ADIM                  1277
#define IDC_LONGITUDINAL_REBAR          1277
#define IDC_SHOW_DIALOG                 1277
#define IDC_UPDATE_NOW                  1277
#define IDC_EXTENDED                    1277
#define IDC_NORTH_UP                    1277
#define IDC_SHOW_TRANSV_REINF           1277
#define IDC_SYNC                        1277
#define IDC_MIRROR_LINK                 1277
#define IDC_SYMMETRICAL_GIRDER_LAYOUT   1277
#define IDC_SAME_NUM_GIRDERLINES        1277
#define IDC_SAME_GIRDER_SPACING         1277
#define IDC_RIGHT_SIDEWALK              1277
#define IDC_IGNORE_ROA                  1277
#define IDC_DONTSHOWAGAIN               1277
#define IDC_SAMESLABOFFSET              1277
#define IDC_SPACING_LABEL               1279
#define IDC_ALIGNMENTOFFSET_UNIT        1281
#define IDC_ALIGNMENTOFFSET_FMT         1282
#define IDC_HCURVE_GRID                 1283
#define IDC_REMOVE                      1284
#define IDC_SORT                        1285
#define IDC_VCURVE_GRID                 1286
#define IDC_ELEVATION_UNIT              1288
#define IDC_PIER_GRID                   1290
#define IDC_REMOVE_PIER                 1291
#define IDC_LAYOUT                      1294
#define IDC_SIMPLE                      1295
#define IDC_SIMPLE2                     1296
#define IDC_SIMPLE3                     1297
#define IDC_STATION_RANGE               1300
#define IDC_MOD_E                       1300
#define IDC_EC                          1301
#define IDC_EC_UNIT                     1302
#define IDC_ECI                         1303
#define IDC_ECI_UNIT                    1304
#define IDC_MOD_EC                      1307
#define IDC_STRAND_INPUT_TYPE           1310
#define IDC_HARP_STRAIGHT               1311
#define IDC_STATIC_LL                   1312
#define IDC_STATIC_LLE                  1313
#define IDC_STATIC_SL                   1314
#define IDC_STATIC_TLSO                 1315
#define IDC_STATIC_SLLO                 1316
#define IDC_STATICSLGL                  1317
#define IDC_CHECK_LIFTING               1318
#define IDC_CHECK_HAULING               1319
#define IDC_CHECK_SLOPE                 1320
#define IDC_CHECK_HOLDDOWN              1321
#define IDC_LEFT_BOUNDARY_CONDITIONS    1322
#define IDC_RIGHT_BOUNDARY_CONDITIONS   1323
#define IDC_CATALOG                     1323
#define IDC_CATALOG_LIST                1324
#define IDC_GENERIC                     1325
#define IDC_DOWNLOAD                    1326
#define IDC_PUBLISHERS                  1327
#define IDC_LOCAL                       1328
#define IDC_FIRST_RUN                   1332
#define IDC_DECK_TYPE                   1333
#define IDC_OVERHANG_DEPTH              1334
#define IDC_OVERHANG_DEPTH_UNIT         1335
#define IDC_DESCRIPTION                 1336
#define IDC_OVERHANG_DEPTH_LABEL        1337
#define IDC_ADD_MOMENTLOAD              1339
#define IDC_ALLOWABLE_SPACING           1340
#define IDC_GIRDER_CONNECTIVITY_S       1341
#define IDC_GIRDER_CONNECTIVITY         1342
#define IDC_URL                         1347
#define IDC_UPDATENOW                   1348
#define IDC_DESIGN_LANE_IMPACT          1349
#define IDC_BEAM_FAMILIES               1350
#define IDC_FATIGUE_LANE_IMPACT         1350
#define IDC_PERMIT_LANE_IMPACT          1351
#define IDC_NUMSTRAIGHT                 1351
#define IDC_NUM_DEBONDED                1352
#define IDC_PERCENT_DEBONDED            1353
#define IDC_MORE                        1354
#define IDC_GIRDERGRID                  1356
#define IDC_PREV_PIER_SPACING_LABEL     1357
#define IDC_NEXT_PIER_SPACING_LABEL     1358
#define IDC_PREV_PIER_SPACING_GRID      1359
#define IDC_BACK_BOUNDARY_CONDITIONS    1359
#define IDC_NEXT_PIER_SPACING_GRID      1360
#define IDC_BACK_CONNECTION             1360
#define IDC_AHEAD_CONNECTION            1361
#define IDC_AHEAD_BOUNDARY_CONDITIONS   1362
#define IDC_AHEAD_GROUP                 1363
#define IDC_BACK_GROUP                  1364
#define IDC_SPAN_LABEL                  1365
#define IDC_SPAN_LENGTH_UNIT            1366
#define IDC_PIER_LABEL                  1367
#define IDC_STATION_FORMAT              1368
#define IDC_ORIENTATION_FORMAT          1369
#define IDC_LINK_ORIENTATION            1370
#define IDC_NUMGDR_BACK                 1371
#define IDC_NUMGDR_PREV_SPAN            1371
#define IDC_NUMGDR_SPIN_BACK            1372
#define IDC_NUMGDR_SPIN_PREV_SPAN       1372
#define IDC_MOVE_LABEL                  1373
#define IDC_SAME_GIRDERNAME             1374
#define IDC_SAME_GIRDERSPACING          1375
#define IDC_AHEAD_NOTE                  1377
#define IDC_BACK_NOTE                   1378
#define IDC_NUMGDR_NOTE                 1378
#define IDC_GIRDERGRID_NOTE             1379
#define IDC_PREV_PIER_GIRDER_SPACING_MEASURE 1380
#define IDC_NEXT_PIER_GIRDER_SPACING_MEASURE 1381
#define IDC_GIRDER_SPACING_NOTE         1382
#define IDC_BACK_PIER_SPACING_GRID      1383
#define IDC_PREV_SPAN_SPACING_GRID      1383
#define IDC_AHEAD_PIER_SPACING_GRID     1384
#define IDC_NEXT_SPAN_SPACING_GRID      1384
#define IDC_ADD_SPAN                    1385
#define IDC_REMOVE_SPAN                 1386
#define IDC_LINK_TARGET_NOTE            1387
#define IDC_NUMGDR_PREV_SPAN_LABEL      1388
#define IDC_NUMGDR_NEXT_SPAN_LABEL      1389
#define IDC_BACK_PIER_SPACING_LABEL     1390
#define IDC_AHEAD_PIER_SPACING_LABEL    1391
#define IDC_GIRDER_SPACING_NOTE_BACK    1393
#define IDC_GIRDER_SPACING_NOTE_END_OF_PREV_SPAN 1393
#define IDC_GIRDER_SPACING_NOTE_AHEAD   1394
#define IDC_GIRDER_SPACING_NOTE_START_OF_NEXT_SPAN 1394
#define IDC_NUM_GIRDER_AHEAD_NOTE       1395
#define IDC_NUM_GIRDER_NEXT_SPAN_NOTE   1395
#define IDC_NUM_GIRDER_BACK_NOTE        1396
#define IDC_SPAN_LENGTH_NOTE            1396
#define IDC_NUM_GIRDER_PREV_SPAN_NOTE   1396
#define IDC_BACKGROUP                   1397
#define IDC_AHEADGROUP                  1398
#define IDC_USER_TEMPLATE_LOCATION      1399
#define IDC_BACK_CONNECTION_LABEL       1399
#define IDC_BACK_BOUNDARY_CONDITIONS_LABEL 1400
#define IDC_AHEAD_CONNECTION_LABEL      1401
#define IDC_AHEAD_BOUNDARY_CONDITIONS_LABEL 1402
#define IDC_SAME_GIRDER_FAMILY          1403
#define IDC_GIRDER_ORIENTATION_LABEL    1404
#define IDC_GIRDER_NAME_LABEL           1405
#define IDC_GIRDER_FAMILY_NOTE          1406
#define IDC_GIRDER_FAMILY_LABEL         1407
#define IDC_DECK_TYPE_LABEL             1408
#define IDC_LEFT_SIDEWALK               1409
#define IDC_LEFT_SIDEWALK_WIDTH         1410
#define IDC_LEFT_SIDEWALK_WIDTH_UNIT    1411
#define IDC_LEFT_SIDEWALK_LEFT_DEPTH_UNIT 1412
#define IDC_LEFT_SIDEWALK_RIGHT_DEPTH   1413
#define IDC_LEFT_SIDEWALK_RIGHT_DEPTH_UNIT 1414
#define IDC_LEFT_EXTERIORBARRIER        1415
#define IDC_LEFT_INTERIORBARRIER        1416
#define IDC_RIGHT_EXTERIORBARRIER       1417
#define IDC_RIGHT_INTERIORBARRIER       1418
#define IDC_LEFT_INTERIOR_BARRIER       1419
#define IDC_LEFT_SIDEWALK_WIDTH_LABEL   1420
#define IDC_LEFT_SIDEWALK_LEFT_DEPTH_LABEL 1421
#define IDC_RIGHT_INTERIOR_BARRIER      1422
#define IDC_LEFT_SIDEWALK_RIGHT_DEPTH_LABEL 1423
#define IDC_RIGHT_SIDEWALK_WIDTH        1424
#define IDC_GIRDERNAME_NOTE             1424
#define IDC_RIGHT_SIDEWALK_WIDTH_UNIT   1425
#define IDC_COPY_GIRDER                 1425
#define IDC_RIGHT_SIDEWALK_WIDTH_LABEL  1426
#define IDC_LABEL                       1426
#define IDC_RIGHT_SIDEWALK_LEFT_DEPTH_LABEL 1427
#define IDC_TEXT                        1427
#define IDC_RIGHT_SIDEWALK_RIGHT_DEPTH_LABEL 1428
#define IDC_RIGHT_SIDEWALK_LEFT_DEPTH_UNIT 1429
#define IDC_ALIGNMENT_OFFSET            1429
#define IDC_RIGHT_SIDEWALK_RIGHT_DEPTH  1430
#define IDC_ALIGNMENT_OFFSET_UNIT       1430
#define IDC_RIGHT_SIDEWALK_RIGHT_DEPTH_UNIT 1431
#define IDC_ALIGNMENT_OFFSET_FORMAT     1431
#define IDC_ALIGNMENT_OFFSET_LABEL      1432
#define IDC_DECK_EDGE_LABEL             1434
#define IDC_GIRDER_SPACING_TYPE         1435
#define IDC_GIRDER_SPACING_LABEL        1436
#define IDC_PREV_PIER_GIRDER_SPACING_LABEL 1437
#define IDC_NEXT_PIER_GIRDER_SPACING_LABEL 1438
#define IDC_ROA_STATIC                  1439
#define IDC_HEIGHT                      1439
#define IDC_PREV_SPAN_CONSTANT_SPACING_NOTE 1440
#define IDC_NEXT_SPAN_CONSTANT_SPACING_NOTE 1441
#define IDC_RADIO_INPUT                 1442
#define IDC_RADIO_IGNORE                1443
#define IDC_DS_TITLE                    1445
#define IDS_E_CLASSNOTREG               1446
#define IDS_E_BADINSTALL                1446
#define IDC_SERVERS_STATIC              1446
#define IDS_E_PROBPERSISTS              1447
#define IDC_SERVERS_STATIC2             1447
#define IDS_E_INVALIDFORMAT             1448
#define IDC_LOCAL_STATIC                1448
#define IDS_E_FILENOTFOUND              1449
#define IDC_LOCALS_STATIC2              1449
#define IDS_E_READ                      1450
#define IDC_SERVER_STATIC3              1450
#define IDS_E_FORMAT                    1451
#define IDC_NORTHING                    1451
#define IDS_E_NOBROWSER                 1452
#define IDC_EASTING                     1452
#define IDS_E_WRITE                     1453
#define IDC_BOUNDARY_CONDITIONS         1453
#define IDS_E_UNSAFESAVE                1454
#define IDC_BC_GROUP                    1454
#define IDS_E_SAVERECOVER1              1455
#define IDC_GROUP                       1455
#define IDS_E_SAVERECOVER2              1456
#define IDC_PREV_PIER_AHEAD_CONNECTION  1456
#define IDS_E_CREATEWND                 1457
#define IDC_PREV_PIER_BACK_CONNECTION   1457
#define IDS_CONFLICT_TOP_IMPORT         1458
#define IDC_NEXT_PIER_BACK_CONNECTION   1458
#define IDS_CONFLICT_TOP_MASTER         1459
#define IDC_NEXT_PIER_AHEAD_CONNECTION  1459
#define IDC_COPYRIGHT                   1459
#define IDS_E_LOWRESOURCES              1460
#define IDC_WSDOT                       1460
#define IDS_DLG_STATIONFMT_SI           1461
#define IDC_TXDOT                       1461
#define IDS_DLG_STATIONFMT_US           1462
#define IDC_BRIDGESIGHT                 1462
#define IDS_DLG_ORIENTATIONFMT          1463
#define IDC_LEFT_SIDEWALK_PLACEMENT     1463
#define IDS_GRADE250_US                 1464
#define IDS_GRADE1725_US                1464
#define IDC_RIGHT_SIDEWALK_PLACEMENT    1464
#define IDC_LABEL_BEARINGS              1464
#define IDS_GRADE250_SI                 1465
#define IDS_GRADE1725_SI                1465
#define IDC_LEFT_STRUCTURALLY_CONTINUOUS 1465
#define IDS_GRADE270_US                 1466
#define IDS_GRADE1860_US                1466
#define IDC_RIGHT_STRUCTURALLY_CONTINUOUS 1466
#define IDC_REF_GIRDER                  1466
#define IDS_GRADE270_SI                 1467
#define IDS_GRADE1860_SI                1467
#define IDC_REF_GIRDER_OFFSET           1467
#define IDS_GDRSEL_EXCEED_MAX_STRAND    1468
#define IDC_REF_GIRDER_OFFSET_UNIT      1468
#define IDS_PSFORCE_EXCEED_MAX          1469
#define IDC_REF_GIRDER_OFFSET_TYPE      1469
#define ID_INDICATOR_AUTOCALC_ON        1470
#define IDC_PREV_REF_GIRDER             1470
#define ID_INDICATOR_AUTOCALC_OFF       1471
#define IDC_PREV_REF_GIRDER_OFFSET      1471
#define IDS_BROWSER_ERROR               1472
#define IDC_PREV_REF_GIRDER_OFFSET_UNIT 1472
#define IDS_RESULTS_NOT_AVAILABLE       1473
#define IDC_PREV_REF_GIRDER_OFFSET_TYPE 1473
#define IDS_COMPANY                     1474
#define IDC_NEXT_REF_GIRDER             1474
#define IDS_REG_COMPANY                 1475
#define IDC_NEXT_REF_GIRDER_OFFSET      1475
#define IDS_REG_ENGINEER                1476
#define IDC_NEXT_REF_GIRDER_OFFSET_UNIT 1476
#define IDC_NEXT_REF_GIRDER_OFFSET_TYPE 1477
#define IDC_PREV_REF_GIRDER_LABEL       1478
#define IDC_PREV_REF_GIRDER_FROM        1479
#define IDC_NEXT_REF_GIRDER_LABEL       1480
#define IDC_NEXT_REF_GIRDER_FROM        1481
#define IDC_RADIO1                      1482
#define IDC_ALPHA                       1482
#define IDS_TEMPLATE_FILE_SUFFIX        1483
#define IDS_FATAL_MSG_SAVE              1484
#define IDC_ADIM_START_LABEL            1484
#define IDS_FATAL_MSG_NOSAVE            1485
#define IDC_ADIM_START_UNIT             1485
#define IDS_DEFAULT_MASTER_LIB          1486
#define IDC_ADIM_END_LABEL              1486
#define IDS_CANT_FIND_LIBRARY_FILE      1487
#define IDC_ADIM_END_UNIT               1487
#define IDS_CORRUPTED_LIBRARY_FILE      1488
#define IDC_SLABOFFSET_NOTE             1488
#define IDS_E_EXCESSIVE_SKEW            1489
#define IDC_COPY_SLABOFFSET             1489
#define IDS_E_EXCESSIVE_DELTA_SKEW      1490
#define IDC_SIP_LABEL                   1490
#define IDS_E_PIER_LAYOUT               1491
#define IDS_E_NOCHAPTERS                1492
#define IDC_TO_SPAN                     1492
#define IDS_TOOLBAR_STATE               1493
#define IDC_COMBO4                      1493
#define IDC_TO_GIRDER                   1493
#define IDS_REG_SETTINGS                1494
#define IDC_STRENGTH_GRID               1494
#define IDS_TOOLTIP_STATE               1495
#define IDC_FATIGUE_GRID                1495
#define IDS_REG_WNDPOS                  1496
#define IDC_STRENGTH_LABEL              1496
#define IDS_E_RPTUPDATE                 1497
#define IDS_E_UPDATE                    1497
#define IDC_FATIGUE_LABEL               1497
#define IDS_CONFLICT_BOTTOM_MASTER      1498
#define IDC_LEFT_FC_LABEL               1498
#define IDS_CONFLICT_BOTTOM_IMPORT      1499
#define IDC_LEFT_FC                     1499
#define IDS_WORKING                     1500
#define IDC_LEFT_FC_UNIT                1500
#define IDS_E_PARSER_INIT_FAIL          1501
#define IDC_LEFT_MOD_E                  1501
#define IDS_E_INVALIDVERSION            1502
#define IDC_LEFT_EC                     1502
#define IDS_E_USERDEFINED               1503
#define IDC_LEFT_EC_UNIT                1503
#define ID_INDICATOR_STATUS             1504
#define IDC_LEFT_MORE                   1504
#define IDC_TTS_USE                     1505
#define ID_E_INVALID_ORIENTATION        1505
#define IDC_RIGHT_FC_LABEL              1505
#define IDC_RIGHT_FC                    1506
#define IDC_RIGHT_FC_UNIT               1507
#define IDC_RIGHT_MOD_E                 1508
#define IDC_RIGHT_EC                    1509
#define IDC_RIGHT_EC_UNIT               1510
#define IDC_RIGHT_MORE                  1511
#define IDC_LEFT_DENSITY                1512
#define IDC_LEFT_DENSITY_UNIT           1513
#define IDC_RIGHT_DENSITY               1514
#define IDC_LEFT_DENSITY_UNIT2          1515
#define IDC_RIGHT_DENSITY_UNIT          1515
#define IDC_LEFT_CONCRETE_LABEL         1516
#define IDC_LEFT_CONCRETE_LABEL2        1517
#define IDC_LEFT_RAILING_GROUP          1517
#define IDC_RIGHT_RAILING_GROUP         1518
#define IDC_SLAB_OFFSET_NOTE            1519
#define IDC_START_SLAB_OFFSET_UNIT      1520
#define IDC_END_SLAB_OFFSET             1521
#define IDC_END_SLAB_OFFSET_UNIT        1522
#define IDC_BACK_SLAB_OFFSET_NOTE       1523
#define IDC_AHEAD_SLAB_OFFSET_NOTE      1524
#define IDC_BACK_SLAB_OFFSET            1525
#define IDC_BACK_SLAB_OFFSET_UNIT       1526
#define IDC_AHEAD_SLAB_OFFSET           1527
#define IDC_AHEAD_SLAB_OFFSET_UNIT      1528
#define IDC_BACK_SLAB_OFFSET_LABEL      1529
#define IDC_AHEAD_SLAB_OFFSET_LABEL     1530
#define IDC_NUMGDR_LABEL                1530
#define IDC_START_SLAB_OFFSET_LABEL     1531
#define IDC_END_SLAB_OFFSET_LABEL       1532
#define ID_INDICATOR_ANALYSIS           1605
#define ID_UPDATE_TEMPLATE              1625
#define IDM_REPORT                      2222
#define FIRST_IMPORT_PLUGIN             9000
#define LAST_IMPORT_PLUGIN              9020
#define FIRST_EXPORT_PLUGIN             9100
#define LAST_EXPORT_PLUGIN              9120
#define ID_VIEW_STATUSCENTER            10006
#define ID_VIEW_STATUSCENTER2           10007
#define ID_VIEW_STATUSCENTER3           10008
#define IDM_EXPORT_TXDOTCADDATA         12000
#define IDD_EXPORT_TXDOTCADDATA         12001
#define IDR_STDTOOLBAR                  12129
#define IDR_LIBTOOLBAR                  12130
#define IDR_HELPTOOLBAR                 12131
#define ID_FILE_PROJECT_PROPERTIES      12771
#define ID_EDIT_INSERTROW               12772
#define ID_VIEW_BRIDGEMODELEDITOR       12773
#define ID_VIEW_GIRDEREDITOR            12774
#define ID_EDIT_REMOVEROWS              12775
#define ID_VIEW_ANALYSISMODELEDITOR     12776
#define ID_VIEW_LIBRARYEDITOR           12777
#define ID_VIEW_REPORTS                 12778
#define IDS_BM_VIEW_SETTINGS            12779
#define ID_VIEWSETTINGS_BRIDGEMODELEDITOR 12780
#define ID_VIEWSETTINGS_GIRDEREDITOR    12781
#define ID_VIEWSETTINGS_ANALYSISMODELEDITOR 12782
#define ID_VIEWSETTINGS_LIBRARYEDITOR   12783
#define ID_VIEW_OPTIONS                 12784
#define ID_LOADS_ADDPOINTLOAD           12785
#define ID_LOADS_ADDUNIFLOAD            12786
#define ID_LOADS_EDIT                   12787
#define ID_LOADS_UTILITIES              12788
#define ID_LOADS_FORMS                  12789
#define ID_PROJECT_AUTOCALC             12790
#define ID_PROJECT_UPDATENOW            12791
#define ID_PROJECT_DESIGNGIRDER         12792
#define ID_PROJECT_DESIGNGIRDERDIRECT   12793
#define ID_PROJECT_UNITS                12794
#define ID_PROJECT_SPEC                 12795
#define ID_PROJECT_POI                  12796
#define ID_PROJECT_DESIGNOPTIONS        12797
#define ID_VIEW_ANALYSISRESULTS         12804
#define ID_PROJECT_ENVIRONMENT          12805
#define ID_PROJECT_BRIDGEDESC           12806
#define IDM_ADD_ENTRY                   12807
#define IDM_EDIT_ENTRY                  12808
#define IDM_DELETE_ENTRY                12809
#define IDM_DUPLICATE_ENTRY             12810
#define IDM_SI                          12811
#define IDM_US                          12812
#define IDM_EXPORT_TEMPLATE             12813
#define ID_TOOLBAR_PRINT                12814
#define IDM_LARGE_ICONS                 12815
#define IDM_SMALL_ICONS                 12816
#define IDM_LIST_ICONS                  12817
#define IDM_ARRANGE_ICONS               12818
#define IDS_GM_VIEW_SETTINGS            12819
#define ID_UNITS_SI                     12822
#define ID_UNITS_US                     12823
#define ID_LOADS_LOADMODIFIERS          12825
#define ID_LEFTEND                      12827
#define ID_RIGHTEND                     12828
#define ID_LEFT_HP                      12829
#define ID_CENTER                       12830
#define ID_RIGHT_HP                     12831
#define ID_USER_CUT                     12832
#define ID_EDIT_ROADWAY                 12833
#define ID_EDIT_PIERS                   12834
#define ID_EDIT_BRIDGE                  12834
#define ID_EDIT_SUPERSTRUCTURE          12835
#define ID_VIEWSETTINGS                 12836
#define ID_EDIT_PRESTRESSING            12837
#define ID_EDIT_STIRRUPS                12838
#define ID_HELP_INET_WSDOT              12840
#define ID_HELP_INET_PGSUPER            12841
#define IDM_RENAME_ENTRY                12843
#define IDM_EDIT_GIRDER                 12844
#define ID_BUTTON32845                  12845
#define IDM_COPY_GIRDER_PROPS           12846
#define IDM_IMPORT_PROJECT_LIBRARY      12848
#define ID_APP_LEGAL                    12849
#define ID_HELP_POST                    12850
#define ID_HELP_JOINARPLIST             12851
#define ID_HELP_INET_ARP                12852
#define ID_VIEW_FACTOROFSAFETY          12853
#define ID_VIEW_STABILITY               12854
#define ID_LOADS_LLDF                   12855
#define ID_ADD_POINTLOAD                12858
#define ID_ADD_LINEAR_LOAD              12859
#define ID_EDIT_USERLOADS               12860
#define ID_ADD_DISTRIBUTED_LOAD         12861
#define ID_GV_ADD_POINTLOAD             12863
#define ID_ADD_GV_DISTRIBUTED_LOAD      12864
#define ID_GEV_CTX_EDIT_LOAD            12865
#define ID_GEV_CTX_DELETE_LOAD          12866
#define ID_PROJECT_ALIGNMENT            12867
#define ID_EDIT_GIRDER                  12869
#define ID_VIEW_GIRDER                  12870
#define IDR_LIVE_LOADS                  12871
#define ID_ADD_MOMENT_LOAD              12872
#define ID_DUMP_LBAM                    12873
#define IDS_ALIGNMENTOFFSET_FMT         12874
#define ID_PROJECT_ANALYSIS             12875
#define ID_EDIT_PIER                    12876
#define ID_EDIT_SPAN                    12877
#define IDC_EXPAND                      12878
#define IDC_JOIN                        12879
#define ID_PROJECT_SPANDESC             12880
#define ID_PROJECT_PIERDESC             12881
#define ID_DELETE                       12882
#define ID_DELETE_PIER                  12883
#define ID_DELETE_SPAN                  12885
#define ID_INSERT                       12886
#define ID_INSERT_SPAN                  12887
#define ID_INSERT_PIER                  12888
#define ID_EDIT_DECK                    12889
#define ID_OPTIONS_HINTS                12890
#define ID_PROJECT_DESIGNGIRDERDIRECTHOLDSLABOFFSET 12891
#define ID_SCREEN_SIZE                  12892
#define IDM_HINGED                      12913
#define IDM_ROLLER                      12914
#define IDM_CONTINUOUS_AFTERDECK        12915
#define IDM_CONTINUOUS_BEFOREDECK       12916
#define IDM_INTEGRAL_AFTERDECK          12917
#define IDM_INTEGRAL_BEFOREDECK         12918
#define IDM_INTEGRAL_AFTERDECK_HINGEBACK 12919
#define IDM_INTEGRAL_BEFOREDECK_HINGEBACK 12920
#define IDM_INTEGRAL_AFTERDECK_HINGEAHEAD 12921
#define IDM_INTEGRAL_BEFOREDECK_HINGEAHEAD 12922
#define ID_ZOOM                         12923
#define ID_SCALETOFIT                   12924
#define IDD_SELECTREPORT                12925
#define ID_REPORTS_                     12926
#define ID_OPTIONS_LABELS               12927
#define ID_FILE_NEW_LIBRARY             12928
#define ID_FILE_NEWMASTERLIBRARY        12929
#define ID_FILE_IMPORT                  32788
#define IDS_INCOMPATIBLE_BEARING_MSG    61446
#define IDS_INCOMPATIBLE_BEARING_MSG2   61447
#define IDC_FRAME                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        295
#define _APS_NEXT_COMMAND_VALUE         12930
#define _APS_NEXT_CONTROL_VALUE         1532
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
