//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PGSuperAppPlugin.rc
//
#define ID_INDICATOR_MODIFIED           1
#define ID_INDICATOR_STATUS             2
#define ID_INDICATOR_ANALYSIS           3
#define IDCANCEL2                       3
#define ID_INDICATOR_AUTOCALC_ON        4
#define ID_INDICATOR_AUTOCALC_OFF       5
#define IDS_LWC_MESSAGE                 6
#define IDS_GIRDER_SHEAR                7
#define IDS_LIVE_LOAD_FACTOR_TOOLTIP    8
#define IDS_E_ONLINERESOURCES           9
#define IDS_LIVE_LOAD_FACTOR_DISABLED_TOOLTIP 10
#define IDS_NWC_MESSAGE                 12
#define EAF_TOOLBAR_MENU_COUNT          40
#define EAF_REPORT_MENU_COUNT           50
#define IDS_PROJNAME                    100
#define IDR_PGSUPERAPPPLUGIN            101
#define IDR_PGSUPERCOMPONENTINFO        102
#define IDR_PGSUPERAPPPLUGINIMPL        103
#define IDR_PGSUPERPROJECTIMPORTERAPPPLUGIN 104
#define IDR_PGSUPER                 130
#define IDD_PROJECTPROPERTIES           131
#define IDR_BRIDGEMODELEDITOR           132
#define IDR_PROJECTIMPORTER             133
#define IDR_GIRDERMODELEDITOR           134
#define IDR_ANALYSISMODELEDITOR         136
#define IDR_LIBRARYEDITOR               137
#define IDR_ANALYSISRESULTS             138
#define IDD_ENVIRONMENT                 139
#define IDR_REPORT                      140
#define IDD_BRIDGEDESC_GENERAL          141
#define IDD_BRIDGEDESC_ROADWAY          142
#define IDR_FACTOROFSAFETY              144
#define IDD_BRIDGEDESC_PIERS            145
#define IDB_WSDOTLOGO                   146
#define IDR_ADD_DELETE_POPUP            147
#define IDD_BRIDGEDESC_XSECTION         148
#define IDD_BRIDGEDESC_SUPERSTRUCTURE   149
#define IDD_DESIGNOPTIONS               150
#define IDD_BRIDGEDESC_PRESTRESS        151
#define IDD_GIRDERDESC_PRESTRESS        152
#define IDD_SPECIFICATION               153
#define IDD_USER_INFO                   155
#define IDD_FILE_LOCATIONS              156
#define IDD_BRIDGE_EDITOR_PLAN_PAGE     157
#define IDD_BRIDGE_EDITOR_SECTION_PAGE  158
#define IDD_GIRDER_EDITOR_SECTION_PAGE  160
#define IDD_GIRDER_EDITOR_ELEVATION_PAGE 161
#define IDR_GIRDER_SECTION              162
#define IDR_BRIDGE_PLAN_CTX             163
#define IDB_IN_USE                      164
#define IDB_IN_USE_AND_READ_ONLY        165
#define IDB_READ_ONLY                   166
#define IDR_BRIDGE_XSECTION_CTX         167
#define IDR_GIRDER_CTX                  168
#define IDD_DESIGN_GIRDER               170
#define IDD_DESIGN_COMPLETE             171
#define IDD_DESIGN_DETAILS              172
#define IDD_BRIDGE_DESCR_LIFTING_PAGE   173
#define IDD_GIRDERDESC_LIFTING_PAGE     174
#define IDD_LIBRARY_ENTRY_CONFLICT      175
#define IDD_RENAME_LIBRARY_ENTRY        176
#define IDD_GIRDER_DESC_FIRST_PAGE      177
#define IDD_BRIDGE_DESC_MISC            178
#define IDD_COPY_GIRDER_PROPERTIES      179
#define IDD_GIRDER_ELEVATION_BAR        180
#define IDD_VALUE_DIALOG                181
#define IDD_SECTION_CUT_DIALOG          182
#define IDD_ANALYSIS_RESULTS_BAR        183
#define IDD_BRIDGEDESC_SHEAR_STEEL      184
#define IDD_GIRDERDESC_SHEAR_STEEL      185
#define IDD_LICENSEWIZ_1                187
#define IDD_SECTION_CUT_DIALOG_EX       188
#define IDD_LICENSEWIZ_2                189
#define IDR_LEGAL                       192
#define IDD_DESIGN_OUTCOME              194
#define IDD_STABILITY_BAR               195
#define IDD_LLDF                        196
#define IDD_BRIDGEDESC_ENVIRONMENTAL    197
#define IDI_DEFAULT_ENTRY               198
#define IDI_FOLDER                      199
#define IDI_OPEN_FOLDER                 200
#define IDI_PGSUPER                     201
#define IDI_LIBRARY_MANAGER             201
#define IDD_COPY_CONC_ENTRY             202
#define IDI_WARNING2                    203
#define IDD_SELECT_LIVE_LOAD            204
#define IDD_STATUSCENTER                205
#define IDD_EDIT_POINTLOAD              206
#define IDD_EDIT_DISTRIBUTEDLOAD        207
#define IDD_EDIT_LOADS                  208
#define IDD_DEAL_WITH_LOADS_DLG         209
#define IDR_EDITLOADS                   210
#define IDI_EDIT_LOADS                  211
#define IDR_LOADS_CTX                   212
#define IDI_POINT_LOAD                  214
#define IDI_DISTRIBUTED_LOAD            215
#define IDD_DIALOG1                     217
#define IDD_GIRDERDESC_DEBOND           226
#define IDD_ALIGNMENT_HORIZONTAL        227
#define IDD_PROFILE_PAGE                228
#define IDD_SUPERELEVATIONS             229
#define IDD_SPAN_LENGTHS                230
#define IDR_SELECTED_GIRDER_CONTEXT     231
#define IDD_STATION_CUT_DIALOG          232
#define IDR_SELECTED_DECK_CONTEXT       233
#define IDD_SELECT_GIRDER               234
#define IDD_BRIDGEDESCR_GIRDER_CONCRETE 235
#define IDD_BRIDGEDESCR_GIRDER_MATERIALS 236
#define IDD_GIRDERDESC_GENERAL          237
#define IDD_BRIDGEDESC_DECKREINFORCEMENT 238
#define IDD_BRIDGEDESC_LONGITUDINAL_REBAR 240
#define IDD_GIRDERDESC_LONGITUDINAL_REBAR 241
#define IDD_PIER_CONNECTIONS            242
#define IDD_PGSUPER_CATALOG             243
#define IDD_CONFIGUREPGSUPER            244
#define IDD_BRIDGEDESC_DECKDETAILS      245
#define IDI_MOMENT_LOAD                 246
#define IDD_EDIT_MOMENTLOAD             250
#define IDD_CATALOGSERVER               255
#define IDD_SERVERDATA                  256
#define IDD_MOVEPIER                    258
#define IDD_CONCRETE_DETAILS            259
#define IDD_STRUCTURAL_ANALYSIS_METHOD  260
#define IDR_SELECTED_PIER_CONTEXT       262
#define IDR_SELECTED_SPAN_CONTEXT       263
#define IDD_GIRDERLAYOUT                264
#define IDR_GIRDER_GRID_CONTEXT         265
#define IDD_SPANCONNECTIONS             268
#define IDD_SPANLAYOUT                  269
#define IDD_PIERLAYOUT                  270
#define IDD_PIERCONNECTIONS             271
#define IDD_GIRDERSPACING               272
#define IDD_BRIDGEDESC_FRAMING          274
#define IDR_FRAMING_GRID_CONTEXT        275
#define IDD_BRIDGEDESC_RAILINGSYSTEM    276
#define IDD_SELECT_ITEM                 277
#define IDD_UIHINTS                     278
#define IDD_RESOLVE_GIRDER_SPACING      281
#define IDR_REPORTS                     293
#define IDD_GIRDERLABELFORMAT           294
#define IDI_EARTH                       296
#define IDD_RATING_OPTIONS              299
#define IDD_DESIGN_RATING               300
#define IDI_ICON1                       301
#define IDD_LEGAL_RATING                302
#define IDD_PERMIT_RATING               303
#define IDD_GIRDERDESC_RATING           304
#define IDD_BRIDGEDESC_RATING           305
#define IDD_MANAGE_PLUGINS              307
#define IDD_CONSTRUCTION_LOADS          308
#define IDB_GIRDERDESIGNER              309
#define IDI_EDIT_BRIDGE                 311
#define IDM_NEWLOADS                    312
#define IDR_NEWLOADS                    312
#define IDI_EDIT_GIRDER                 313
#define IDI_LIVELOAD                    314
#define IDI_RF                          315
#define IDI_COPY_PROPERTIES             316
#define IDD_MULTI_GIRDER_SELECT         317
#define IDR_COPY_PASTE                  318
#define IDD_LLDF_FILL                   319
#define IDD_BRIDGEVIEW_SETTINGS         322
#define IDD_LOAD_FACTORS                323
#define IDD_GIRDER_SELECT_STRANDS       324
#define IDR_PGSUPER_TEMPLATE_ICON       500
#define IDC_BRIDGE                      1000
#define IDC_BULB                        1001
#define IDC_BRIDGEID                    1002
#define IDC_JOBNUMBER                   1004
#define IDC_ENGINEER                    1006
#define IDC_BEARING_OFFSET              1006
#define IDC_COMPANY                     1007
#define IDC_RIGHT_BEARING_OFFSET        1007
#define IDC_RIGHT_END_DISTANCE          1008
#define IDC_FC                          1009
#define IDC_DESCRIPTION                 1009
#define IDC_COMMENTS                    1010
#define IDC_DS                          1011
#define IDC_MILD_STEEL_SELECTOR         1013
#define IDC_DW                          1014
#define IDC_RADIO2                      1015
#define IDC_AGG_SIZE                    1016
#define IDC_POI                         1017
#define IDC_BACK_DIAPHRAGM_OFFSET       1017
#define IDC_VALUE                       1018
#define IDC_SERVICE_IA_DW               1018
#define IDC_AHEAD_DIAPHRAGM_OFFSET      1018
#define IDC_RADIO3                      1020
#define IDC_STRENGTH_I_DW_MIN           1020
#define IDC_UPDATEDESIGN                1021
#define IDC_STRENGTH_I_DW_MAX           1021
#define IDC_PROFILE                     1022
#define IDC_STRENGTH_II_DW_MIN          1022
#define IDC_RADIO_IGNORE_LEVER          1023
#define IDC_STRENGTH_II_DW_MAX          1023
#define IDC_NUMERIC                     1024
#define IDC_FATIGUE_I_DW                1024
#define IDC_DIAPHRAGM_HEIGHT            1024
#define IDC_BACK_DIAPHRAGM_HEIGHT       1024
#define IDC_LIST                        1025
#define IDC_DIAPHRAGM_WIDTH             1025
#define IDC_BACK_DIAPHRAGM_WIDTH        1025
#define IDC_VALUE_UNITS                 1026
#define IDC_AHEAD_DIAPHRAGM_HEIGHT      1026
#define IDC_EXPOSURE                    1027
#define IDC_BEARING_OFFSET_T            1027
#define IDC_AHEAD_DIAPHRAGM_WIDTH       1027
#define IDC_RELHUMIDITY                 1028
#define IDC_DIAPHRAGM_HEIGHT_T          1028
#define IDC_BACK_DIAPHRAGM_HEIGHT_T     1028
#define IDC_INSERTROW                   1029
#define IDC_DIAPHRAGM_WIDTH_T           1029
#define IDC_BACK_DIAPHRAGM_WIDTH_T      1029
#define IDC_REFDIR                      1030
#define IDC_END_DISTANCE_T              1030
#define IDC_AHEAD_DIAPHRAGM_HEIGHT_T    1030
#define IDC_REMOVEROWS                  1031
#define IDC_RIGHT_BEARING_OFFSET_T      1031
#define IDC_DIRECTION                   1032
#define IDC_RIGHT_END_DISTANCE_T        1032
#define IDC_PIER1_STATION               1033
#define IDC_AHEAD_DIAPHRAGM_WIDTH_T     1033
#define IDC_RESTORE_DEFAULTS            1034
#define IDC_APPEND_ROW                  1035
#define IDC_PIER2_STATION               1036
#define IDC_STATIONFMT                  1037
#define IDC_LONG_GRID                   1038
#define IDC_PIER1_ORIENTATION           1039
#define IDC_PIER1_TYPE                  1040
#define IDC_PIER2_ORIENTATION           1041
#define IDC_PIER2_TYPE                  1042
#define IDC_ORIENTATIONFMT              1043
#define IDC_PIER1_GDRSPACING            1044
#define IDC_PIER2_GDRSPACING            1045
#define IDC_FC_UNIT                     1046
#define IDC_PIER2_GDRSPACING_UNIT       1047
#define IDC_DS_UNIT                     1048
#define IDC_PIER1_GDRSPACING_UNIT       1049
#define IDC_DW_UNIT                     1050
#define IDC_NUMGDR                      1051
#define IDC_AGG_SIZE_UNIT               1052
#define IDC_NUMGDR_SPIN                 1053
#define IDC_GDR_TYPE                    1054
#define IDC_NUMGDR_AHEAD                1055
#define IDC_NUMGDR_NEXT_SPAN            1056
#define IDC_GDR_CONCTYPE                1057
#define IDC_CBSLAB_TYPE                 1058
#define IDC_NUMGDR_SPIN_AHEAD           1059
#define IDC_NUMGDR_SPIN_NEXT_SPAN       1060
#define IDC_GROSS_DEPTH                 1061
#define IDC_OVERHANG                    1062
#define IDC_LEFTOVERHANG                1063
#define IDC_ADIM                        1064
#define IDC_SLAB_CONCRETE               1065
#define IDC_SLAB_FC                     1066
#define IDC_OLAY_DENSITY_LABEL          1068
#define IDC_OLAY_DENSITY                1069
#define IDC_SACDEPTH                    1070
#define IDC_OLAY_DENSITY_UNIT           1072
#define IDC_SACDEPTH_UNIT               1073
#define IDC_ADIM_UNIT                   1074
#define IDC_OVERHANG_UNIT               1076
#define IDC_LEFTOVERHANG_UNIT           1078
#define IDC_GROSS_DEPTH_UNIT            1079
#define IDC_SLAB_FC_UNIT                1080
#define IDC_DIAPHRAGM_LAYOUT            1081
#define IDC_SLAB_DS                     1082
#define IDC_SPAN                        1083
#define IDC_SLAB_DS_UNIT                1084
#define IDC_OLAY_WEIGHT_LABEL           1085
#define IDC_GIRDER                      1086
#define IDC_SLAB_MA                     1087
#define IDC_GIRDER2                     1087
#define IDC_OLAY_DEPTH_LABEL            1088
#define IDC_DETAIL_STIRRUPS             1089
#define IDC_LOAD_CASE                   1090
#define IDC_SLAB_MA_UNIT                1091
#define IDC_LOSSES                      1092
#define IDC_SHOW_PS_CG                  1092
#define IDC_ACTION                      1093
#define IDC_RIGHTOVERHANG               1094
#define IDC_OLAY_WEIGHT                 1095
#define IDC_STAGE                       1096
#define IDC_RIGHTOVERHANG_UNIT          1097
#define IDC_OLAY_WEIGHT_UNIT            1098
#define IDC_FCI                         1099
#define IDC_TRAFFICBARRIER2             1100
#define IDC_OLAY_DEPTH                  1101
#define IDC_TEST_SERVER                 1101
#define IDC_FCI_UNIT                    1102
#define IDC_OLAY_DEPTH_UNIT             1102
#define IDC_GRADE250                    1104
#define IDC_GRADE1725                   1105
#define IDC_SLAB_DW                     1106
#define IDC_GRADE270                    1107
#define IDC_GRADE1860                   1108
#define IDC_SLAB_DW_UNIT                1109
#define IDC_LOWRELAX                    1110
#define IDC_STRESSREL                   1111
#define IDC_STRAND_SIZE                 1112
#define IDC_XFERTIME                    1113
#define IDC_STRAND_SIZE2                1113
#define IDC_TEMP_STRAND_SIZE            1113
#define IDC_XFERTIME_SPIN               1114
#define IDC_XFERTIME_UNIT               1115
#define IDC_HPOFFSET_END                1116
#define IDC_HPOFFSET_END_UNIT           1118
#define IDC_HPOFFSET_HP                 1119
#define IDC_HPOFFSET_HP_UNIT            1120
#define IDC_NUM_SS                      1121
#define IDC_NUM_SS_SPIN                 1122
#define IDC_NUM_HS                      1123
#define IDC_NUM_HS_SPIN                 1124
#define IDC_SS_JACK                     1125
#define IDC_SS_JACK_FORCE               1126
#define IDC_HS_JACK                     1127
#define IDC_HS_JACK_FORCE               1128
#define IDC_SS_JACK_FORCE_UNIT          1129
#define IDC_HS_JACK_FORCE_UNIT          1130
#define IDC_TRAFFICBARRIER              1131
#define IDC_SPEC                        1132
#define IDC_NUM_TEMP                    1133
#define IDC_LEFT_TRAFFICBARRIER         1134
#define IDC_SPACING                     1135
#define IDC_NUM_TEMP_SPIN               1136
#define IDC_SPACING_UNIT                1137
#define IDC_TEMP_JACK                   1138
#define IDC_ENGINEER_NAME               1139
#define IDC_TEMP_JACK_FORCE             1140
#define IDC_RIGHT_TRAFFICBARRIER        1141
#define IDC_COMPANY_NAME                1142
#define IDC_TEMP_JACK_FORCE_UNIT        1143
#define IDC_USER_TEMPLATE_BROWSE        1144
#define IDC_WORKGROUP_TEMPLATE_LOCATION 1145
#define IDC_LABEL_PIERS                 1146
#define IDC_WORKGROUP_TEMPLATE_BROWSE   1147
#define IDC_DIAPHRAGM_OFFSET_UNITS      1147
#define IDC_BACK_DIAPHRAGM_OFFSET_UNITS 1147
#define IDC_LABEL_GIRDERS               1148
#define IDC_CONNECTION_MF               1148
#define IDC_LIBRARY_FILE_LOCATION       1149
#define IDC_AHEAD_DIAPHRAGM_OFFSET_UNITS 1149
#define IDC_LABEL_ALIGNMENT             1150
#define IDC_SHOW_DIMENSIONS             1151
#define IDC_LIBRARY_FILE_BROWSE         1152
#define IDC_TIP_FILE_LOCATION           1153
#define IDC_SHOW_STIRRUPS               1154
#define IDC_SHOW_SCHEMATIC              1155
#define IDC_SHOW_STRANDS                1157
#define IDC_SHOW_LONG_REINF             1158
#define IDC_SHOW_SHOW_LONG_REINF        1159
#define IDC_CHANGE_SECTION              1160
#define IDC_SECTION_CUT                 1161
#define IDC_GRID                        1162
#define IDC_SELECT_GIRDERS              1163
#define IDC_LLDF_FILL2                  1163
#define IDC_SELECT_ALL                  1163
#define IDC_EDIT_STRAND_FILL            1163
#define IDC_COPY                        1163
#define IDC_COPY_TO_END                 1163
#define IDC_PRINT                       1164
#define IDC_SELECT_ALL2                 1164
#define IDC_CLEAR_ALL                   1164
#define IDC_COPY_TO_START               1164
#define IDC_VIEWDETAILS                 1165
#define IDC_COPY_MATERIAL               1166
#define IDC_EDIT_LOAD                   1167
#define IDD_ADD                         1168
#define IDC_ADD                         1169
#define IDC_ADD_PIER                    1170
#define IDC_RESTORE_DEFAULTS1           1171
#define IDC_BACK_COPY                   1172
#define IDC_FIX_BRIDGE                  1173
#define IDC_AHEAD_COPY                  1174
#define IDC_UPDATE_STIRRUPS             1175
#define IDC_OUTCOME                     1176
#define IDC_BROWSER                     1177
#define IDC_DETAILS                     1178
#define IDC_LEFT_END                    1179
#define IDC_RADIO4                      1180
#define IDC_UPDATEDESIGN_NO             1181
#define IDC_RADIO_LEVER                 1182
#define IDC_LEFT_HARP                   1183
#define IDC_GIRDER_MIDDLE               1184
#define IDC_RIGHT_HARP                  1186
#define IDC_DESIGN_FLEXURE              1187
#define IDC_RIGHT_END                   1188
#define IDC_DESIGN_SHEAR                1189
#define IDC_SS_TITLE                    1190
#define IDC_USER_CUT                    1191
#define IDC_HS_TITLE                    1192
#define IDC_DESIGN_A                    1193
#define IDC_TEMP_TITLE                  1194
#define IDC_HPOFFSET_END_TITLE          1195
#define IDC_HPOFFSET_END_NOTE           1196
#define IDC_HPOFFSET_HP_TITLE           1197
#define IDC_HPOFFSET_HP_NOTE            1198
#define IDC_LIFTING_LOOP_LOCATION       1199
#define IDC_TRUCK_SUPPORT_LOCATION      1200
#define IDC_TRAILINGOVERHANG            1201
#define IDC_LIFTING_LOOP_LOCATION_UNITS 1202
#define IDC_TRUCK_SUPPORT_LOCATION_UNITS 1203
#define IDC_TRAILINGOVERHANG_UNITS      1204
#define IDC_ALIGNMENT                   1205
#define IDC_LEADINGOVERHANG             1206
#define IDC_PI_STATION                  1207
#define IDC_LEADINGOVERHANG_UNITS       1208
#define IDC_FWD_TANGENT                 1209
#define IDC_BK_TANGENT                  1210
#define IDC_RADIUS                      1211
#define IDC_CREEP_K1                    1212
#define IDC_GRADE                       1213
#define IDC_CREEP_K2                    1213
#define IDC_G1                          1214
#define IDC_SHRINKAGE_K1                1214
#define IDC_GRADE_TAG                   1215
#define IDC_SHRINKAGE_K2                1215
#define IDC_G1_TAG                      1216
#define IDC_G2                          1217
#define IDC_PVI_STATION                 1218
#define IDC_PVI_ELEVATION               1219
#define IDC_PVI_ELEVATION_TAG           1220
#define IDC_LENGTH                      1221
#define IDC_LENGTH_TAG                  1222
#define IDC_LEFT_CROWN                  1223
#define IDC_LEFT_CROWN_TAG              1224
#define IDC_RIGHT_CROWN                 1225
#define IDC_PI_STATION_LABEL            1226
#define IDC_FWD_TANGENT_LABEL           1227
#define IDC_BK_TANGENT_LABEL            1228
#define IDC_RADIUS_LABEL                1229
#define IDC_DIRECTION_LABEL             1230
#define IDC_DIRECTION_TAG               1231
#define IDC_PI_STATION_TAG              1232
#define IDC_FWD_TANGENT_TAG             1233
#define IDC_BK_TANGENT_TAG              1234
#define IDC_RADIUS_TAG                  1236
#define IDC_GRADE_LABEL                 1237
#define IDC_G1_LABEL                    1238
#define IDC_G2_LABEL                    1239
#define IDC_FILLET                      1240
#define IDC_PVI_STATION_LABEL           1241
#define IDC_FILLET_UNIT                 1242
#define IDC_PVI_ELEVATION_LABEL         1243
#define IDC_LENGTH_LABEL                1244
#define IDC_G2_TAG                      1245
#define IDC_BEARING_OFFSET_MEASURE      1245
#define IDC_PVI_STATION_TAG             1246
#define IDC_END_DISTANCE_MEASURE        1246
#define IDC_CURVED_ALIGNMENT            1247
#define IDC_VC_PROFILE                  1248
#define IDC_STATION_LABEL               1249
#define IDC_STATION                     1250
#define IDC_ELEVATION_LABEL             1251
#define IDC_ELEVATION                   1252
#define IDC_ELEVATION_TAG               1253
#define IDC_STATION_TAG                 1254
#define IDC_RIGHT_CROWN_TAG             1255
#define IDC_ENTRY_TEXT                  1257
#define IDC_EDIT1                       1259
#define IDC_CONDITION_FACTOR            1259
#define IDC_STRENGTH_I_DC               1259
#define IDC_FY_COEFFICIENT              1259
#define IDC_LOAD                        1259
#define IDC_START_SPAN_EDIT             1259
#define IDC_CONNECTION_TYPE             1259
#define IDC_LOCATION                    1260
#define IDC_SERVICE_III_DC              1260
#define IDC_K1                          1261
#define IDC_EC_K1                       1261
#define IDC_TOP_COVER                   1262
#define IDC_EC_K2                       1262
#define IDC_EDIT                        1263
#define IDC_SUPERSTRUCTURE_DESCRIPTION  1264
#define IDC_NAME                        1265
#define IDC_DESIGN_TRUCK_IMPACT         1266
#define IDC_SPAN_LENGTH                 1267
#define IDC_SERVER_TYPE                 1267
#define IDC_ORIENTATION                 1268
#define IDC_LEFT_SIDEWALK_LEFT_DEPTH    1269
#define IDC_REFSTATION                  1271
#define IDC_ADIM_START                  1272
#define IDC_START_SLAB_OFFSET           1273
#define IDC_TOP_COVER_UNIT              1274
#define IDC_MAGNITUDE                   1275
#define IDC_LOCATION2                   1276
#define IDC_RIGHT_MAGNITUDE             1277
#define IDC_RIGHT_SIDEWALK_LEFT_DEPTH   1278
#define IDC_ALIGNMENTOFFSET_LABEL       1279
#define IDC_ADIM_END                    1280
#define IDC_FATIGUE_TRUCK_IMPACT        1281
#define IDC_PERMIT_TRUCK_IMPACT         1282
#define IDC_BOTTOM_COVER                1283
#define IDC_PERMIT_TRUCK_IMPACT2        1283
#define IDC_SPAN_GIRDER                 1284
#define IDC_LOCATION3                   1285
#define IDC_RIGHT_LOCATION              1286
#define IDC_BOTTOM_COVER_UNIT           1287
#define IDC_LOCATION4                   1289
#define IDC_LEFT_MAGNITUDE              1290
#define IDC_TOP_MAT_BAR_SPACING         1291
#define IDC_TOP_MAT_BAR_SPACING_UNIT    1293
#define IDC_TOP_MAT_LUMP_SUM            1294
#define IDC_FROM_LIST                   1295
#define IDC_TOP_MAT_LUMP_SUM_UNIT       1296
#define IDC_TO_LIST                     1297
#define IDC_BOTTOM_MAT_BAR_SPACING      1298
#define IDC_COPY_PRESTRESSING           1299
#define IDC_BOTTOM_MAT_BAR_SPACING_UNIT 1300
#define IDC_COPY_TRANSVERSE             1301
#define IDC_CONFLICT_TOP                1302
#define IDC_BOTTOM_MAT_LUMP_SUM         1303
#define IDC_COPY_HANDLING               1304
#define IDC_CONFLICT_BOTTOM             1305
#define IDC_BOTTOM_MAT_LUMP_SUM_UNIT    1306
#define IDC_LIC_TEXT                    1307
#define IDC_ALIGNMENTOFFSET             1308
#define IDC_DECK                        1309
#define IDC_DISCLAIMER                  1310
#define IDC_CHECK                       1311
#define IDC_STATIC_BOX                  1313
#define IDC_LEFT_DENSITY_LABEL          1314
#define IDC_END_SLAB_OFFSET2            1315
#define IDC_RIGHT_DENSITY_LABEL         1316
#define IDC_STATIC_TEXT                 1317
#define IDC_GDR_SECTION                 1318
#define IDC_SLAB_TYPE                   1319
#define IDC_DEPTH_LABEL                 1320
#define IDC_GROSS_DEPTH_LABEL           1321
#define IDC_PANEL_DEPTH                 1322
#define IDC_PANEL_DEPTH_UNIT            1323
#define IDC_PANEL_SUPPORT               1324
#define IDC_PANEL_SUPPORT_UNIT          1325
#define IDC_DEPTH_LABEL2                1326
#define IDC_LLDF_COMPUTE                1327
#define IDC_LLDF_LEVER_RULE             1328
#define IDC_LLDF_INPUT                  1329
#define IDC_LLDF_MOMENT                 1330
#define IDC_INT_LLDF_MOMENT             1331
#define IDC_LLDF_SHEAR                  1332
#define IDC_INT_LLDF_SHEAR              1333
#define IDC_LLDF_REACTION               1334
#define IDC_INT_LLDF_REACTION           1335
#define IDC_EXT_LLDF_MOMENT             1336
#define IDC_EXT_LLDF_SHEAR              1337
#define IDC_EXT_LLDF_REACTION           1338
#define IDC_CONC_ENTRIES                1339
#define IDC_WARNING                     1340
#define IDC_WARNOTE                     1341
#define IDC_SERVICE_I_LLIM              1341
#define IDC_STATUSLIST                  1342
#define IDC_DESIGN_LL_LIST              1343
#define IDC_SERVICE_IA_DC               1343
#define IDC_SPANS                       1344
#define IDC_SERVICE_IA_LLIM             1344
#define IDC_DESIGN_HL93                 1345
#define IDC_GIRDERS                     1346
#define IDC_SERVICE_III_LLIM            1346
#define IDC_FATIGUE_LL_LIST             1347
#define IDC_STRENGTH_I_DC_MIN           1347
#define IDC_STRENGTH_LL_LIST            1348
#define IDC_STRENGTH_I_LLIM             1348
#define IDC_MEASURED_FROM               1349
#define IDC_STRENGTH_I_DC_MAX           1349
#define IDC_STRENGTH_HL93               1350
#define IDC_STRENGTH_II_DC_MIN          1350
#define IDC_LOCATION_UNITS              1351
#define IDC_STRENGTH_II_DC_MAX          1351
#define IDC_FRACTIONAL                  1352
#define IDC_STRENGTH_II_LLIM            1352
#define IDC_MAGNITUDE_UNITS             1353
#define IDC_FATIGUE_I_DC                1353
#define IDC_LOADCASE                    1354
#define IDC_FATIGUE_I_LLIM              1354
#define IDC_TEMPORARY                   1356
#define IDC_MAGNITUDE_UNITS2            1357
#define IDC_LOADTYPE                    1358
#define IDC_LOADS_LIST                  1359
#define IDC_ANALYSIS                    1360
#define IDC_DELETE_LOAD                 1361
#define IDC_ADD_POINTLOAD               1362
#define IDC_ADD_NEW_DISTRIBUTED         1363
#define IDC_LEFT_LOCATION               1364
#define IDC_LEFT_ENDSTATIC              1365
#define IDC_RIGHT_END_STATIC            1366
#define IDC_LOCATION_STATIC             1367
#define IDC_MESSAGE                     1370
#define IDC_SPAN_LENGTH_CTRL            1371
#define IDC_LOAD_STATIC                 1372
#define IDC_SELSTAGE                    1373
#define IDC_LOADS                       1374
#define IDC_POINT_LOAD_DRAG             1375
#define IDC_GIRDER_FC                   1376
#define IDC_DISTRIBUTED_LOAD_DRAG       1377
#define IDC_GIRDER_FC_UNIT              1378
#define IDC_MOMENT_LOAD_DRAG            1379
#define IDC_GIRDER_MA                   1380
#define IDC_GIRDER_MA_UNIT              1381
#define IDC_GIRDER_DS                   1382
#define IDC_GIRDER_DS_UNIT              1383
#define IDC_GIRDER_DW                   1384
#define IDC_GIRDER_DW_UNIT              1385
#define IDC_CHOICE                      1386
#define IDC_SHOW_LEGEND                 1387
#define IDC_HAULINGOVERHANGS            1388
#define IDC_GIRDERLENGTH                1389
#define IDC_GIRDERLENGTH_UNIT           1390
#define IDC_MAXOVERHANG                 1394
#define IDC_SUPPORT_WIDTH               1394
#define IDC_OVERHANG_LABEL              1395
#define IDC_SUPPORT_WIDTH_T             1395
#define IDC_LEFTOVERHANG_LABEL          1396
#define IDC_RIGHT_SUPPORT_WIDTH         1396
#define IDC_FILLET_LABEL                1397
#define IDC_RIGHT_SUPPORT_WIDTH_T       1397
#define IDC_PANEL_DEPTH_LABEL           1398
#define IDC_PANEL_SUPPORT_LABEL         1399
#define IDC_ADIM_LABEL                  1400
#define IDC_SLAB_FC_LABEL               1401
#define IDC_SLAB_DS_LABEL               1402
#define IDC_SLAB_DW_LABEL               1403
#define IDC_SLAB_MA_LABEL               1404
#define IDC_SACDEPTH_LABEL              1405
#define IDC_RIGHTOVERHANG_LABEL         1406
#define IDC_COMBO1                      1407
#define IDC_RATING_CRITERIA             1407
#define IDC_PERMIT_TYPE                 1407
#define IDC_CONDITION_FACTOR_TYPE       1407
#define IDC_CONCRETE_TYPE               1407
#define IDC_GIRDER_SPAN                 1407
#define IDC_DESIGN_PEDES_COMBO          1407
#define IDC_COMBO_VIEWLOC               1407
#define IDC_BACK_DIAPHRAGM_LOAD         1407
#define IDC_GIRDER_ORIENTATION          1408
#define IDC_GIRDER_GIRDER               1408
#define IDC_AHEAD_DIAPHRAGM_LOAD        1408
#define IDC_PIER                        1409
#define IDC_FATIGUE_PEDES_COMBO         1409
#define IDC_HP_COMBO_END                1410
#define IDC_PIER_GIRDER                 1410
#define IDC_DESIGN_PEDES_COMBO4         1410
#define IDC_PERMIT_PEDES_COMBO          1410
#define IDC_TOP_MAT_BAR                 1411
#define IDC_UPDATE_FREQUENCY            1412
#define IDC_OVERHANG_TAPER              1413
#define IDC_GIRDER_END                  1414
#define IDC_RESIZEOPTIONS               1415
#define IDC_GIRDER_NAME                 1416
#define IDC_PREV_PIER_SPACING_MEASUREMENT_LOCATION 1417
#define IDC_MOVE_PIER                   1418
#define IDC_BACK_PIER_SPACING_MEASUREMENT 1419
#define IDC_PREV_SPAN_SPACING_MEASUREMENT 1420
#define IDC_ROA_CB                      1421
#define IDC_FROM_SPAN                   1422
#define IDC_COMBO2                      1423
#define IDC_CONDITION_FACTOR_LIST       1423
#define IDC_HARP_END_CB                 1423
#define IDC_HP_COMBO_HP                 1424
#define IDC_HARP_HP_CB                  1424
#define IDC_BOTTOM_MAT_BAR              1425
#define IDC_LEFT_CONNECTION             1426
#define IDC_GIRDER_SPACING_MEASURE      1427
#define IDC_WEARINGSURFACETYPE          1428
#define IDC_SERVERS                     1429
#define IDC_NEXT_PIER_SPACING_MEASUREMENT_LOCATION 1430
#define IDC_LINK_SOURCE                 1431
#define IDC_AHEAD_PIER_SPACING_MEASUREMENT 1432
#define IDC_NEXT_SPAN_SPACING_MEASUREMENT 1433
#define IDC_MEASUREMENT_DATUM           1434
#define IDC_FROM_GIRDER                 1435
#define IDC_RIGHT_CONCRETE_LABEL        1436
#define IDC_RIGHT_CONNECTION            1437
#define IDC_PREV_PIER_SPACING_MEASUREMENT_TYPE 1438
#define IDC_NEXT_PIER_SPACING_MEASUREMENT_TYPE 1439
#define IDC_K1_LABEL                    1440
#define IDC_EC_K1_LABEL                 1440
#define IDC_DEBOND_HARPED               1441
#define IDC_EC_K2_LABEL                 1441
#define IDC_DEBOND_STRAIGHT             1442
#define IDC_DEBOND_GRID                 1443
#define IDC_DELETE                      1444
#define IDC_HAS_AGG_STRENGTH            1444
#define IDC_PICTURE                     1445
#define IDC_CHECK1                      1446
#define IDC_RATE_FOR_SHEAR              1446
#define IDC_DESIGN                      1446
#define IDC_START_WITH_LAYOUT           1446
#define IDC_CHECK_SYMM                  1446
#define IDC_SYMMETRIC_DEBOND            1447
#define IDC_FUTURE_WS                   1448
#define IDC_MOD_ECI                     1449
#define IDC_CHECK_ADIM                  1450
#define IDC_LONGITUDINAL_REBAR          1451
#define IDC_SHOW_DIALOG                 1453
#define IDC_UPDATE_NOW                  1454
#define IDC_EXTENDED                    1455
#define IDC_NORTH_UP                    1456
#define IDC_SHOW_TRANSV_REINF           1457
#define IDC_SYNC                        1458
#define IDC_MIRROR_LINK                 1459
#define IDC_SYMMETRICAL_GIRDER_LAYOUT   1460
#define IDC_SAME_NUM_GIRDERLINES        1461
#define IDC_SAME_GIRDER_SPACING         1462
#define IDC_RIGHT_SIDEWALK              1463
#define IDC_IGNORE_ROA                  1464
#define IDC_DONTSHOWAGAIN               1465
#define IDC_SAMESLABOFFSET              1466
#define IDC_SPACING_LABEL               1467
#define IDC_ALIGNMENTOFFSET_UNIT        1468
#define IDC_ALIGNMENTOFFSET_FMT         1469
#define IDC_HCURVE_GRID                 1470
#define IDC_REMOVE                      1471
#define IDC_SORT                        1472
#define IDC_VCURVE_GRID                 1473
#define IDC_ELEVATION_UNIT              1474
#define IDC_PIER_GRID                   1475
#define IDC_REMOVE_PIER                 1476
#define IDC_LAYOUT                      1477
#define IDC_SIMPLE                      1478
#define IDC_SIMPLE2                     1479
#define IDC_SIMPLE3                     1480
#define IDC_STATION_RANGE               1481
#define IDC_MOD_E                       1482
#define IDC_EC                          1483
#define IDC_EC_UNIT                     1484
#define IDC_ECI                         1485
#define IDC_ECI_UNIT                    1486
#define IDC_MOD_EC                      1487
#define IDC_STRAND_INPUT_TYPE           1488
#define IDC_HARP_STRAIGHT               1489
#define IDC_STATIC_LL                   1490
#define IDC_STATIC_LLE                  1491
#define IDC_STATIC_SL                   1492
#define IDC_STATIC_TLSO                 1493
#define IDC_AGG_STRENGTH                1493
#define IDC_STATIC_SLLO                 1494
#define IDC_AGG_STRENGTH_T              1494
#define IDC_STATICSLGL                  1495
#define IDC_CHECK_LIFTING               1496
#define IDC_CHECK_HAULING               1497
#define IDC_CHECK_SLOPE                 1498
#define IDC_CHECK_HOLDDOWN              1499
#define IDC_LEFT_BOUNDARY_CONDITIONS    1500
#define IDC_RIGHT_BOUNDARY_CONDITIONS   1501
#define IDC_CATALOG                     1502
#define IDC_CATALOG_LIST                1503
#define IDC_GENERIC                     1504
#define IDC_DOWNLOAD                    1505
#define IDC_PUBLISHERS                  1506
#define IDC_LOCAL                       1507
#define IDC_FIRST_RUN                   1508
#define IDC_DECK_TYPE                   1509
#define IDC_OVERHANG_DEPTH              1510
#define IDC_OVERHANG_DEPTH_UNIT         1511
#define IDC_OVERHANG_DEPTH_LABEL        1513
#define IDC_CREEP_K1_LABEL              1513
#define IDC_ADD_MOMENTLOAD              1514
#define IDC_CREEP_K2_LABEL              1514
#define IDC_ALLOWABLE_SPACING           1515
#define IDC_SHRINKAGE_K1_LABEL          1515
#define IDC_GIRDER_CONNECTIVITY_S       1516
#define IDC_SHRINKAGE_K2_LABEL          1516
#define IDC_GIRDER_CONNECTIVITY         1517
#define IDC_URL                         1518
#define IDC_UPDATENOW                   1519
#define IDC_DESIGN_LANE_IMPACT          1520
#define IDC_BEAM_FAMILIES               1521
#define IDC_FATIGUE_LANE_IMPACT         1522
#define IDC_PERMIT_LANE_IMPACT          1523
#define IDC_NUMSTRAIGHT                 1524
#define IDC_PERMIT_LANE_IMPACT2         1524
#define IDC_NUM_DEBONDED                1525
#define IDC_PERCENT_DEBONDED            1526
#define IDC_MORE                        1527
#define IDC_PERCENT_DEBONDED2           1527
#define IDC_NUM_EXTENDED                1527
#define IDC_EXTENDED_LEFT               1527
#define IDC_NUM_EXTENDED_LEFT           1527
#define IDC_GIRDERGRID                  1528
#define IDC_EXTENDED_RIGHT              1528
#define IDC_NUM_EXTENDED_LEFT2          1528
#define IDC_NUM_EXTENDED_RIGHT          1528
#define IDC_PREV_PIER_SPACING_LABEL     1529
#define IDC_PREV_SPAN_SPACING_LABEL     1529
#define IDC_NEXT_PIER_SPACING_LABEL     1530
#define IDC_NEXT_SPAN_SPACING_LABEL     1530
#define IDC_PREV_PIER_SPACING_GRID      1531
#define IDC_BACK_BOUNDARY_CONDITIONS    1532
#define IDC_NEXT_PIER_SPACING_GRID      1533
#define IDC_SYSTEM_FACTOR_FLEXURE       1533
#define IDC_BACK_CONNECTION             1534
#define IDC_SYSTEM_FACTOR_SHEAR         1534
#define IDC_AHEAD_CONNECTION            1535
#define IDC_URL_STATIC                  1535
#define IDC_AHEAD_BOUNDARY_CONDITIONS   1536
#define IDC_STRENGTH_I_LL_INVENTORY     1536
#define IDC_TEMPLATE_STATIC             1536
#define IDC_UPDATES_STATIC              1536
#define IDC_AHEAD_GROUP                 1537
#define IDC_STRENGTH_I_DW               1537
#define IDC_PUBLISHER_HYPERLINK         1537
#define IDC_BACK_GROUP                  1538
#define IDC_STRENGTH_I_LL_OPERATING     1538
#define IDC_SPAN_LABEL                  1539
#define IDC_SERVICE_III_DW              1539
#define IDC_STATIC_EARTH                1539
#define IDC_SPAN_LENGTH_UNIT            1540
#define IDC_SERVICE_III_LL              1540
#define IDC_PIER_LABEL                  1541
#define IDC_ALLOWABLE_TENSION           1541
#define IDC_STATION_FORMAT              1542
#define IDC_ALLOWABLE_TENSION_UNIT      1542
#define IDC_ORIENTATION_FORMAT          1543
#define IDC_ROUTINE_LIVELOAD            1543
#define IDC_LINK_ORIENTATION            1544
#define IDC_SPECIAL_LIVELOAD            1544
#define IDC_NUMGDR_BACK                 1545
#define IDC_EXCLUDE_LANELOAD            1545
#define IDC_NUMGDR_PREV_SPAN            1546
#define IDC_COMBO3                      1546
#define IDC_ADTT                        1546
#define IDC_NUMGDR_SPIN_BACK            1547
#define IDC_STRENGTH_I_LL_ROUTINE       1547
#define IDC_NUMGDR_SPIN_PREV_SPAN       1548
#define IDC_STRENGTH_I_LL_SPECIAL       1548
#define IDC_MOVE_LABEL                  1549
#define IDC_SERVICE_III_LL_ROUTINE      1549
#define IDC_SAME_GIRDERNAME             1550
#define IDC_SERVICE_III_LL_SPECIAL      1550
#define IDC_SAME_GIRDERSPACING          1551
#define IDC_ROUTINE_TRUCK_IMPACT        1551
#define IDC_AHEAD_NOTE                  1552
#define IDC_ROUTINE_LANE_IMPACT         1552
#define IDC_BACK_NOTE                   1553
#define IDC_SPECIAL_TRUCK_IMPACT        1553
#define IDC_PERMIT_LIVELOAD             1553
#define IDC_NUMGDR_NOTE                 1554
#define IDC_SPECIAL_LANE_IMPACT         1554
#define IDC_STRENGTH_II_DC              1554
#define IDC_GIRDERGRID_NOTE             1555
#define IDC_STRENGTH_II_DW              1555
#define IDC_PREV_PIER_GIRDER_SPACING_MEASURE 1556
#define IDC_STRENGTH_II_LL_PERMIT       1556
#define IDC_NEXT_PIER_GIRDER_SPACING_MEASURE 1557
#define IDC_SERVICE_I_DC                1557
#define IDC_GIRDER_SPACING_NOTE         1558
#define IDC_SERVICE_I_DW                1558
#define IDC_BACK_PIER_SPACING_GRID      1559
#define IDC_SERVICE_I_LL_PERMIT         1559
#define IDC_PREV_SPAN_SPACING_GRID      1560
#define IDC_LEGAL                       1560
#define IDC_PERMIT_LIVELOAD2            1560
#define IDC_AHEAD_PIER_SPACING_GRID     1561
#define IDC_CHECK3                      1561
#define IDC_PERMIT                      1561
#define IDC_STRENGTH_II_LL_PERMIT2      1561
#define IDC_NEXT_SPAN_SPACING_GRID      1562
#define IDC_CHECK2                      1562
#define IDC_CHECK_YIELDING              1562
#define IDC_RATE_FOR_STRESS             1562
#define IDC_PEDESTRIAN                  1562
#define IDC_SHOW_NUMBERS                1562
#define IDC_ADD_SPAN                    1563
#define IDC_FY_LABEL                    1563
#define IDC_REMOVE_SPAN                 1564
#define IDC_FY                          1564
#define IDC_LINK_TARGET_NOTE            1565
#define IDC_SERVICE_I_LL_PERMIT2        1565
#define IDC_NUMGDR_PREV_SPAN_LABEL      1566
#define IDC_NUMGDR_NEXT_SPAN_LABEL      1567
#define IDC_BACK_PIER_SPACING_LABEL     1568
#define IDC_AHEAD_PIER_SPACING_LABEL    1569
#define IDC_GIRDER_SPACING_NOTE_BACK    1570
#define IDC_GIRDER_SPACING_NOTE_END_OF_PREV_SPAN 1571
#define IDC_GIRDER_SPACING_NOTE_AHEAD   1572
#define IDC_GIRDER_SPACING_NOTE_START_OF_NEXT_SPAN 1573
#define IDC_NUM_GIRDER_AHEAD_NOTE       1574
#define IDC_NUM_GIRDER_NEXT_SPAN_NOTE   1575
#define IDC_NUM_GIRDER_BACK_NOTE        1576
#define IDC_SPAN_LENGTH_NOTE            1577
#define IDC_NUM_GIRDER_PREV_SPAN_NOTE   1578
#define IDC_BACKGROUP                   1579
#define IDC_AHEADGROUP                  1580
#define IDC_USER_TEMPLATE_LOCATION      1581
#define IDC_BACK_CONNECTION_LABEL       1582
#define IDC_BACK_BOUNDARY_CONDITIONS_LABEL 1583
#define IDC_AHEAD_CONNECTION_LABEL      1584
#define IDC_AHEAD_BOUNDARY_CONDITIONS_LABEL 1585
#define IDC_SAME_GIRDER_FAMILY          1586
#define IDC_GIRDER_ORIENTATION_LABEL    1587
#define IDC_GIRDER_NAME_LABEL           1588
#define IDC_GIRDER_FAMILY_NOTE          1589
#define IDC_GIRDER_FAMILY_LABEL         1590
#define IDC_DECK_TYPE_LABEL             1591
#define IDC_LEFT_SIDEWALK               1592
#define IDC_LEFT_SIDEWALK_WIDTH         1593
#define IDC_LEFT_SIDEWALK_WIDTH_UNIT    1594
#define IDC_LEFT_SIDEWALK_LEFT_DEPTH_UNIT 1595
#define IDC_LEFT_SIDEWALK_RIGHT_DEPTH   1596
#define IDC_DATA_IMPORTER_LIST          1596
#define IDC_PLUGIN_LIST                 1596
#define IDC_LEFT_SIDEWALK_RIGHT_DEPTH_UNIT 1597
#define IDC_LIST_TITLE                  1597
#define IDC_LEFT_EXTERIORBARRIER        1598
#define IDC_LEFT_INTERIORBARRIER        1599
#define IDC_LIST1                       1599
#define IDC_RIGHT_EXTERIORBARRIER       1600
#define IDC_LOAD_UNIT                   1600
#define IDC_RIGHT_INTERIORBARRIER       1601
#define IDC_HELPME                      1601
#define IDC_LEFT_INTERIOR_BARRIER       1602
#define IDC_LEFT_SIDEWALK_WIDTH_LABEL   1603
#define IDC_CONCRETE_TYPE_LABEL         1603
#define IDC_REF_GIRDER_LABEL            1603
#define IDC_LEFT_SIDEWALK_LEFT_DEPTH_LABEL 1604
#define IDC_REF_GIRDER_OFFSET_TYPE_LABEL 1604
#define IDC_RIGHT_INTERIOR_BARRIER      1605
#define IDC_TEMP_STRAND_SIZE_LABEL      1605
#define IDC_PREV_PIER_LABEL             1605
#define IDC_LEFT_SIDEWALK_RIGHT_DEPTH_LABEL 1606
#define IDC_SELECT_GRID                 1606
#define IDC_NEXT_PIER_LABEL             1606
#define IDC_RIGHT_SIDEWALK_WIDTH        1607
#define IDC_ADIM_STATIC                 1607
#define IDC_GIRDERNAME_NOTE             1608
#define IDC_LEFT_CONCRETE_TYPE_LABEL    1608
#define IDC_RIGHT_SIDEWALK_WIDTH_UNIT   1609
#define IDC_PIER_RADIO                  1609
#define IDC_COPY_GIRDER                 1610
#define IDC_RIGHT_CONCRETE_TYPE_LABEL   1610
#define IDC_FILL_STATIC                 1610
#define IDC_RIGHT_SIDEWALK_WIDTH_LABEL  1611
#define IDC_GIRDER_GIRDER_STATIC        1611
#define IDC_LABEL                       1612
#define IDC_PIER_GIRDER_STATIC          1612
#define IDC_RIGHT_SIDEWALK_LEFT_DEPTH_LABEL 1613
#define IDC_TEXT                        1614
#define IDC_NOTE                        1614
#define IDC_RIGHT_SIDEWALK_RIGHT_DEPTH_LABEL 1615
#define IDC_START_SPAN_SPIN             1615
#define IDC_NOTE2                       1615
#define IDC_RIGHT_SIDEWALK_LEFT_DEPTH_UNIT 1616
#define IDC_END_SPAN_EDIT               1616
#define IDC_ALIGNMENT_OFFSET            1617
#define IDC_END_SPAN_SPIN               1617
#define IDC_RIGHT_SIDEWALK_RIGHT_DEPTH  1618
#define IDC_DESIGN_PEDES_STATIC         1618
#define IDC_ALIGNMENT_OFFSET_UNIT       1619
#define IDC_FATIGUE_PEDES_STATIC        1619
#define IDC_RIGHT_SIDEWALK_RIGHT_DEPTH_UNIT 1620
#define IDC_PERMIT_PEDES_STATIC         1620
#define IDC_ALIGNMENT_OFFSET_FORMAT     1621
#define IDC_VERT_GROUP                  1621
#define IDC_ALIGNMENT_OFFSET_LABEL      1622
#define IDC_STRAND_GRID                 1622
#define IDC_SERVICE_IA_LABEL            1622
#define IDC_DECK_EDGE_LABEL             1623
#define IDC_SERVICE_IA_DC_LABEL         1623
#define IDC_GIRDER_SPACING_TYPE         1624
#define IDC_SERVICE_IA_DW_LABEL         1624
#define IDC_GIRDER_SPACING_LABEL        1625
#define IDC_SERVICE_IA_LLIM_LABEL       1625
#define IDC_PREV_PIER_GIRDER_SPACING_LABEL 1626
#define IDC_FATIGUE_I_DC_LABEL          1626
#define IDC_NEXT_PIER_GIRDER_SPACING_LABEL 1627
#define IDC_FATIGUE_I_LABEL             1627
#define IDC_ROA_STATIC                  1628
#define IDC_FATIGUE_I_DW_LABEL          1628
#define IDC_ROA_STATIC2                 1629
#define IDC_FATIGUE_I_LLIM_LABEL        1629
#define IDC_PREV_SPAN_CONSTANT_SPACING_NOTE 1630
#define IDC_GRID_STATIC                 1630
#define IDC_NEXT_SPAN_CONSTANT_SPACING_NOTE 1631
#define IDC_HARP_END_STATIC2            1631
#define IDC_RADIO_INPUT                 1632
#define IDC_HARP_HP_STATIC2             1632
#define IDC_RADIO_IGNORE                1633
#define IDC_HARP_END_UNIT               1633
#define IDC_DS_TITLE                    1634
#define IDC_HARP_END_UNIT2              1634
#define IDC_HARP_HP_UNIT                1634
#define IDS_E_CLASSNOTREG               1635
#define IDC_HARP_GROUP                  1635
#define IDS_E_BADINSTALL                1636
#define IDC_HARP_END_STATIC1            1636
#define IDC_SERVERS_STATIC              1637
#define IDC_HARP_HP_STATIC1             1637
#define IDS_E_PROBPERSISTS              1638
#define IDC_DEBONDED                    1638
#define IDC_SERVERS_STATIC2             1639
#define IDC_STRAIGHT                    1639
#define IDS_E_INVALIDFORMAT             1640
#define IDC_HARPED                      1640
#define IDC_SPAN_COUNT                  1640
#define IDC_STATION_LOCATION_LABEL      1640
#define IDC_LOCAL_STATIC                1641
#define IDC_LINE_GROUP                  1641
#define IDS_E_FILENOTFOUND              1642
#define IDC_SPAN_LENGTH_BASIS           1642
#define IDC_LOCALS_STATIC2              1643
#define IDS_E_READ                      1644
#define IDC_SERVER_STATIC3              1645
#define IDS_E_FORMAT                    1646
#define IDC_NORTHING                    1647
#define IDC_EASTING                     1649
#define IDC_BOUNDARY_CONDITIONS         1651
#define IDC_BC_GROUP                    1653
#define IDC_GROUP                       1655
#define IDC_PREV_PIER_AHEAD_CONNECTION  1657
#define IDC_PREV_PIER_BACK_CONNECTION   1659
#define IDS_CONFLICT_TOP_IMPORT         1660
#define IDC_NEXT_PIER_BACK_CONNECTION   1661
#define IDS_CONFLICT_TOP_MASTER         1662
#define IDC_END_DISTANCE_LABEL          1662
#define IDC_NEXT_PIER_AHEAD_CONNECTION  1663
#define IDC_BEARING_OFFSET_LABEL        1663
#define IDS_E_LOWRESOURCES              1665
#define IDS_DLG_STATIONFMT_SI           1667
#define IDS_DLG_STATIONFMT_US           1669
#define IDS_DLG_ORIENTATIONFMT          1671
#define IDC_LEFT_SIDEWALK_PLACEMENT     1672
#define IDC_LEFT_BEARING_OFFSET         1672
#define IDS_GRADE250_US                 1673
#define IDC_LEFT_BEARING_OFFSET_T       1673
#define IDS_GRADE1725_US                1674
#define IDC_LEFT_END_DISTANCE           1674
#define IDC_RIGHT_SIDEWALK_PLACEMENT    1675
#define IDC_LEFT_END_DISTANCE_T         1675
#define IDC_LABEL_BEARINGS              1676
#define IDC_LEFT_SUPPORT_WIDTH          1676
#define IDS_GRADE250_SI                 1677
#define IDC_LEFT_SUPPORT_WIDTH_T        1677
#define IDS_GRADE1725_SI                1678
#define IDC_DIAPHRAGM_OFFSET_LABEL      1678
#define IDC_BACK_DIAPHRAGM_OFFSET_LABEL 1678
#define IDC_LEFT_STRUCTURALLY_CONTINUOUS 1679
#define IDC_LEFT_LABEL                  1679
#define IDS_GRADE270_US                 1680
#define IDC_RIGHT_LABEL                 1680
#define IDS_GRADE1860_US                1681
#define IDC_SUPPORT_WIDTH_LABEL         1681
#define IDC_RIGHT_STRUCTURALLY_CONTINUOUS 1682
#define IDC_AHEAD_DIAPHRAGM_OFFSET_LABEL 1682
#define IDC_REF_GIRDER                  1683
#define IDS_GRADE270_SI                 1684
#define IDS_GRADE1860_SI                1685
#define IDC_REF_GIRDER_OFFSET           1686
#define IDS_GDRSEL_EXCEED_MAX_STRAND    1687
#define IDC_REF_GIRDER_OFFSET_UNIT      1688
#define IDS_PSFORCE_EXCEED_MAX          1689
#define IDC_REF_GIRDER_OFFSET_TYPE      1690
#define IDC_PREV_REF_GIRDER             1692
#define IDC_PREV_REF_GIRDER_OFFSET      1694
#define IDS_BROWSER_ERROR               1695
#define IDC_PREV_REF_GIRDER_OFFSET_UNIT 1696
#define IDS_RESULTS_NOT_AVAILABLE       1697
#define IDC_PREV_REF_GIRDER_OFFSET_TYPE 1698
#define IDS_COMPANY                     1699
#define IDC_NEXT_REF_GIRDER             1700
#define IDS_REG_COMPANY                 1701
#define IDC_NEXT_REF_GIRDER_OFFSET      1702
#define IDS_REG_ENGINEER                1703
#define IDC_NEXT_REF_GIRDER_OFFSET_UNIT 1704
#define IDC_NEXT_REF_GIRDER_OFFSET_TYPE 1705
#define IDC_PREV_REF_GIRDER_LABEL       1706
#define IDC_PREV_REF_GIRDER_FROM        1707
#define IDC_NEXT_REF_GIRDER_LABEL       1708
#define IDC_NEXT_REF_GIRDER_FROM        1709
#define IDC_RADIO1                      1710
#define IDC_RADIO_SINGLE                1710
#define IDC_GIRDER_RADIO                1710
#define IDC_LLDF_SINGLE_VALUE           1710
#define IDC_ALPHA                       1711
#define IDC_RADIO_MULTIPLE              1711
#define IDS_PGSUPER_TEMPLATE_FILE_SUFFIX        1712
#define IDC_ADIM_START_LABEL            1714
#define IDC_ADIM_START_UNIT             1716
#define IDS_DEFAULT_MASTER_LIB          1717
#define IDC_ADIM_END_LABEL              1718
#define IDS_CANT_FIND_LIBRARY_FILE      1719
#define IDC_ADIM_END_UNIT               1720
#define IDS_CORRUPTED_LIBRARY_FILE      1721
#define IDC_SLABOFFSET_NOTE             1722
#define IDS_E_EXCESSIVE_SKEW            1723
#define IDC_COPY_SLABOFFSET             1724
#define IDS_E_EXCESSIVE_DELTA_SKEW      1725
#define IDC_SIP_LABEL                   1726
#define IDS_E_PIER_LAYOUT               1727
#define IDS_E_NOCHAPTERS                1728
#define IDC_TO_SPAN                     1729
#define IDC_COMBO4                      1731
#define IDC_TO_GIRDER                   1732
#define IDC_STRENGTH_GRID               1734
#define IDC_LLDF_GIRDERS_TABW           1734
#define IDC_LLDF_PIERS_TABW             1735
#define IDC_FATIGUE_GRID                1736
#define IDC_STRENGTH_LABEL              1738
#define IDS_E_RPTUPDATE                 1739
#define IDS_E_UPDATE                    1740
#define IDC_FATIGUE_LABEL               1741
#define IDS_CONFLICT_BOTTOM_MASTER      1742
#define IDC_LEFT_FC_LABEL               1743
#define IDS_CONFLICT_BOTTOM_IMPORT      1744
#define IDC_LEFT_FC                     1745
#define IDC_LEFT_FC_UNIT                1747
#define IDC_LEFT_MOD_E                  1749
#define IDS_E_INVALIDVERSION            1750
#define IDC_LEFT_EC                     1751
#define IDC_LEFT_EC_UNIT                1753
#define IDC_LEFT_MORE                   1755
#define IDC_TTS_USE                     1756
#define IDC_RIGHT_FC_LABEL              1758
#define IDC_RIGHT_FC                    1759
#define IDC_RIGHT_FC_UNIT               1760
#define IDC_RIGHT_MOD_E                 1761
#define IDC_RIGHT_EC                    1762
#define IDC_RIGHT_EC_UNIT               1763
#define IDC_RIGHT_MORE                  1764
#define IDC_LEFT_DENSITY                1765
#define IDC_LEFT_DENSITY_UNIT           1766
#define IDC_RIGHT_DENSITY               1767
#define IDC_LEFT_DENSITY_UNIT2          1768
#define IDC_RIGHT_DENSITY_UNIT          1769
#define IDC_LEFT_CONCRETE_LABEL         1770
#define IDC_LEFT_CONCRETE_LABEL2        1771
#define IDC_LEFT_RAILING_GROUP          1772
#define IDC_RIGHT_RAILING_GROUP         1773
#define IDC_SLAB_OFFSET_NOTE            1774
#define IDC_START_SLAB_OFFSET_UNIT      1775
#define IDC_END_SLAB_OFFSET             1776
#define IDC_END_SLAB_OFFSET_UNIT        1777
#define IDC_BACK_SLAB_OFFSET_NOTE       1778
#define IDC_AHEAD_SLAB_OFFSET_NOTE      1779
#define IDC_BACK_SLAB_OFFSET            1780
#define IDC_BACK_SLAB_OFFSET_UNIT       1781
#define IDC_AHEAD_SLAB_OFFSET           1782
#define IDC_AHEAD_SLAB_OFFSET_UNIT      1783
#define IDC_BACK_SLAB_OFFSET_LABEL      1784
#define IDC_AHEAD_SLAB_OFFSET_LABEL     1785
#define IDC_NUMGDR_LABEL                1786
#define IDC_START_SLAB_OFFSET_LABEL     1787
#define IDC_END_SLAB_OFFSET_LABEL       1788
#define IDC_NWC_NOTE                    1789
#define IDR_STDTOOLBAR                  12129
#define IDR_LIBTOOLBAR                  12130
#define IDR_HELPTOOLBAR                 12131
#define IDS_BM_VIEW_SETTINGS            12779
#define IDS_GM_VIEW_SETTINGS            12819
#define IDS_ALIGNMENTOFFSET_FMT         12874
#define IDC_EXPAND                      12878
#define IDC_JOIN                        12879
#define IDS_INCOMPATIBLE_BEARING_MSG    13100
#define IDS_INCOMPATIBLE_BEARING_MSG2   13101
#define ID_HELP_JOINARPLIST             33024
#define ID_HELP_INET_ARP                33025
#define ID_HELP_INET_WSDOT              33026
#define ID_HELP_INET_PGSUPER            33027
#define ID_SCREEN_SIZE                  33028
#define FIRST_DATA_IMPORTER_PLUGIN      33033
#define LAST_DATA_IMPORTER_PLUGIN       33053
#define FIRST_DATA_EXPORTER_PLUGIN      33054
#define LAST_DATA_EXPORTER_PLUGIN       33104
#define IDM_ADD_ENTRY                   36864
#define IDM_EDIT_ENTRY                  36865
#define IDM_DELETE_ENTRY                36866
#define IDM_DUPLICATE_ENTRY             36867
#define IDM_LARGE_ICONS                 36868
#define IDM_SMALL_ICONS                 36869
#define IDM_LIST_ICONS                  36870
#define IDM_ARRANGE_ICONS               36871
#define IDM_RENAME_ENTRY                36872
#define IDM_EXPORT_TEMPLATE             36873
#define IDM_EDIT_GIRDER                 36874
#define IDM_COPY_GIRDER_PROPS           36875
#define IDM_IMPORT_PROJECT_LIBRARY      36876
#define IDM_HINGED                      36877
#define IDM_ROLLER                      36878
#define IDM_CONTINUOUS_AFTERDECK        36879
#define IDM_CONTINUOUS_BEFOREDECK       36880
#define IDM_INTEGRAL_AFTERDECK          36881
#define IDM_INTEGRAL_BEFOREDECK         36882
#define IDM_INTEGRAL_AFTERDECK_HINGEBACK 36883
#define IDM_INTEGRAL_BEFOREDECK_HINGEBACK 36884
#define IDM_INTEGRAL_AFTERDECK_HINGEAHEAD 36885
#define IDM_INTEGRAL_BEFOREDECK_HINGEAHEAD 36886
#define ID_UPDATE_TEMPLATE              36887
#define ID_FILE_PROJECT_PROPERTIES      36888
#define ID_EDIT_INSERTROW               36889
#define ID_VIEW_BRIDGEMODELEDITOR       36890
#define ID_VIEW_GIRDEREDITOR            36891
#define ID_EDIT_REMOVEROWS              36892
#define ID_VIEW_ANALYSISMODELEDITOR     36893
#define ID_VIEW_LIBRARYEDITOR           36894
#define ID_VIEW_REPORTS                 36895
#define ID_VIEWSETTINGS_BRIDGEMODELEDITOR 36896
#define ID_VIEWSETTINGS_GIRDEREDITOR    36897
#define ID_VIEWSETTINGS_ANALYSISMODELEDITOR 36898
#define ID_VIEWSETTINGS_LIBRARYEDITOR   36899
#define ID_CONFIGURE_PGSUPER            36900
#define ID_PROJECT_AUTOCALC             36901
#define ID_PROJECT_UPDATENOW            36902
#define ID_PROJECT_DESIGNGIRDER         36903
#define ID_PROJECT_DESIGNGIRDERDIRECT   36904
#define ID_PROJECT_SPEC                 36905
#define ID_VIEW_ANALYSISRESULTS         36906
#define ID_PROJECT_ENVIRONMENT          36907
#define ID_PROJECT_BRIDGEDESC           36908
#define ID_LOADS_LOADMODIFIERS          36909
#define ID_LEFTEND                      36910
#define ID_RIGHTEND                     36911
#define ID_LEFT_HP                      36912
#define ID_CENTER                       36913
#define ID_RIGHT_HP                     36914
#define ID_USER_CUT                     36915
#define ID_EDIT_ROADWAY                 36916
#define ID_EDIT_PIERS                   36917
#define ID_EDIT_BRIDGE                  36918
#define ID_EDIT_SUPERSTRUCTURE          36919
#define ID_VIEWSETTINGS                 36920
#define ID_EDIT_PRESTRESSING            36921
#define ID_EDIT_STIRRUPS                36922
#define ID_VIEW_FACTOROFSAFETY          36926
#define ID_VIEW_STABILITY               36927
#define ID_LOADS_LLDF                   36928
#define ID_ADD_POINT_LOAD               36929
#define ID_EDIT_USERLOADS               36930
#define ID_ADD_DISTRIBUTED_LOAD         36931
#define ID_EDIT_LOAD                    36932
#define ID_DELETE_LOAD                  36933
#define ID_PROJECT_ALIGNMENT            36934
#define ID_EDIT_GIRDER                  36935
#define ID_VIEW_GIRDER                  36936
#define ID_LIVE_LOADS                   36937
#define ID_ADD_MOMENT_LOAD              36938
#define ID_DUMP_LBAM                    36939
#define ID_EDIT_PIER                    36940
#define ID_EDIT_SPAN                    36941
#define ID_PROJECT_SPANDESC             36942
#define ID_PROJECT_PIERDESC             36943
#define ID_DELETE                       36944
#define ID_DELETE_PIER                  36945
#define ID_DELETE_SPAN                  36946
#define ID_INSERT                       36947
#define ID_INSERT_SPAN                  36948
#define ID_INSERT_PIER                  36949
#define ID_EDIT_DECK                    36950
#define ID_OPTIONS_HINTS                36951
#define ID_PROJECT_DESIGNGIRDERDIRECTHOLDSLABOFFSET 36952
#define ID_ZOOM                         36953
#define ID_SCALETOFIT                   36954
#define ID_REPORTS_                     36955
#define ID_OPTIONS_LABELS               36956
#define ID_RATING_SPEC                  36957
#define ID_PROJECT_RATING               36958
#define ID_MANAGE_PLUGINS               36959
#define ID_FILE_IMPORT                  36960
#define ID_PROJECT_ANALYSIS             36961
#define ID_CONSTRUCTION_LOADS           36964
#define ID_FILE_MANAGE                  36965
#define ID_PROJECT_EFFECTIVEFLANGEWIDTH 36966
#define ID_LOADS_LOADFACTORS            36967

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        325
#define _APS_NEXT_COMMAND_VALUE         36968
#define _APS_NEXT_CONTROL_VALUE         1643
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
