//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PGSuperAppPlugin.rc
//
#define ID_INDICATOR_CRITERIA           4
#define ID_INDICATOR_ANALYSIS           5
#define IDS_LWC_MESSAGE                 6
#define IDS_GIRDER_SHEAR                7
#define IDS_LIVE_LOAD_FACTOR_TOOLTIP    8
#define IDS_E_ONLINERESOURCES           9
#define IDS_LIVE_LOAD_FACTOR_DISABLED_TOOLTIP 10
#define IDS_CREATE_NEW_EVENT            11
#define IDS_NWC_MESSAGE                 12
#define EAF_TOOLBAR_MENU_COUNT          40
#define EAF_REPORT_MENU_COUNT           50
#define EAF_GRAPH_MENU_COUNT            50
#define IDR_PGSUPERAPPPLUGIN            101
#define IDR_PGSUPERCOMPONENTINFO        102
#define IDC_CONCRETE_TYPE_LABEL         102
#define IDR_PGSUPERAPPPLUGINIMPL        103
#define IDR_PGSPLICEAPPPLUGINIMPL       104
#define IDR_PGSUPERPROJECTIMPORTERAPPPLUGIN 105
#define IDR_PGSPLICEPROJECTIMPORTERAPPPLUGIN 106
#define IDD_CLOSURE_CONNECTION          107
#define IDR_PGSPLICECOMPONENTINFO       110
#define IDD_SELECTBOUNDARYCONDITION     113
#define IDR_PGSUPER                     130
#define IDD_PROJECTPROPERTIES           131
#define IDR_BRIDGEMODELEDITOR           132
#define IDR_PGSUPERPROJECTIMPORTER      133
#define IDR_PGSPLICEPROJECTIMPORTER     134
#define IDR_GIRDERMODELEDITOR           135
#define IDR_ANALYSISMODELEDITOR         136
#define IDR_LIBRARYEDITOR               137
#define IDR_ANALYSISRESULTS             138
#define IDR_GRAPHING                    139
#define IDD_ENVIRONMENT                 139
#define IDR_REPORT                      140
#define IDR_PGSPLICE                    141
#define IDD_BRIDGEDESC_GENERAL          141
#define IDR_FACTOROFSAFETY              144
#define IDR_ADD_DELETE_POPUP            147
#define IDD_GIRDERDESC_PRESTRESS        152
#define IDD_SPECIFICATION               153
#define IDD_BRIDGE_EDITOR_PLAN_PAGE     157
#define IDD_BRIDGE_EDITOR_SECTION_PAGE  158
#define IDD_BRIDGE_EDITOR_ALIGNMENT_PAGE 159
#define IDD_GIRDER_EDITOR_SECTION_PAGE  160
#define IDD_GIRDER_EDITOR_ELEVATION_PAGE 161
#define IDR_ALIGNMENT_PLAN_CTX          162
#define IDR_BRIDGE_PLAN_CTX             163
#define IDB_IN_USE                      164
#define IDB_IN_USE_AND_READ_ONLY        165
#define IDB_READ_ONLY                   166
#define IDR_BRIDGE_XSECTION_CTX         167
#define IDR_GIRDER_CTX                  168
#define IDR_ALIGNMENT_PROFILE_CTX       169
#define IDD_DESIGN_GIRDER               170
#define IDD_GIRDERDESC_LIFTING_PAGE     174
#define IDD_COPY_GIRDER_PROPERTIES      179
#define IDD_GIRDER_EDITOR_BAR           180
#define IDD_SECTION_CUT_DIALOG          182
#define IDD_SECTION_CUT_DIALOG_EX       188
#define IDI_WSDOT                       190
#define IDI_BSS                         191
#define IDD_DESIGN_OUTCOME              194
#define IDD_STABILITY_BAR               195
#define IDD_LLDF                        196
#define IDD_BRIDGEDESC_ENVIRONMENTAL    197
#define IDI_DEFAULT_ENTRY               198
#define IDI_FOLDER                      199
#define IDI_OPEN_FOLDER                 200
#define IDI_LIBRARY_MANAGER             201
#define IDI_WARNING2                    203
#define IDD_SELECT_LIVE_LOAD            204
#define IDD_EDIT_POINTLOAD              206
#define IDD_EDIT_DISTRIBUTEDLOAD        207
#define IDD_EDIT_LOADS                  208
#define IDD_TIMELINE_REPORT             209
#define IDR_EDITLOADS                   210
#define IDI_EDIT_LOADS                  211
#define IDR_LOADS_CTX                   212
#define IDI_POINT_LOAD                  214
#define IDI_DISTRIBUTED_LOAD            215
#define IDD_GIRDERDESC_DEBOND           226
#define IDD_ALIGNMENT_HORIZONTAL        227
#define IDD_PROFILE_PAGE                228
#define IDD_SUPERELEVATIONS             229
#define IDD_SPAN_LENGTHS                230
#define IDR_SELECTED_GIRDER_CONTEXT     231
#define IDR_SELECTED_GIRDER_SEGMENT_CONTEXT 232
#define IDD_STATION_CUT_DIALOG          232
#define IDR_SELECTED_DECK_CONTEXT       233
#define IDR_SELECTED_GIRDERLINE_CONTEXT 234
#define IDD_SELECT_GIRDER               234
#define IDD_GIRDERDESC_GENERAL          237
#define IDD_BRIDGEDESC_DECKREINFORCEMENT 238
#define IDI_TXDOT                       239
#define IDC_FILLET_UNITS                240
#define IDC_ASSUMED_EXCESS_CAMBER_UNITS 240
#define IDD_GIRDERDESC_LONGITUDINAL_REBAR 241
#define IDD_BRIDGEDESC_DECKDETAILS      245
#define IDI_MOMENT_LOAD                 246
#define IDD_EDIT_MOMENTLOAD             250
#define IDD_MOVEPIER                    258
#define IDD_STRUCTURAL_ANALYSIS_METHOD  260
#define IDR_SELECTED_PIER_CONTEXT       262
#define IDR_SELECTED_SPAN_CONTEXT       263
#define IDD_GIRDERLAYOUT                264
#define IDR_GIRDER_GRID_CONTEXT         265
#define IDD_SPANLAYOUT                  269
#define IDD_PIER_LOCATION               270
#define IDD_PIERCONNECTIONS             271
#define IDD_GIRDERSPACING               272
#define IDD_ABUTMENTCONNECTIONS         273
#define IDR_FRAMING_GRID_CONTEXT        275
#define IDD_BRIDGEDESC_RAILINGSYSTEM    276
#define IDD_SELECT_ITEM                 277
#define IDD_BRIDGEDESC_FRAMING          279
#define IDD_BRIDGE_EDITOR_PROFILE_PAGE  280
#define IDD_RESOLVE_GIRDER_SPACING      281
#define IDC_COLUMN_GRID                 287
#define IDC_ADD_COLUMN                  288
#define IDC_REMOVE_COLUMN               289
#define IDR_REPORTS                     293
#define IDR_GRAPHS                      294
#define IDD_GIRDERLABELFORMAT           294
#define IDD_RATING_OPTIONS              299
#define IDD_DESIGN_RATING               300
#define IDD_LEGAL_RATING                302
#define IDD_PERMIT_RATING               303
#define IDD_MANAGE_PLUGINS              307
#define IDD_CONSTRUCTION_LOADS          308
#define IDB_GIRDERDESIGNER              309
#define IDI_KDOT                        310
#define IDI_EDIT_BRIDGE                 311
#define IDR_NEWLOADS                    312
#define IDI_EDIT_GIRDER                 313
#define IDR_FRAMING_GRID2_CONTEXT       313
#define IDI_LIVELOAD                    314
#define IDI_RF                          315
#define IDI_COPY_PROPERTIES             316
#define IDD_MULTI_GIRDER_SELECT         317
#define IDR_COPY_PASTE                  318
#define IDD_SPLICEDGIRDER               318
#define IDD_LINEAR_DUCT                 319
#define IDD_PARABOLIC_DUCT              320
#define IDD_OFFSET_DUCT                 321
#define IDD_LLDF_FILL                   322
#define IDD_BRIDGEVIEW_CONTROLS         323
#define IDD_TS_GENERAL                  324
#define IDD_CLOSURE_GENERAL             325
#define IDD_CLOSURE_LONGITUDINAL        326
#define IDD_SELECT_GIRDERSEGMENT        329
#define IDR_SELECTED_TEMPORARY_SUPPORT_CONTEXT 330
#define IDD_SEGMENT_GENERAL             331
#define IDD_SEGMENT_LONGITUDINAL_REBAR  332
#define IDD_SEGMENT_STRANDS             336
#define IDD_SEGMENT_TENDONS             337
#define IDD_SEGMENT_SPACING             338
#define IDD_TIMELINE_MANAGER            339
#define IDD_TIMELINE_EVENT              340
#define IDR_ACTIVITIES                  341
#define IDD_ERECT_PIERS                 342
#define IDD_REMOVE_TS                   343
#define IDD_CAST_CLOSURE_JOINT          345
#define IDD_APPLYLOADS                  346
#define IDD_CONSTRUCT_SEGMENT           347
#define IDD_STRESS_TENDON               348
#define IDD_ERECT_SEGMENTS              349
#define IDD_INSERT_SPAN                 350
#define IDR_EDIT_GIRDER                 352
#define IDD_SELECT_CLOSURE_JOINT        353
#define IDD_LOAD_FACTORS                356
#define IDD_CAST_DECK                   357
#define IDD_POSTTENSION_PARAMETERS      359
#define IDD_PRETENSION_PARAMETERS       360
#define IDD_TIMESTEP_PARAMETERS         363
#define IDD_EDIT_HAUNCH                 367
#define IDD_HAUNCH_BY_BRIDGE            369
#define IDD_HAUNCH_BY_BEARING           370
#define IDD_HAUNCH_BY_SEGMENT           371
#define IDD_EDIT_BEARINGS               375
#define IDD_BEARINGSAME4_BRIDGE         377
#define IDD_CAST_LONGITUDINAL_JOINTS    379
#define IDD_BEARING_GDR_BY_GDR          382
#define IDD_BRIDGEDESC_BEARING          384
#define IDD_EDIT_BRNG_GENERIC_PAGE      387
#define IDD_PIER_BEARINGS_PAGE          387
#define IDD_GIRDER_SELECT_STRANDS       390
#define IDD_SELECT_BOUNDARY_CONDITION   392
#define IDI_ICON1                       395
#define IDI_RW_CS                       395
#define IDD_FILESAVEWARNINGDLG          401
#define IDD_GEOMETRY_CONTROL            408
#define IDR_PGSUPER_TEMPLATE_ICON       500
#define IDR_PGSPLICE_TEMPLATE_ICON      501
#define IDD_ABOUTBOX                    999
#define IDC_BRIDGE                      1000
#define IDC_ALIGNMENT                   1001
#define IDD_FILLETSAME4_BRIDGE          1001
#define IDD_ASSUMED_EXCESS_CAMBER_BRIDGE 1001
#define IDC_VERSION                     1002
#define IDC_BRIDGEID                    1002
#define IDD_ASSUMED_EXCESS_CAMBER_SPAN  1002
#define IDC_COPYRIGHT                   1003
#define IDD_ASSUMED_EXCESS_CAMBER_GIRDER 1003
#define IDD_ASSUMED_EXCESS_CAMBER_SEGMENT 1003
#define IDC_JOBNUMBER                   1004
#define IDD_BEARING_PIER_BY_PIER        1004
#define IDC_APPICON                     1005
#define IDC_END_DISTANCE                1005
#define IDD_COPY_GIRDER_PROPERTIES2     1005
#define IDC_ENGINEER                    1006
#define IDC_BEARING_OFFSET              1006
#define IDC_COMPANY                     1007
#define IDC_RIGHT_BEARING_OFFSET        1007
#define IDC_RIGHT_END_DISTANCE          1008
#define IDC_DESCRIPTION                 1009
#define IDC_FC                          1009
#define IDC_COMMENTS                    1010
#define IDC_MOREINFO                    1013
#define IDC_MILD_STEEL_SELECTOR         1013
#define IDC_RADIO2                      1015
#define IDC_DIAPHRAGM_OFFSET            1017
#define IDC_BEFORE_XFER                 1017
#define IDC_BACK_DIAPHRAGM_OFFSET       1017
#define IDC_VALUE                       1018
#define IDC_SERVICE_IA_DW               1018
#define IDC_AFTER_XFER                  1018
#define IDC_AHEAD_DIAPHRAGM_OFFSET      1018
#define IDC_TENSION_MAX                 1019
#define IDC_STRENGTH_I_DW_MIN           1020
#define IDC_STRENGTH_I_DW_MAX           1021
#define IDC_STRENGTH_II_DW_MIN          1022
#define IDC_STRENGTH_II_DW_MAX          1023
#define IDC_NUMERIC                     1024
#define IDC_FATIGUE_I_DW                1024
#define IDC_DIAPHRAGM_HEIGHT            1024
#define IDC_BACK_DIAPHRAGM_HEIGHT       1024
#define IDC_LIST                        1025
#define IDC_DIAPHRAGM_WIDTH             1025
#define IDC_BACK_DIAPHRAGM_WIDTH        1025
#define IDC_VALUE_UNITS                 1026
#define IDC_AHEAD_DIAPHRAGM_HEIGHT      1026
#define IDC_EXPOSURE                    1027
#define IDC_BEARING_OFFSET_T            1027
#define IDC_AHEAD_DIAPHRAGM_WIDTH       1027
#define IDC_RELHUMIDITY                 1028
#define IDC_DIAPHRAGM_HEIGHT_T          1028
#define IDC_BACK_DIAPHRAGM_HEIGHT_T     1028
#define IDC_INSERTROW                   1029
#define IDC_DIAPHRAGM_WIDTH_T           1029
#define IDC_BACK_DIAPHRAGM_WIDTH_T      1029
#define IDC_END_DISTANCE_T              1030
#define IDC_AHEAD_DIAPHRAGM_HEIGHT_T    1030
#define IDC_REMOVEROWS                  1031
#define IDC_RIGHT_BEARING_OFFSET_T      1031
#define IDC_DIRECTION                   1032
#define IDC_RIGHT_END_DISTANCE_T        1032
#define IDC_AHEAD_DIAPHRAGM_WIDTH_T     1033
#define IDC_RESTORE_DEFAULTS            1034
#define IDC_APPEND_ROW                  1035
#define IDC_STATIONFMT                  1037
#define IDC_LONG_GRID                   1038
#define IDC_ORIENTATIONFMT              1043
#define IDC_FC_UNIT                     1046
#define IDC_NUMGDR                      1051
#define IDC_NUMGDR_SPIN                 1053
#define IDC_GDR_TYPE                    1054
#define IDC_NUMGDR_NEXT_SPAN            1056
#define IDC_NUMGDR_SPIN_NEXT_SPAN       1060
#define IDC_GROSS_DEPTH                 1061
#define IDC_SLAB_OFFSET                 1064
#define IDC_SLAB_FC                     1066
#define IDC_OLAY_DENSITY_LABEL          1068
#define IDC_OLAY_DENSITY                1069
#define IDC_SACDEPTH                    1070
#define IDC_OLAY_DENSITY_UNIT           1072
#define IDC_SACDEPTH_UNIT               1073
#define IDC_SLAB_OFFSET_UNIT            1074
#define IDC_GROSS_DEPTH_UNIT            1079
#define IDC_SLAB_FC_UNIT                1080
#define IDC_SPAN                        1083
#define IDC_OLAY_WEIGHT_LABEL           1085
#define IDC_GIRDER                      1086
#define IDC_OLAY_DEPTH_LABEL            1088
#define IDC_LOAD_CASE                   1090
#define IDC_SHOW_PS_CG                  1092
#define IDC_ACTION                      1093
#define IDC_OLAY_WEIGHT                 1095
#define IDC_EVENT                       1096
#define IDC_OLAY_WEIGHT_UNIT            1098
#define IDC_FCI                         1099
#define IDC_OLAY_DEPTH                  1101
#define IDC_CHECK_TENSION_MAX           1101
#define IDC_FCI_UNIT                    1102
#define IDC_OLAY_DEPTH_UNIT             1102
#define IDC_RELEASE_TENSION_MAX_UNIT    1102
#define IDC_TENSION_MAX_UNIT            1102
#define IDD_PIER_LAYOUT                 1112
#define IDC_FINAL                       1112
#define IDC_TEMP_STRAND_SIZE            1113
#define IDC_BEFORE_TEMP_STRAND_REMOVAL  1113
#define IDD_COPY_PIER_PROPERTIES        1113
#define IDC_BEFORE_XFER_TAG             1114
#define IDD_COPY_PIER_PROPERTIES1       1114
#define IDD_EDIT_HAUNCH_ACAMBER         1114
#define IDC_SHIPPING                    1115
#define IDD_EDIT_HAUNCH_BY_HAUNCH       1115
#define IDC_HPOFFSET_END                1116
#define IDC_SHIPPING_TAG                1116
#define IDC_FINAL_TAG                   1117
#define IDC_HPOFFSET_START              1117
#define IDC_HPOFFSET_END_UNIT           1118
#define IDC_LIFTING                     1118
#define IDC_AFTER_XFER_TAG              1119
#define IDC_HPOFFSET_HP1                1119
#define IDC_LIFTING_TAG                 1120
#define IDC_HPOFFSET_HP1_UNIT           1120
#define IDC_NUM_SS                      1121
#define IDC_BEFORE_TEMP_STRAND_REMOVAL_TAG 1121
#define IDC_NUM_SS_SPIN                 1122
#define IDC_AFTER_TEMP_STRAND_REMOVAL   1122
#define IDC_NUM_HS                      1123
#define IDC_AFTER_TEMP_STRAND_REMOVAL_TAG 1123
#define IDC_NUM_HS_SPIN                 1124
#define IDC_AFTER_DECK_PLACEMENT        1124
#define IDC_SS_JACK                     1125
#define IDC_AFTER_DECK_PLACEMENT_TAG    1125
#define IDC_SS_JACK_FORCE               1126
#define IDC_AFTER_SIDL                  1126
#define IDC_HS_JACK                     1127
#define IDC_AFTER_SIDL_TAG              1127
#define IDC_HS_JACK_FORCE               1128
#define IDC_SS_JACK_FORCE_UNIT          1129
#define IDC_HS_JACK_FORCE_UNIT          1130
#define IDC_TS_JACK_FORCE               1131
#define IDC_HPOFFSET_START_UNIT         1131
#define IDC_SPEC                        1132
#define IDC_TS_JACK_FORCE_UNIT          1132
#define IDC_HPOFFSET_HP2                1132
#define IDC_NUM_TEMP                    1133
#define IDC_HPOFFSET_HP2_UNIT           1134
#define IDC_SPACING                     1135
#define IDC_NUM_TEMP_SPIN               1136
#define IDC_SPACING2                    1136
#define IDC_HARP_POINT_LOCATION         1136
#define IDC_SPACING_UNIT                1137
#define IDC_TEMP_JACK                   1138
#define IDC_TEMP_JACK_FORCE             1140
#define IDC_TEMP_JACK_FORCE_UNIT        1143
#define IDC_LABEL_PIERS                 1146
#define IDC_DIAPHRAGM_OFFSET_UNITS      1147
#define IDC_BACK_DIAPHRAGM_OFFSET_UNITS 1147
#define IDC_LABEL_GIRDERS               1148
#define IDC_CONNECTION_MF               1148
#define IDC_AHEAD_DIAPHRAGM_OFFSET_UNITS 1149
#define IDC_SHOW_DIMENSIONS             1151
#define IDC_SHOW_DIMENSIONS2            1152
#define IDC_SHOW_PROPERTIES             1152
#define IDC_SHOW_RW_CROSSSECTION        1152
#define IDC_SHOW_SCHEMATIC              1155
#define IDC_SHOW_STRANDS                1157
#define IDC_SHOW_LONG_REINF             1158
#define IDC_SHOW_SHOW_LONG_REINF        1159
#define IDC_SECTION_CUT                 1161
#define IDC_GRID                        1162
#define IDC_SELECT_GIRDERS              1163
#define IDC_LLDF_FILL2                  1163
#define IDC_SELECT_ALL                  1163
#define IDC_EDIT_STRAND_FILL            1163
#define IDC_ADD_TEMP_SUPPORT            1163
#define IDC_MORE_PROPERTIES             1163
#define IDC_COPY                        1163
#define IDC_MOVE_RIGHT                  1163
#define IDC_COPY_TO_END                 1163
#define IDC_EDIT_HAUNCH_BUTTON          1163
#define IDC_PRINT                       1164
#define IDC_CLEAR_ALL                   1164
#define IDC_REMOVE_TEMP_SUPPORT         1164
#define IDC_COPY_TO_START               1164
#define IDC_EDIT_HAUNCH_BUTTON2         1164
#define IDC_EDIT_LOAD                   1167
#define IDC_ADD                         1169
#define IDC_BEFORE_XFER_LABEL           1169
#define IDC_ADD_PIER                    1170
#define IDC_AFTER_XFER_LABEL            1170
#define IDC_RESTORE_DEFAULTS1           1171
#define IDC_SHIPPING_LABEL              1171
#define IDC_BACK_COPY                   1172
#define IDC_FINAL_LABEL                 1172
#define IDC_AHEAD_COPY                  1174
#define IDC_LIFTING_LABEL               1174
#define IDC_BEFORE_TEMP_STRAND_REMOVAL_LABEL 1175
#define IDC_AFTER_TEMP_STRAND_REMOVAL_LABEL 1176
#define IDC_BROWSER                     1177
#define IDC_AFTER_DECK_PLACEMENT_LABEL  1177
#define IDC_AFTER_SIDL_LABEL            1178
#define IDC_DESIGN_FLEXURE              1187
#define IDC_DESIGN_SHEAR                1189
#define IDC_SS_TITLE                    1190
#define IDC_USER_CUT                    1191
#define IDC_HS_TITLE                    1192
#define IDC_DESIGN_HAUNCH               1193
#define IDC_TEMP_TITLE                  1194
#define IDC_DESIGN_CONCRETE             1194
#define IDC_DESIGN_CONCRETE_STRENGTH    1194
#define IDC_HPOFFSET_END_TITLE          1195
#define IDC_HPOFFSET_END_NOTE           1196
#define IDC_HPOFFSET_HP_TITLE           1197
#define IDC_HPOFFSET_HP_NOTE            1198
#define IDC_LIFTING_LOOP_LOCATION       1199
#define IDC_STORAGE_LOCATION            1200
#define IDC_TRAILINGOVERHANG            1201
#define IDC_LIFTING_LOOP_LOCATION_UNITS 1202
#define IDC_STORAGE_LOCATION_UNITS      1203
#define IDC_TRAILINGOVERHANG_UNITS      1204
#define IDC_RELEASE_LOCATION            1205
#define IDC_LEADINGOVERHANG             1206
#define IDC_RELEASE_LOCATION_UNITS      1207
#define IDC_LEADINGOVERHANG_UNITS       1208
#define IDC_GRADE                       1213
#define IDC_LENGTH                      1221
#define IDC_FILLET                      1240
#define IDC_FILLET_UNIT                 1242
#define IDC_BEARING_OFFSET_MEASURE      1245
#define IDC_END_DISTANCE_MEASURE        1246
#define IDC_STATION                     1250
#define IDC_ELEVATION                   1252
#define IDC_STRENGTH_I_DC               1259
#define IDC_FY_COEFFICIENT              1259
#define IDC_LOAD                        1259
#define IDC_START_GROUP_EDIT            1259
#define IDC_LEFT_PRISMATIC_LENGTH       1259
#define IDC_RELAXATION_TIME             1259
#define IDC_ANCHORSET_PT                1259
#define IDC_ADJUSTMENT                  1259
#define IDC_START_CANTILEVER_LENGTH     1259
#define IDC_HEIGHT                      1259
#define IDC_CURING                      1259
#define IDC_CONDITION_FACTOR            1260
#define IDC_LOCATION                    1260
#define IDC_SERVICE_III_DC              1260
#define IDC_LEFT_TAPERED_LENGTH         1260
#define IDC_ANCHORSET_TTS               1260
#define IDC_END_CANTILEVER_LENGTH       1260
#define IDC_RIGHT_TAPERED_LENGTH        1261
#define IDC_STRENGTH_I_CR               1261
#define IDC_TOP_COVER                   1262
#define IDC_RIGHT_PRISMATIC_LENGTH      1262
#define IDC_SUPERSTRUCTURE_DESCRIPTION  1264
#define IDC_DESIGN_TRUCK_IMPACT         1266
#define IDC_SPAN_LENGTH                 1267
#define IDC_ORIENTATION                 1268
#define IDC_LEFT_SIDEWALK_LEFT_DEPTH    1269
#define IDC_REFSTATION                  1271
#define IDC_START_SLAB_OFFSET           1273
#define IDC_TOP_COVER_UNIT              1274
#define IDC_END_SLAB_OFFSET             1274
#define IDC_MAGNITUDE                   1275
#define IDC_RIGHT_MAGNITUDE             1277
#define IDC_RIGHT_SIDEWALK_LEFT_DEPTH   1278
#define IDC_FATIGUE_TRUCK_IMPACT        1281
#define IDC_PERMIT_TRUCK_IMPACT         1282
#define IDC_BOTTOM_COVER                1283
#define IDC_PERMIT_TRUCK_IMPACT2        1283
#define IDC_RIGHT_LOCATION              1286
#define IDC_BOTTOM_COVER_UNIT           1287
#define IDC_LEFT_MAGNITUDE              1290
#define IDC_TOP_MAT_BAR_SPACING         1291
#define IDC_TOP_MAT_BAR_SPACING_UNIT    1293
#define IDC_TOP_MAT_LUMP_SUM            1294
#define IDC_TOP_MAT_LUMP_SUM_UNIT       1296
#define IDC_BOTTOM_MAT_BAR_SPACING      1298
#define IDC_BOTTOM_MAT_BAR_SPACING_UNIT 1300
#define IDC_BOTTOM_MAT_LUMP_SUM         1303
#define IDC_BOTTOM_MAT_LUMP_SUM_UNIT    1306
#define IDC_ALIGNMENTOFFSET             1308
#define IDC_DECK                        1309
#define IDC_ERECTION_LABEL              1313
#define IDC_END_BLOCK_LENGTH_LABEL      1313
#define IDC_EVENT_NOTE                  1313
#define IDC_LEFT_DENSITY_LABEL          1314
#define IDC_RIGHT_DENSITY_LABEL         1316
#define IDC_STATIC_TEXT                 1317
#define IDC_GROSS_DEPTH_LABEL           1321
#define IDC_PANEL_DEPTH                 1322
#define IDC_PANEL_DEPTH_UNIT            1323
#define IDC_PANEL_SUPPORT               1324
#define IDC_PANEL_SUPPORT_UNIT          1325
#define IDC_LLDF_COMPUTE                1327
#define IDC_LLDF_LEVER_RULE             1328
#define IDC_LLDF_INPUT                  1329
#define IDC_SERVICE_I_LLIM              1341
#define IDC_DESIGN_LL_LIST              1343
#define IDC_SERVICE_IA_DC               1343
#define IDC_SPANS                       1344
#define IDC_SERVICE_IA_LLIM             1344
#define IDC_GIRDERS                     1346
#define IDC_SERVICE_III_LLIM            1346
#define IDC_FATIGUE_LL_LIST             1347
#define IDC_STRENGTH_I_DC_MIN           1347
#define IDC_STRENGTH_LL_LIST            1348
#define IDC_STRENGTH_I_LLIM             1348
#define IDC_STRENGTH_I_DC_MAX           1349
#define IDC_STRENGTH_II_DC_MIN          1350
#define IDC_LOCATION_UNITS              1351
#define IDC_STRENGTH_II_DC_MAX          1351
#define IDC_FRACTIONAL                  1352
#define IDC_STRENGTH_II_LLIM            1352
#define IDC_MAGNITUDE_UNITS             1353
#define IDC_FATIGUE_I_DC                1353
#define IDC_LOADCASE                    1354
#define IDC_FATIGUE_I_LLIM              1354
#define IDC_TEMPORARY                   1356
#define IDC_MAGNITUDE_UNITS2            1357
#define IDC_LOADTYPE                    1358
#define IDC_LOADS_LIST                  1359
#define IDC_ANALYSIS                    1360
#define IDC_DELETE_LOAD                 1361
#define IDC_ADD_POINTLOAD               1362
#define IDC_ADD_NEW_DISTRIBUTED         1363
#define IDC_LEFT_LOCATION               1364
#define IDC_LEFT_ENDSTATIC              1365
#define IDC_RIGHT_END_STATIC            1366
#define IDC_LOCATION_STATIC             1367
#define IDC_WOBBLE_PT_TAG               1370
#define IDC_SPAN_LENGTH_CTRL            1371
#define IDC_ANCHORSET_PT_TAG            1371
#define IDC_LOAD_STATIC                 1372
#define IDC_ANCHORSET_TTS_TAG           1372
#define IDC_SELEVENT                    1373
#define IDC_WOBBLE_TTS_TAG              1373
#define IDC_LOADS                       1374
#define IDC_POINT_LOAD_DRAG             1375
#define IDC_GIRDER_FC                   1376
#define IDC_DISTRIBUTED_LOAD_DRAG       1377
#define IDC_GIRDER_FC_UNIT              1378
#define IDC_MOMENT_LOAD_DRAG            1379
#define IDC_SHOW_LEGEND                 1387
#define IDC_HAULINGOVERHANGS            1388
#define IDC_SHOW_SECTION_CG             1388
#define IDC_GIRDERLENGTH                1389
#define IDC_GIRDERLENGTH_UNIT           1390
#define IDC_SUPPORT_WIDTH               1394
#define IDC_SUPPORT_WIDTH_T             1395
#define IDC_RIGHT_SUPPORT_WIDTH         1396
#define IDC_RIGHT_SUPPORT_WIDTH_T       1397
#define IDC_ASSUMED_EXCESS_CAMBER_LABEL 1397
#define IDC_PANEL_DEPTH_LABEL           1398
#define IDC_PANEL_SUPPORT_LABEL         1399
#define IDC_SLAB_OFFSET_LABEL           1400
#define IDC_SLAB_FC_LABEL               1401
#define IDC_SLAB_FC_LABEL2              1402
#define IDC_FILLET_LABEL                1403
#define IDC_SACDEPTH_LABEL              1405
#define IDC_RATING_CRITERIA             1407
#define IDC_PERMIT_TYPE                 1407
#define IDC_CONDITION_FACTOR_TYPE       1407
#define IDC_GIRDER_SPAN                 1407
#define IDC_DESIGN_PEDES_COMBO          1407
#define IDC_COMBO_VIEWLOC               1407
#define IDC_REFERENCE_DUCT              1407
#define IDC_VARIATION_TYPE              1407
#define IDC_TS_TYPE                     1407
#define IDC_CONNECTION_TYPE             1407
#define IDC_DIAPHRAGM_LOAD              1407
#define IDC_SUPPORTS                    1407
#define IDC_BACK_DIAPHRAGM_LOAD         1407
#define IDC_ADJUSTABLE_COMBO            1407
#define IDC_PIER_MODEL_TYPE             1407
#define IDC_HAUNCH_SHAPE                1407
#define IDC_DESIGNA_FROM                1407
#define IDC_CB_NUMGDRS                  1407
#define IDC_FILLET_COMBO                1407
#define IDC_NGDRS_COMBO                 1407
#define IDC_HAUL_TRUCKS                 1407
#define IDC_GIRDER_ORIENTATION          1408
#define IDC_GIRDER_GIRDER               1408
#define IDC_AHEAD_DIAPHRAGM_LOAD        1408
#define IDC_HAUNCH_SHAPE2               1408
#define IDC_DESIGNA_TO                  1408
#define IDC_CB_SPACG_TYPE               1408
#define IDC_GDR_NAME_COMBO              1408
#define IDC_PIER                        1409
#define IDC_FATIGUE_PEDES_COMBO         1409
#define IDC_FILLET_TYPE                 1409
#define IDC_GDR_SPC_TYPE_COMBO          1409
#define IDC_ASSUMED_EXCESS_CAMBER_TYPE  1409
#define IDC_BY_SEG_SPAN                 1409
#define IDC_HP_COMBO_END                1410
#define IDC_PIER_GIRDER                 1410
#define IDC_PERMIT_PEDES_COMBO          1410
#define IDC_TOP_MAT_BAR                 1411
#define IDC_OVERHANG_TAPER              1413
#define IDC_GIRDER_END                  1414
#define IDC_RESIZEOPTIONS               1415
#define IDC_GIRDER_NAME                 1416
#define IDC_GIRDER_NAMEUSE              1417
#define IDC_MOVE_PIER                   1418
#define IDC_ASSUMED_EXCESS_CAMBER_TYPES 1418
#define IDC_SLAB_OFFSET_TYPE            1419
#define IDC_PREV_SPAN_SPACING_MEASUREMENT 1420
#define IDC_ROA_CB                      1421
#define IDC_FROM_SPAN                   1422
#define IDC_CONSTRUCTION_EVENT          1423
#define IDC_DECK_EVENT                  1423
#define IDC_HARP_END_CB                 1423
#define IDC_DUCT_TYPE                   1423
#define IDC_REFCOLUMN_MEASUREMENT       1423
#define IDC_LOAD_RATING_EVENT           1423
#define IDC_ERECTION_EVENT              1424
#define IDC_HP_COMBO_HP                 1424
#define IDC_HARP_HP_CB                  1424
#define IDC_CB_SAMEGIRDER               1424
#define IDC_BOTTOM_MAT_BAR              1425
#define IDC_DUCT_TYPE2                  1425
#define IDC_GIRDER_SPACING_MEASURE      1427
#define IDC_WEARINGSURFACETYPE          1428
#define IDC_NEXT_SPAN_SPACING_MEASUREMENT 1433
#define IDC_MEASUREMENT_DATUM           1434
#define IDC_FROM_GIRDER                 1435
#define IDC_RIGHT_CONCRETE_LABEL        1436
#define IDC_DEBOND_GRID                 1443
#define IDC_DELETE                      1444
#define IDC_PICTURE                     1445
#define IDC_RATE_FOR_SHEAR              1446
#define IDC_DESIGN                      1446
#define IDC_CHECK_SYMM                  1446
#define IDC_START_WITH_LAYOUT           1446
#define IDC_USER_ECI                    1446
#define IDC_RAILING_SYSTEM              1446
#define IDC_NEW_GROUP                   1446
#define IDC_USE_LUMPSUM                 1446
#define IDC_BOTTOM_FLANGE_DEPTH         1446
#define IDC_START_CANTILEVER            1446
#define IDC_DRAW_BRIDGE                 1446
#define IDC_EPOXY                       1446
#define IDC_CHECK_ADESIGN               1446
#define IDC_SYMMETRIC_DEBOND            1447
#define IDC_END_CANTILEVER              1447
#define IDC_MOD_ECI                     1449
#define IDC_SHOW_DIALOG                 1453
#define IDC_NORTH_UP                    1456
#define IDC_SHOW_TRANSV_REINF           1457
#define IDC_SYNC                        1458
#define IDC_SAME_NUM_GIRDERLINES        1461
#define IDC_RIGHT_SIDEWALK              1463
#define IDC_SPACING_LABEL               1467
#define IDC_FILLETTYPE                  1467
#define IDC_ALIGNMENTOFFSET_UNIT        1468
#define IDC_ALIGNMENTOFFSET_FMT         1469
#define IDC_HCURVE_GRID                 1470
#define IDC_REMOVE                      1471
#define IDC_SORT                        1472
#define IDC_VCURVE_GRID                 1473
#define IDC_ELEVATION_UNIT              1474
#define IDC_PIER_GRID                   1475
#define IDC_REMOVE_PIER                 1476
#define IDC_LAYOUT                      1477
#define IDC_SIMPLE                      1478
#define IDC_SIMPLE2                     1479
#define IDC_SIMPLE3                     1480
#define IDC_STATION_RANGE               1481
#define IDC_MOD_E                       1482
#define IDC_EC                          1483
#define IDC_EC_UNIT                     1484
#define IDC_ECI                         1485
#define IDC_ECI_UNIT                    1486
#define IDC_MOD_EC                      1487
#define IDC_STRAND_INPUT_TYPE           1488
#define IDC_HARP_STRAIGHT               1489
#define IDC_STATIC_LLE                  1491
#define IDC_STATIC_SL                   1492
#define IDC_STATIC_TLSO                 1493
#define IDC_STATIC_SLLO                 1494
#define IDC_STATICSLGL                  1495
#define IDC_STATIC_LL2                  1496
#define IDC_STATIC_LLE2                 1497
#define IDC_STATIC_LLE3                 1498
#define IDC_DECK_TYPE                   1509
#define IDC_OVERHANG_DEPTH              1510
#define IDC_RIGHT_OVERHANG_DEPTH        1510
#define IDC_OVERHANG_DEPTH_UNIT         1511
#define IDC_LEFT_OVERHANG_DEPTH         1512
#define IDC_OVERHANG_DEPTH_LABEL        1513
#define IDC_ADD_MOMENTLOAD              1514
#define IDC_ALLOWABLE_SPACING           1515
#define IDC_GIRDER_CONNECTIVITY_S       1516
#define IDC_GIRDER_CONNECTIVITY         1517
#define IDC_DESIGN_LANE_IMPACT          1520
#define IDC_BEAM_FAMILIES               1521
#define IDC_FATIGUE_LANE_IMPACT         1522
#define IDC_PERMIT_LANE_IMPACT          1523
#define IDC_NUMSTRAIGHT                 1524
#define IDC_PERMIT_LANE_IMPACT2         1524
#define IDC_NUM_DEBONDED                1525
#define IDC_MORE                        1527
#define IDC_EXTENDED_LEFT               1527
#define IDC_NUM_EXTENDED_LEFT           1527
#define IDC_GIRDERGRID                  1528
#define IDC_EXTENDED_RIGHT              1528
#define IDC_NUM_EXTENDED_RIGHT          1528
#define IDC_PREV_SPAN_SPACING_LABEL     1529
#define IDC_NEXT_SPAN_SPACING_LABEL     1530
#define IDC_PREV_PIER_SPACING_GRID      1531
#define IDC_NEXT_PIER_SPACING_GRID      1533
#define IDC_SYSTEM_FACTOR_FLEXURE       1533
#define IDC_SYSTEM_FACTOR_SHEAR         1534
#define IDC_TOP_WIDTH_GRID              1534
#define IDC_STRENGTH_I_LL_INVENTORY     1536
#define IDC_STRENGTH_I_DW               1537
#define IDC_STRENGTH_I_LL_OPERATING     1538
#define IDC_SPAN_LABEL                  1539
#define IDC_SERVICE_III_DW              1539
#define IDC_SPAN_LENGTH_UNIT            1540
#define IDC_SERVICE_III_LL              1540
#define IDC_PIER_LABEL                  1541
#define IDC_ALLOWABLE_TENSION           1541
#define IDC_STATION_FORMAT              1542
#define IDC_ALLOWABLE_TENSION_UNIT      1542
#define IDC_ORIENTATION_FORMAT          1543
#define IDC_ROUTINE_LIVELOAD            1543
#define IDC_SPECIAL_LIVELOAD            1544
#define IDC_EXCLUDE_LANELOAD            1545
#define IDC_NUMGDR_PREV_SPAN            1546
#define IDC_ADTT                        1546
#define IDC_REMOVAL_EVENT               1546
#define IDC_OVERLAY_EVENT               1546
#define IDC_INSTALLATION_TYPE           1546
#define IDC_REFCOLUMN                   1546
#define IDC_EMERGENCY_LIVELOAD          1546
#define IDC_STRENGTH_I_LL_ROUTINE       1547
#define IDC_NUMGDR_SPIN_PREV_SPAN       1548
#define IDC_STRENGTH_I_LL_SPECIAL       1548
#define IDC_MOVE_LABEL                  1549
#define IDC_SERVICE_III_LL_ROUTINE      1549
#define IDC_SAME_GIRDERNAME             1550
#define IDC_SERVICE_III_LL_SPECIAL      1550
#define IDC_ROUTINE_TRUCK_IMPACT        1551
#define IDC_ROUTINE_LANE_IMPACT         1552
#define IDC_SPECIAL_TRUCK_IMPACT        1553
#define IDC_PERMIT_LIVELOAD             1553
#define IDC_SPECIAL_LANE_IMPACT         1554
#define IDC_STRENGTH_II_DC              1554
#define IDC_STRENGTH_II_DW              1555
#define IDC_EMERGENCY_TRUCK_IMPACT      1555
#define IDC_PREV_PIER_GIRDER_SPACING_MEASURE 1556
#define IDC_STRENGTH_II_LL_PERMIT       1556
#define IDC_EMERGENCY_LANE_IMPACT       1556
#define IDC_NEXT_PIER_GIRDER_SPACING_MEASURE 1557
#define IDC_SERVICE_I_DC                1557
#define IDC_STRENGTH_I_LL_EMERGENCY     1557
#define IDC_SERVICE_I_DW                1558
#define IDC_SERVICE_III_LL_SPECIAL2     1558
#define IDC_SERVICE_III_LL_EMERGENCY    1558
#define IDC_SERVICE_I_LL_PERMIT         1559
#define IDC_PREV_SPAN_SPACING_GRID      1560
#define IDC_LEGAL                       1560
#define IDC_PERMIT_LIVELOAD2            1560
#define IDC_PERMIT                      1561
#define IDC_LIVELOAD                    1561
#define IDC_TS_JACK                     1561
#define IDC_IGNORE_SHRINKAGE            1561
#define IDC_STRENGTH_II_LL_SPECIAL      1561
#define IDC_SHOW_NUMBERS                1562
#define IDC_NEXT_SPAN_SPACING_GRID      1562
#define IDC_PEDESTRIAN                  1562
#define IDC_USER_EC                     1562
#define IDC_OVERLAY                     1562
#define IDC_SERVICE_III_CR              1562
#define IDC_IGNORE_CREEP                1562
#define IDC_ADD_SPAN                    1563
#define IDC_SERVICE_III_SH              1563
#define IDC_LOAD_RATING                 1563
#define IDC_REMOVE_SPAN                 1564
#define IDC_SERVICE_III_LL_PERMIT       1564
#define IDC_FATIGUE_I_CR                1565
#define IDC_SERVICE_I_LL_SPECIAL        1565
#define IDC_NUMGDR_PREV_SPAN_LABEL      1566
#define IDC_FATIGUE_I_SH                1566
#define IDC_NUMGDR_NEXT_SPAN_LABEL      1567
#define IDC_FATIGUE_I_PS                1567
#define IDC_SERVICE_IA_CR               1568
#define IDC_SERVICE_IA_SH               1569
#define IDC_SERVICE_IA_PS               1570
#define IDC_STRENGTH_I_CR_MIN           1571
#define IDC_STRENGTH_I_SH_MIN           1572
#define IDC_STRENGTH_I_CR_MAX           1574
#define IDC_STRENGTH_I_SH_MAX           1575
#define IDC_SPAN_LENGTH_NOTE            1577
#define IDC_STRENGTH_II_CR_MIN          1577
#define IDC_STRENGTH_II_SH_MIN          1578
#define IDC_BACKGROUP                   1579
#define IDC_AHEADGROUP                  1580
#define IDC_STRENGTH_II_CR_MAX          1580
#define IDC_STRENGTH_II_SH_MAX          1581
#define IDC_BACKGROUP2                  1581
#define IDC_GIRDER_ORIENTATION_LABEL    1587
#define IDC_GIRDER_FAMILY_LABEL         1590
#define IDC_DECK_TYPE_LABEL             1591
#define IDC_LEFT_SIDEWALK               1592
#define IDC_LEFT_SIDEWALK_WIDTH         1593
#define IDC_LEFT_SIDEWALK_WIDTH_UNIT    1594
#define IDC_LEFT_SIDEWALK_LEFT_DEPTH_UNIT 1595
#define IDC_LEFT_SIDEWALK_RIGHT_DEPTH   1596
#define IDC_LEFT_SIDEWALK_RIGHT_DEPTH_UNIT 1597
#define IDC_LIST_TITLE                  1597
#define IDC_LEFT_EXTERIORBARRIER        1598
#define IDC_LEFT_INTERIORBARRIER        1599
#define IDC_SOURCE_LIST                 1599
#define IDC_RIGHT_EXTERIORBARRIER       1600
#define IDC_LOAD_UNIT                   1600
#define IDC_RIGHT_INTERIORBARRIER       1601
#define IDC_HELPME                      1601
#define IDC_LEFT_INTERIOR_BARRIER       1602
#define IDC_LEFT_SIDEWALK_WIDTH_LABEL   1603
#define IDC_REF_GIRDER_LABEL            1603
#define IDC_LEFT_SIDEWALK_LEFT_DEPTH_LABEL 1604
#define IDC_REF_GIRDER_OFFSET_TYPE_LABEL 1604
#define IDC_RIGHT_INTERIOR_BARRIER      1605
#define IDC_TEMP_STRAND_SIZE_LABEL      1605
#define IDC_PREV_PIER_LABEL             1605
#define IDC_LEFT_SIDEWALK_RIGHT_DEPTH_LABEL 1606
#define IDC_SELECT_GRID                 1606
#define IDC_NEXT_PIER_LABEL             1606
#define IDC_RIGHT_SIDEWALK_WIDTH        1607
#define IDC_GIRDER_GRID                 1607
#define IDC_LEFT_CONCRETE_TYPE_LABEL    1608
#define IDC_DUCT_GRID                   1608
#define IDC_RIGHT_SIDEWALK_WIDTH_UNIT   1609
#define IDC_PIER_RADIO                  1609
#define IDC_RIGHT_CONCRETE_TYPE_LABEL   1610
#define IDC_FILL_STATIC                 1610
#define IDC_TENDONS                     1610
#define IDC_RIGHT_SIDEWALK_WIDTH_LABEL  1611
#define IDC_GIRDER_GIRDER_STATIC        1611
#define IDC_POINT_GRID                  1611
#define IDC_SLABOFFSET_GRID             1611
#define IDC_PIER_GIRDER_STATIC          1612
#define IDC_LABEL                       1612
#define IDC_RIGHT_SIDEWALK_LEFT_DEPTH_LABEL 1613
#define IDC_NOTE                        1614
#define IDC_RIGHT_SIDEWALK_RIGHT_DEPTH_LABEL 1615
#define IDC_START_GROUP_SPIN            1615
#define IDC_NOTE2                       1615
#define IDC_WOBBLE_PT                   1615
#define IDC_RIGHT_SIDEWALK_LEFT_DEPTH_UNIT 1616
#define IDC_END_GROUP_EDIT              1616
#define IDC_WOBBLE_TTS                  1616
#define IDC_END_GROUP_SPIN              1617
#define IDC_LEFT_PRISMATIC_FLANGE_DEPTH 1617
#define IDC_DAY                         1617
#define IDC_FRICTION_PT                 1617
#define IDC_X5                          1617
#define IDC_RIGHT_SIDEWALK_RIGHT_DEPTH  1618
#define IDC_DESIGN_PEDES_STATIC         1618
#define IDC_GDR_TYPE_LABEL              1618
#define IDC_LEFT_TAPERED_FLANGE_DEPTH   1618
#define IDC_FRICTION_TTS                1618
#define IDC_FATIGUE_PEDES_STATIC        1619
#define IDC_RIGHT_TAPERED_FLANGE_DEPTH  1619
#define IDC_RIGHT_SIDEWALK_RIGHT_DEPTH_UNIT 1620
#define IDC_PERMIT_PEDES_STATIC         1620
#define IDC_FCI_LABEL                   1620
#define IDC_RIGHT_PRISMATIC_FLANGE_DEPTH 1620
#define IDC_FC_LABEL                    1621
#define IDC_VERT_GROUP                  1621
#define IDC_STRAND_GRID                 1622
#define IDC_SERVICE_IA_LABEL            1622
#define IDC_SERVICE_IA_DC_LABEL         1623
#define IDC_GIRDER_SPACING_TYPE         1624
#define IDC_SERVICE_IA_DW_LABEL         1624
#define IDC_SEGMENT                     1624
#define IDC_SERVICE_IA_LLIM_LABEL       1625
#define IDC_GIRDER_SPACING_LABEL        1625
#define IDC_LEFT_PRISMATIC_LENGTH_UNIT  1625
#define IDC_FATIGUE_I_DC_LABEL          1626
#define IDC_PREV_PIER_GIRDER_SPACING_LABEL 1626
#define IDC_LEFT_PRISMATIC_HEIGHT       1626
#define IDC_GIRDER_SPACING_TYPE2        1626
#define IDC_WORKPOINT_TYPE              1626
#define IDC_FATIGUE_I_LABEL             1627
#define IDC_NEXT_PIER_GIRDER_SPACING_LABEL 1627
#define IDC_LEFT_PRISMATIC_HEIGHT_UNIT  1627
#define IDC_FATIGUE_I_DW_LABEL          1628
#define IDC_ROA_STATIC                  1628
#define IDC_LEFT_PRISMATIC_FLANGE_DEPTH_UNIT 1628
#define IDC_FATIGUE_I_LLIM_LABEL        1629
#define IDC_ROA_STATIC2                 1629
#define IDC_LEFT_TAPERED_LENGTH_UNIT    1629
#define IDC_GRID_STATIC                 1630
#define IDC_LEFT_TAPERED_HEIGHT         1630
#define IDC_HARP_END_STATIC2            1631
#define IDC_LEFT_TAPERED_HEIGHT_UNIT    1631
#define IDC_HARP_HP_STATIC2             1632
#define IDC_LEFT_TAPERED_FLANGE_DEPTH_UNIT 1632
#define IDC_HARP_END_UNIT               1633
#define IDC_RIGHT_TAPERED_LENGTH_UNIT   1633
#define IDC_HARP_HP_UNIT                1634
#define IDC_RIGHT_TAPERED_HEIGHT        1634
#define IDC_HARP_GROUP                  1635
#define IDC_RIGHT_TAPERED_HEIGHT_UNIT   1635
#define IDC_HARP_END_STATIC1            1636
#define IDS_E_BADINSTALL                1636
#define IDC_RIGHT_TAPERED_FLANGE_DEPTH_UNIT 1636
#define IDC_HARP_HP_STATIC1             1637
#define IDC_RIGHT_PRISMATIC_LENGTH_UNIT 1637
#define IDS_E_PROBPERSISTS              1638
#define IDC_DEBONDED                    1638
#define IDC_RIGHT_PRISMATIC_HEIGHT      1638
#define IDC_RIGHT_PRISMATIC_HEIGHT_UNIT 1639
#define IDC_STRAIGHT                    1639
#define IDS_E_INVALIDFORMAT             1640
#define IDC_STATION_LOCATION_LABEL      1640
#define IDC_RIGHT_PRISMATIC_FLANGE_DEPTH_UNIT 1640
#define IDC_HARPED                      1640
#define IDC_GROUP_COUNT                 1640
#define IDC_LINE_GROUP                  1641
#define IDC_LEFT_PRISMATIC_LABEL        1641
#define IDS_E_FILENOTFOUND              1642
#define IDC_SPAN_LENGTH_BASIS           1642
#define IDC_LEFT_TAPERED_LABEL          1642
#define IDC_VERT_STATIC                 1643
#define IDC_RIGHT_TAPERED_LABEL         1643
#define IDS_E_READ                      1644
#define IDC_USER_LLDF_NOTE              1644
#define IDC_RIGHT_PRISMATIC_LABEL       1644
#define IDS_E_FORMAT                    1646
#define IDC_LEFT_END_BLOCK_LABEL        1646
#define IDC_NORTHING                    1647
#define IDC_LEFT_END_BLOCK_LENGTH       1647
#define IDC_LEFT_END_BLOCK_LENGTH_UNIT  1648
#define IDC_EASTING                     1649
#define IDC_LEFT_END_BLOCK_TRANSITION   1649
#define IDC_LEFT_END_BLOCK_TRANSITION_UNIT 1650
#define IDC_BOUNDARY_CONDITIONS         1651
#define IDC_LEFT_END_BLOCK_WIDTH        1651
#define IDC_LEFT_END_BLOCK_WIDTH_UNIT   1652
#define IDC_BC_GROUP                    1653
#define IDC_RIGHT_END_BLOCK_LABEL       1653
#define IDC_RIGHT_END_BLOCK_LENGTH      1654
#define IDC_GROUP                       1655
#define IDC_RIGHT_END_BLOCK_LENGTH_UNIT 1655
#define IDC_RIGHT_END_BLOCK_TRANSITION  1656
#define IDC_RIGHT_END_BLOCK_TRANSITION_UNIT 1657
#define IDC_RIGHT_END_BLOCK_WIDTH       1658
#define IDC_RIGHT_END_BLOCK_WIDTH_UNIT  1659
#define IDC_SEGMENT_LENGTH              1660
#define IDC_DRAW_SEGMENT                1661
#define IDC_END_DISTANCE_LABEL          1662
#define IDC_BEARING_OFFSET_LABEL        1663
#define IDS_E_LOWRESOURCES              1665
#define IDC_SPACING_MEASUREMENT         1665
#define IDC_WSDOT                       1666
#define IDC_SPACING_GRID                1666
#define IDS_DLG_STATIONFMT_SI           1667
#define IDC_TXDOT                       1668
#define IDC_REF_GIRDER_FROM             1668
#define IDC_KDOT                        1669
#define IDS_DLG_STATIONFMT_US           1669
#define IDC_BRIDGESIGHT                 1670
#define IDS_DLG_ORIENTATIONFMT          1671
#define IDC_LEFT_SIDEWALK_PLACEMENT     1672
#define IDC_LEFT_BEARING_OFFSET         1672
#define IDC_LEFT_BEARING_OFFSET_T       1673
#define IDS_GRADE1725_US                1674
#define IDC_LEFT_END_DISTANCE           1674
#define IDC_RIGHT_SIDEWALK_PLACEMENT    1675
#define IDC_LEFT_END_DISTANCE_T         1675
#define IDC_LABEL_BEARINGS              1676
#define IDC_LEFT_SUPPORT_WIDTH          1676
#define IDC_LEFT_SUPPORT_WIDTH_T        1677
#define IDS_GRADE1725_SI                1678
#define IDC_DIAPHRAGM_OFFSET_LABEL      1678
#define IDC_BACK_DIAPHRAGM_OFFSET_LABEL 1678
#define IDC_LEFT_STRUCTURALLY_CONTINUOUS 1679
#define IDC_LEFT_LABEL                  1679
#define IDC_RIGHT_LABEL                 1680
#define IDS_GRADE1860_US                1681
#define IDC_SUPPORT_WIDTH_LABEL         1681
#define IDC_RIGHT_STRUCTURALLY_CONTINUOUS 1682
#define IDC_SPACING_GROUP               1682
#define IDC_AHEAD_DIAPHRAGM_OFFSET_LABEL 1682
#define IDC_REF_GIRDER                  1683
#define IDC_NO_SPACING_NOTE             1684
#define IDS_GRADE1860_SI                1685
#define IDC_STRAND                      1685
#define IDC_REF_GIRDER_OFFSET           1686
#define IDC_CB_FILLETTYPE               1686
#define IDS_GDRSEL_EXCEED_MAX_STRAND    1687
#define IDC_REF_GIRDER_OFFSET_UNIT      1688
#define IDS_PSFORCE_EXCEED_MAX          1689
#define IDC_MOVE_LEFT                   1689
#define IDC_REF_GIRDER_OFFSET_TYPE      1690
#define IDC_ACTIVITY_GRID               1691
#define IDC_PREV_REF_GIRDER             1692
#define IDC_TARGET_LIST                 1693
#define IDC_PREV_REF_GIRDER_OFFSET      1694
#define IDS_BROWSER_ERROR               1695
#define IDC_ACTIVITIES_LABEL            1695
#define IDC_PREV_REF_GIRDER_OFFSET_UNIT 1696
#define IDC_EVENT_LABEL                 1696
#define IDS_RESULTS_NOT_AVAILABLE       1697
#define IDC_DECK_EVENT_LABEL            1697
#define IDC_PREV_REF_GIRDER_OFFSET_TYPE 1698
#define IDC_ORIENT_PIERS                1698
#define IDS_COMPANY                     1699
#define IDC_NEXT_REF_GIRDER             1700
#define IDC_NEXT_REF_GIRDER_OFFSET      1702
#define IDC_NEXT_REF_GIRDER_OFFSET_UNIT 1704
#define IDC_NEXT_REF_GIRDER_OFFSET_TYPE 1705
#define IDC_PREV_REF_GIRDER_LABEL       1706
#define IDC_PREV_REF_GIRDER_FROM        1707
#define IDC_NEXT_REF_GIRDER_LABEL       1708
#define IDC_NEXT_REF_GIRDER_FROM        1709
#define IDC_RADIO1                      1710
#define IDC_RADIO_SINGLE                1710
#define IDC_GIRDER_RADIO                1710
#define IDC_LLDF_SINGLE_VALUE           1710
#define IDC_ALPHA                       1711
#define IDC_RADIO_MULTIPLE              1711
#define IDS_PGSUPER_TEMPLATE_FILE_SUFFIX 1712
#define IDS_PGSPLICE_TEMPLATE_FILE_SUFFIX 1713
#define IDC_START_SLAB_OFFSET_LABEL     1714
#define IDS_DEFAULT_MASTER_LIB          1717
#define IDC_END_SLAB_OFFSET_LABEL       1718
#define IDS_CANT_FIND_LIBRARY_FILE      1719
#define IDC_END_SLAB_OFFSET_UNIT        1720
#define IDS_CORRUPTED_LIBRARY_FILE      1721
#define IDS_E_EXCESSIVE_SKEW            1723
#define IDS_E_EXCESSIVE_DELTA_SKEW      1725
#define IDC_SIP_LABEL                   1726
#define IDS_E_PIER_LAYOUT               1727
#define IDS_E_NOCHAPTERS                1728
#define IDC_TO_SPAN                     1729
#define IDC_HEIGHT_MEASURE              1731
#define IDC_TO_GIRDER                   1732
#define IDC_LLDF_GIRDERS_TABW           1734
#define IDC_LLDF_TABW                   1734
#define IDC_LLDF_PIERS_TABW             1735
#define IDS_E_UPDATE                    1740
#define IDC_LEFT_FC_LABEL               1743
#define IDC_ANALYSISTYPE                1744
#define IDC_LEFT_FC                     1745
#define IDC_GROUP_LABEL                 1745
#define IDC_RELAXATION_TIME_UNIT        1746
#define IDC_LEFT_FC_UNIT                1747
#define IDC_AGE                         1747
#define IDC_WIDTH                       1747
#define IDC_H1                          1747
#define IDC_AGE_UNIT                    1748
#define IDC_H2                          1748
#define IDC_LEFT_MOD_E                  1749
#define IDC_FC1                         1749
#define IDC_H3                          1749
#define IDC_FC2                         1750
#define IDS_E_INVALIDVERSION            1750
#define IDC_H4                          1750
#define IDC_LEFT_EC                     1751
#define IDC_X1                          1751
#define IDC_X2                          1752
#define IDC_LEFT_EC_UNIT                1753
#define IDC_W                           1753
#define IDC_OVERLAY_NOTE                1754
#define IDC_X6                          1754
#define IDC_LEFT_MORE                   1755
#define IDC_REFCOLUMN_OFFSET            1755
#define IDC_REFCOLUMN_OFFSET_UNIT       1756
#define IDC_TTS_USE                     1756
#define IDC_END_BLOCK_TRANSITION_LABEL  1756
#define IDC_END_BLOCK_WIDTH_LABEL       1757
#define IDC_RIGHT_FC_LABEL              1758
#define IDC_RIGHT_FC                    1759
#define IDC_RIGHT_FC_UNIT               1760
#define IDC_SERVICE_I_PLUS              1760
#define IDC_RIGHT_MOD_E                 1761
#define IDC_SERVICE_I_CR_LABEL          1761
#define IDC_RIGHT_EC                    1762
#define IDC_SERVICE_I_SH_LABEL          1762
#define IDC_RIGHT_EC_UNIT               1763
#define IDC_SERVICE_I_PS_LABEL          1763
#define IDC_RIGHT_MORE                  1764
#define IDC_STRENGTH_I_PLUS             1764
#define IDC_LEFT_DENSITY                1765
#define IDC_STRENGTH_I_CR_LABEL         1765
#define IDC_LEFT_DENSITY_UNIT           1766
#define IDC_STRENGTH_I_SH_LABEL         1766
#define IDC_RIGHT_DENSITY               1767
#define IDC_STRENGTH_I_PS_LABEL         1767
#define IDC_STRENGTH_II_PLUS            1768
#define IDC_RIGHT_DENSITY_UNIT          1769
#define IDC_STRENGTH_II_CR              1769
#define IDC_LEFT_CONCRETE_LABEL         1770
#define IDC_STRENGTH_II_CR_LABEL        1770
#define IDC_STRENGTH_II_SH              1771
#define IDC_LEFT_RAILING_GROUP          1772
#define IDC_STRENGTH_II_SH_LABEL        1772
#define IDC_RIGHT_RAILING_GROUP         1773
#define IDC_STRENGTH_II_PS              1773
#define IDC_STRENGTH_II_PS_LABEL        1774
#define IDC_START_SLAB_OFFSET_UNIT      1775
#define IDC_SERVICE_IA_PS_LABEL         1775
#define IDC_TENDON_LABEL                1775
#define IDC_ADJUSTMENT_LABEL            1778
#define IDC_ADJUSTMENT_UNIT             1779
#define IDC_BACK_SLAB_OFFSET            1780
#define IDC_BACK_SLAB_OFFSET_UNIT       1781
#define IDC_DRAW_STRANDS                1781
#define IDC_AHEAD_SLAB_OFFSET           1782
#define IDC_SS_LABEL                    1782
#define IDC_AHEAD_SLAB_OFFSET_UNIT      1783
#define IDC_HS_LABEL                    1783
#define IDC_BACK_SLAB_OFFSET_LABEL      1784
#define IDC_AHEAD_SLAB_OFFSET_LABEL     1785
#define IDC_TS_LABEL                    1785
#define IDC_NUMGDR_LABEL                1786
#define IDC_SEGMENT_LENGTH_LABEL        1786
#define IDC_EXTENSIONS                  1787
#define IDC_CANTILEVER_GROUP            1788
#define IDC_START_CANTILEVER_LABEL      1789
#define IDC_START_CANTILEVER_UNIT       1791
#define IDC_END_CANTILEVER_LABEL        1792
#define IDC_BACK_DIAPHRAGM_LABEL        1792
#define IDC_END_CANTILEVER_UNIT         1793
#define IDC_BACK_DIAPHRAGM_HEIGHT_LABEL 1793
#define IDC_BACK_DIAPHRAGM_WIDTH_LABEL  1794
#define IDC_AHEAD_DIAPHRAGM_LABEL       1795
#define IDC_AHEAD_DIAPHRAGM_HEIGHT_LABEL 1796
#define IDC_AHEAD_DIAPHRAGM_WIDTH_LABEL 1797
#define IDC_HEIGHT_UNIT                 1799
#define IDC_HEIGHT_LABEL                1800
#define IDC_WIDTH_LABEL                 1801
#define IDC_WIDTH_UNIT                  1802
#define IDC_DIAPHRAGM_GROUP             1803
#define IDC_IGNORE_RELAXATION           1806
#define IDC_SLIDER                      1807
#define IDC_DIAPHRAGM_HEIGHT_LABEL      1808
#define IDC_DIAPHRAGM_WIDTH_LABEL       1809
#define IDC_PIER_LAYOUT                 1811
#define IDC_H1_UNIT                     1812
#define IDC_H1_LABEL                    1813
#define IDC_H2_LABEL                    1814
#define IDC_H2_UNIT                     1815
#define IDC_H3_LABEL                    1816
#define IDC_H3_UNIT                     1817
#define IDC_H4_LABEL                    1818
#define IDC_H4_UNIT                     1819
#define IDC_X1_LABEL                    1820
#define IDC_X1_UNIT                     1821
#define IDC_X2_LABEL                    1822
#define IDC_X3_LABEL                    1823
#define IDC_X2_UNIT                     1824
#define IDC_X4_LABEL                    1825
#define IDC_W_UNIT                      1826
#define IDC_X5_LABEL                    1827
#define IDC_X5_UNIT                     1828
#define IDC_W_LABEL                     1829
#define IDC_X3                          1830
#define IDC_X3_UNIT                     1831
#define IDC_X4                          1832
#define IDC_X4_UNIT                     1833
#define IDC_STRENGTH_I_SH               1843
#define IDC_STRENGTH_I_PS               1844
#define IDC_EC_LABEL                    1846
#define IDC_PIER_MODEL_LABEL            1849
#define IDC_DIMENSIONS_NOTE             1850
#define IDC_LOAD_RATING_EVENT_LABEL     1851
#define IDC_GROUP_RANGE_LABEL           1854
#define IDC_GROUP_RANGE_TO              1855
#define IDC_FIXITY_LABEL                1856
#define IDC_GROUP_RANGE_LABEL2          1856
#define IDC_FIXITY                      1857
#define IDC_DIAPHRAGM_NOTE              1858
#define IDC_SERVICE_I_CR                1859
#define IDC_CURING_UNIT                 1859
#define IDC_SERVICE_I_SH                1860
#define IDC_SERVICE_I_PS                1861
#define IDC_CHECK_YIELDING              1862
#define IDC_TOP_COVER_LABEL             1862
#define IDC_FY_LABEL                    1863
#define IDC_BOTTOM_COVER_LABEL          1863
#define IDC_FY                          1864
#define IDC_TOP_MAT_BAR_LABEL           1864
#define IDC_SERVICE_III_CR_LABEL        1865
#define IDC_BOTTOM_MAT_BAR_LABEL        1865
#define IDC_SERVICE_III_SH_LABEL        1866
#define IDC_TOP_MAT_BAR_AT              1866
#define IDC_SERVICE_III_PS_LABEL        1867
#define IDC_TOP_MAT_BAR_PLUS            1867
#define IDC_FATIGUE_I_PLUS              1868
#define IDC_BOTTOM_MAT_BAR_AT           1868
#define IDC_FATIGUE_I_CR_LABEL          1869
#define IDC_BOTTOM_MAT_BAR_PLUS         1869
#define IDC_FATIGUE_I_SH_LABEL          1870
#define IDC_PRIMARY_REBAR_GROUP         1870
#define IDC_FATIGUE_I_PS_LABEL          1871
#define IDC_SECONDARY_REBAR_GROUP       1871
#define IDC_SERVICE_IA_PLUS             1872
#define IDC_PRIMARY_REBAR_GROUP_LABEL   1872
#define IDC_SERVICE_IA_CR_LABEL         1873
#define IDC_SECONDARY_REBAR_GROUP_LABEL 1873
#define IDC_SERVICE_IA_SH_LABEL         1874
#define IDC_HPOFFSET_START_LABEL        1874
#define IDC_SERVICE_III_PS              1875
#define IDC_HPOFFSET_END_LABEL          1875
#define IDC_SLAB_OFFSET_UNITS           1876
#define IDC_SLAB_OFFSET_BOX             1877
#define IDC_HAUNCH_GRID                 1878
#define IDC_FILLET_BOX                  1878
#define IDC_ASSUMED_EXCESS_CAMBER_BOX   1878
#define IDC_HAUNCH_SHAPE_LABEL          1880
#define IDC_HAUNCH_SHAPE_LABEL2         1881
#define IDC_ALLOWABLE_TENSION_LABEL     1882
#define IDC_DECK_DEPTH                  1882
#define IDC_MATERIAL_GROUP              1883
#define IDC_CAP_GROUP                   1884
#define IDC_COLUMN_GROUP                1885
#define IDC_SOURCE_LABEL                1886
#define IDC_TARGET_LABEL                1887
#define IDC_FILLET_GRID                 1888
#define IDC_DESIGNA_STATIC              1888
#define IDC_ASSUMED_EXCESS_CAMBER_GRID  1888
#define IDC_EXTENDED_STRANDS_LABEL      1889
#define IDC_DEBONDED_STRANDS_LABEL      1890
#define IDC_START                       1891
#define IDC_END                         1892
#define IDC_STRENGTH_I_CR_MIN_LABEL     1893
#define IDC_STRENGTH_I_CR_MAX_LABEL     1894
#define IDC_STRENGTH_I_SH_MIN_LABEL     1895
#define IDC_STRENGTH_I_SH_MAX_LABEL     1896
#define IDC_STRENGTH_II_CR_MIN_LABEL    1897
#define IDC_STRENGTH_II_CR_MAX_LABEL    1898
#define IDC_SERVICE_III_PLUS            1899
#define IDC_STRENGTH_II_SH_MIN_LABEL    1900
#define IDC_STRENGTH_II_SH_MAX_LABEL    1901
#define IDC_STRENGTH_I_PLUS2            1902
#define IDC_STRENGTH_II_PLUS2           1903
#define IDC_BUTTON1                     1904
#define IDC_NORTH                       1904
#define IDC_STRANDS                     1904
#define IDC_EDIT_BEARINGS               1904
#define IDC_DECK_EVENT_DETAILS          1904
#define IDC_HELP                        1904
#define IDC_VIEW_TIMELINE_SUMMARY       1904
#define IDC_LABELS                      1905
#define IDC_BUTTON2                     1905
#define IDC_EDIT                        1905
#define IDC_LOAD_LOCATION_NOTE          1906
#define IDC_TOP_WIDTH_LABEL             1906
#define IDI_STIRRUPS                    1906
#define IDC_LONGITUDINAL_REINFORCEMENT  1906
#define IDC_TOP_WIDTH                   1907
#define IDC_LONGITUDINAL_REINFORCEMENT2 1907
#define IDC_STIRRUPS                    1907
#define IDC_BRG_TYPE                    1907
#define IDC_ASSUMED_EXCESS_CAMBER       1907
#define IDC_TOP_WIDTH_UNIT              1908
#define IDC_STIRRUPS2                   1908
#define IDC_USER_LOADS                  1908
#define IDC_BRG_SHAPE                   1908
#define IDC_ASSUMED_EXCESS_CAMBER_UNIT  1908
#define IDC_ALLOWABLE_TOP_WIDTH         1909
#define IDC_USER_LOADS2                 1909
#define IDC_SCHEMATIC                   1909
#define IDC_ASSUMED_EXCESS_CAMBER_LABEL2 1909
#define IDC_BRG_COUNT                   1910
#define IDC_SCHEMATIC2                  1910
#define IDC_RW_CS                       1910
#define IDC_BRG_SPACING                 1911
#define IDC_ASSUMED_EXCESS_CAMBER_GROUP 1911
#define IDC_TOP_WIDTH_GRID_LABEL        1912
#define IDC_BRG_SPACING_UNIT            1912
#define IDC_BRG_LENGTH                  1913
#define IDC_BRG_BOX                     1913
#define IDC_BRG_LENGTH_UNIT             1914
#define IDC_TOP_FLANGE_THICKENING_LABEL 1914
#define IDC_BRG_WIDTH                   1915
#define IDC_TOP_FLANGE_THICKENING_TYPE  1915
#define IDC_BRG_WIDTH_UNIT              1916
#define IDC_TOP_FLANGE_THICKENING       1916
#define IDC_BRG_HEIGHT                  1917
#define IDC_TOP_FLANGE_THICKENING_UNIT  1917
#define IDC_BRG_HEIGHT_UNIT             1918
#define IDC_PRECAMBER_LABEL             1918
#define IDC_BRG_RECESS                  1919
#define IDC_PRECAMBER                   1919
#define IDC_BRG_RECESS_UNIT             1920
#define IDC_PRECAMBER_UNIT              1920
#define IDC_BRG_SOLEPLATE               1921
#define IDC_LONGITUDINAL_JOINT_MATERIAL_GROUP 1921
#define IDI_LONGITUDINAL_REINFORCEMENT  1922
#define IDC_BRG_SOLEPLATE_UNIT          1922
#define IDC_INTERMEDIATE_DIAPHRAGMS     1923
#define IDC_BRG_WIDTH_STATIC            1923
#define IDC_BRG_LENGTH_STATIC           1924
#define IDC_CHECK1                      1925
#define IDC_STRANDS_CG                  1925
#define IDC_BRG_RECESS_LENGTH           1925
#define IDC_DONT_WARN                   1925
#define IDC_GCE_CHECK                   1925
#define IDC_STRANDS_CG2                 1926
#define IDC_SECTION_CG                  1926
#define IDC_EDIT1                       1926
#define IDC_BRG_SPACING_STATIC          1926
#define IDC_VIEW_TEMPLATE_EDIT          1926
#define IDC_TIME_BETWEEN_CASTING        1926
#define IDC_STARTPIERNO                 1926
#define IDC_NAME                        1926
#define IDC_BRG_RECESS_LENGTH_UNIT      1927
#define IDC_BEARING_GRID                1928
#define IDC_BRG1_STATIC                 1928
#define IDC_STATIC_B1                   1929
#define IDC_STATIC_B2                   1930
#define IDC_STATIC_B3                   1931
#define IDC_STATIC_B4                   1932
#define IDC_STATIC_B5                   1933
#define IDC_STATIC_B6                   1934
#define IDC_BRG_SHAPE_1                 1935
#define IDC_BRG_SPACING_1               1936
#define IDC_BRG_LENGTH_1                1937
#define IDC_BRG_WIDTH_1                 1938
#define IDC_BRG_HEIGHT_1                1939
#define IDC_BRG_RECESS_1                1940
#define IDC_BRG_SOLEPLATE_1             1941
#define IDC_BRG_COUNT_1                 1942
#define IDC_BRG_RECESS_LENGTH_1         1943
#define IDC_BRG_SHAPE_2                 1944
#define IDC_BRG_SPACING_2               1945
#define IDC_BRG_LENGTH_2                1946
#define IDC_BRG_WIDTH_2                 1947
#define IDC_BRG_HEIGHT_2                1948
#define IDC_BRG_RECESS_2                1949
#define IDC_BRG_SOLEPLATE_2             1950
#define IDC_BRG_COUNT_2                 1951
#define IDC_BRG_RECESS_LENGTH_2         1952
#define IDC_BRG2_STATIC                 1953
#define IDC_RIGHT_TOP_WIDTH             1954
#define IDC_TOP_WIDTH_TYPE              1955
#define IDC_RIGHT_TOP_WIDTH_UNIT        1956
#define IDC_LEFT_TOP_WIDTH              1957
#define IDC_LEFT_TOP_WIDTH_UNIT         1958
#define IDC_LEFT_TOP_WIDTH_LABEL        1959
#define IDC_RIGHT_TOP_WIDTH_LABEL       1960
#define IDC_COMBO1                      1961
#define IDC_X1_MEASURE                  1961
#define IDC_NUMSEGMENTS_COMBO           1961
#define IDC_REGION_BOUNDARY             1961
#define IDC_START_PIER                  1961
#define IDC_START_CB                    1961
#define IDC_DEFAULT_OPTIONS             1961
#define IDC_RATE_FOR_STRESS             1962
#define IDC_X2_MEASURE                  1962
#define IDC_RIDGEPT_COMBO               1962
#define IDC_START_PIER2                 1962
#define IDC_END_PIER                    1962
#define IDC_END_CB                      1962
#define IDI_STRANDS                     1963
#define IDC_X3_MEASURE                  1963
#define IDC_VIEW_TEMPLATE_COMBO         1963
#define IDC_PROFILE_GRADE_POINT         1963
#define IDI_STRANDS_CG                  1964
#define IDC_X1_MEASURE4                 1964
#define IDC_X4_MEASURE                  1964
#define IDI_DIMENSIONS                  1965
#define IDI_USER_LOADS                  1966
#define IDI_SCHEMATIC                   1967
#define IDI_SECTION_CG                  1968
#define IDI_NORTH                       1969
#define IDI_LABELS                      1970
#define IDI_BRIDGE                      1971
#define IDI_SCHEMATIC_PROFILE           1972
#define IDI_PROPERTIES                  1973
#define IDC_PROPERTIES                  1984
#define IDC_DIMENSIONS                  1985
#define IDC_SHOW_BRIDGE                 1986
#define IDC_DIMENSIONS2                 1987
#define IDC_GIRDER_MODIFIERS_NOTE       1987
#define IDC_LEFT_TOP_WIDTH_START        1988
#define IDC_LEFT_TOP_WIDTH_START_UNIT   1989
#define IDC_RIGHT_TOP_WIDTH_START       1990
#define IDC_RIGHT_TOP_WIDTH_START_UNIT  1991
#define IDC_LEFT_TOP_WIDTH_END          1992
#define IDC_LEFT_TOP_WIDTH_END_UNIT     1993
#define IDC_RIGHT_TOP_WIDTH_END         1994
#define IDC_RIGHT_TOP_WIDTH_END_UNIT    1995
#define IDC_TOP_WIDTH_START_LABEL       1996
#define IDC_TOP_WIDTH_START_LABEL2      1997
#define IDC_TOP_WIDTH_END_LABEL         1997
#define IDC_HG_X1                       1997
#define IDC_HG_X2                       1998
#define IDC_BEARING                     1998
#define IDC_HG_X3                       1999
#define IDC_LEFT_OVERHANG_DEPTH_LABEL   1999
#define IDC_HG_X4                       2000
#define IDC_RIGHT_OVERHANG_DEPTH_LABEL  2000
#define IDC_SLAB_OFFSET_GROUP           2001
#define IDC_ADJUSTMENT_GROUP            2004
#define IDC_PROMPT                      2005
#define IDC_LIST1                       2006
#define IDC_VIEW_TEMPLATE_SPIN          2006
#define IDC_CAST_DECK_1                 2008
#define IDC_CAST_DECK_2                 2009
#define IDC_DECK_REGION_GRID            2010
#define IDC_TIME_BETWEEN_CASTING_LABEL  2015
#define IDC_TIME_BETWEEN_CASTING_UNIT   2016
#define IDC_DECK_REGIONS                2018
#define IDC_PLACEMENT_REGION_LABEL      2019
#define IDC_REGION_BOUNDARY_LABEL       2020
#define IDC_HG_START                    2021
#define IDC_HG_MIDDLE                   2022
#define IDC_HG_END                      2023
#define IDC_INSTALLATION_TIME           2025
#define IDC_WORKPOINT_STATIC            2026
#define IDC_RB_COPY                     2027
#define IDC_RB_DONT_COPY                2028
#define IDC_CLOSURE_JOINT_LABEL         2029
#define IDC_COMBO2                      2030
#define IDC_CLOSURE_JOINT_CASTING_REGION 2030
#define IDC_SLOPE_MEASURE_TYPE          2030
#define IDC_STRAIGHT_STRAND_SIZE        2031
#define IDC_COMPREP                     2031
#define IDC_HARPED_STRAND_SIZE          2032
#define IDC_FROM_PIER                   2032
#define IDC_STRAIGHT_STRAND_LABEL       2033
#define IDC_TO_PIER                     2033
#define IDC_HARPED_STRAND_LABEL         2034
#define IDC_PROPERTY_LIST               2035
#define IDC_SLOPE_NOTE                  2036
#define IDC_PLACE_HOLDER                2037
#define IDC_SKETCH_PLACE_HOLDER         2038
#define IDC_HAUNCH_INPUT_TYPE           2038
#define IDC_HAUNCH_DISTRIBUTION         2039
#define IDC_PLACE_HOLDER3               2039
#define IDC_TS_ELEV_GROUPBOX            2039
#define IDC_HAUNCH_BOX                  2040
#define IDC_HAUNCH_DEPTH_TYPE           2041
#define IDC_HAUNCH_DIRECT_GRID          2042
#define IDC_HAUNCH_UNIT                 2043
#define IDC_DISTRIBUTED_TEXT            2044
#define IDC_HAUNCH_DIRECT_SPAN_GRID     2045
#define IDC_PLACEHOLDER                 2046
#define IDC_HAUNCH_DIRECT_SAMEAS_GRID   2047
#define IDC_HAUNCH_LABEL                2048
#define IDC_HAUNCH_DIRECT_ENTIRE_BRIDGE_GRID 2048
#define IDC_HAUNCH                      2049
#define IDC_HAUNCH_DIRECT_SAMEAS_GRID2  2049
#define IDC_HAUNCH_DIRECT_SAMEAS_SEGMENT_GRID 2049
#define IDC_H_UNIT                      2050
#define IDC_HAUNCH_INPUT_UNIT           2050
#define IDC_TS_ELEVATION_ADJUST_GRID    2051
#define IDS_E_WRITE                     2500
#define IDS_E_UNSAFESAVE                2501
#define IDS_E_SAVERECOVER1              2502
#define IDS_E_SAVERECOVER2              2503
#define IDC_APPLIST                     3333
#define IDR_PGSUPER_STDTOOLBAR          12129
#define IDR_LIBTOOLBAR                  12130
#define IDR_HELPTOOLBAR                 12131
#define IDR_PGSPLICE_STDTOOLBAR         12132
#define IDS_BM_VIEW_SETTINGS            12779
#define IDS_GM_VIEW_SETTINGS            12819
#define IDS_ALIGNMENTOFFSET_FMT         12874
#define IDC_EXPAND                      12878
#define IDC_JOIN                        12879
#define IDC_X6_LABEL                    12880
#define IDC_X6_UNIT                     12881
#define IDS_INCOMPATIBLE_BEARING_MSG    13100
#define IDS_INCOMPATIBLE_BEARING_MSG2   13101
#define ID_HELP_JOINARPLIST             33024
#define ID_HELP_INET_ARP                33025
#define ID_HELP_INET_WSDOT              33026
#define ID_HELP_INET_PGSUPER            33027
#define FIRST_DATA_IMPORTER_PLUGIN      33215
#define LAST_DATA_IMPORTER_PLUGIN       33245
#define FIRST_DATA_EXPORTER_PLUGIN      33250
#define LAST_DATA_EXPORTER_PLUGIN       33280
#define FIRST_COPY_GIRDER_PLUGIN        33285
#define LAST_COPY_GIRDER_PLUGIN         33310
#define FIRST_COPY_PIER_PLUGIN          33315
#define LAST_COPY_PIER_PLUGIN           33340
#define FIRST_COPY_TEMP_SUP_PLUGIN      33345
#define LAST_COPY_TEMP_SUP_PLUGIN       33370
#define ID_EDIT_SEGMENT                 36105
#define ID_EDIT_SEGMENT_MIN             36106
#define ID_EDIT_SEGMENT_MAX             36135
#define IDM_ADD_ENTRY                   36864
#define IDM_EDIT_ENTRY                  36865
#define IDM_DELETE_ENTRY                36866
#define IDM_DUPLICATE_ENTRY             36867
#define IDM_LARGE_ICONS                 36868
#define IDM_SMALL_ICONS                 36869
#define IDM_LIST_ICONS                  36870
#define IDM_RENAME_ENTRY                36872
#define IDM_EXPORT_TEMPLATE             36873
#define IDM_COPY_GIRDER_PROPS           36875
#define IDM_IMPORT_PROJECT_LIBRARY      36876
#define IDM_HINGE                       36877
#define IDM_ROLLER                      36878
#define IDM_CONTINUOUS_AFTERDECK        36879
#define IDM_CONTINUOUS_BEFOREDECK       36880
#define IDM_CONTINUOUS_SEGMENT          36881
#define IDM_INTEGRAL_AFTERDECK          36882
#define IDM_INTEGRAL_BEFOREDECK         36883
#define IDM_INTEGRAL_AFTERDECK_HINGEBACK 36884
#define IDM_INTEGRAL_BEFOREDECK_HINGEBACK 36885
#define IDM_INTEGRAL_AFTERDECK_HINGEAHEAD 36886
#define IDM_INTEGRAL_BEFOREDECK_HINGEAHEAD 36887
#define IDM_CONTINUOUS_CLOSURE          36888
#define IDM_INTEGRAL_CLOSURE            36889
#define IDM_CONTINUOUS_SEGMENT_AT_PIER  36890
#define IDM_INTEGRAL_SEGMENT_AT_PIER    36891
#define ID_UPDATE_TEMPLATE              36892
#define ID_FILE_PROJECT_PROPERTIES      36893
#define ID_EDIT_INSERTROW               36894
#define ID_VIEW_BRIDGEMODELEDITOR       36895
#define ID_VIEW_GIRDEREDITOR            36896
#define ID_EDIT_REMOVEROWS              36897
#define ID_VIEW_ANALYSISMODELEDITOR     36898
#define ID_VIEW_LIBRARYEDITOR           36899
#define ID_VIEW_REPORTS                 36900
#define ID_VIEWSETTINGS_BRIDGEMODELEDITOR 36901
#define ID_VIEWSETTINGS_GIRDEREDITOR    36902
#define ID_VIEWSETTINGS_ANALYSISMODELEDITOR 36903
#define ID_VIEWSETTINGS_LIBRARYEDITOR   36904
#define ID_PROJECT_DESIGNGIRDER         36908
#define ID_PROJECT_DESIGNGIRDERDIRECT   36909
#define ID_PROJECT_SPEC                 36910
#define ID_VIEW_ANALYSISRESULTS         36911
#define ID_PROJECT_ENVIRONMENT          36912
#define ID_PROJECT_BRIDGEDESC           36913
#define ID_LOADS_LOADMODIFIERS          36914
#define ID_LEFTEND                      36915
#define ID_RIGHTEND                     36916
#define ID_LEFT_HP                      36917
#define ID_CENTER                       36918
#define ID_RIGHT_HP                     36919
#define ID_USER_CUT                     36920
#define ID_UNUSED_1                     36921
#define ID_UNUSED_2                     36922
#define ID_UNUSED_3                     36923
#define ID_UNUSED_4                     36924
#define ID_VIEWSETTINGS                 36925
#define ID_EDIT_PRESTRESSING            36926
#define ID_EDIT_STIRRUPS                36927
#define ID_VIEW_FACTOROFSAFETY          36928
#define ID_VIEW_STABILITY               36929
#define ID_LOADS_LLDF                   36930
#define ID_ADD_POINT_LOAD               36931
#define ID_EDIT_USERLOADS               36932
#define ID_ADD_DISTRIBUTED_LOAD         36933
#define ID_EDIT_LOAD                    36934
#define ID_DELETE_LOAD                  36935
#define ID_PROJECT_ALIGNMENT            36936
#define ID_VIEW_GIRDER                  36937
#define ID_LIVE_LOADS                   36938
#define ID_ADD_MOMENT_LOAD              36939
#define ID_DUMP_LBAM                    36940
#define ID_EDIT_PIER                    36941
#define ID_EDIT_SPAN                    36942
#define ID_PROJECT_SPANDESC             36943
#define ID_PROJECT_PIERDESC             36944
#define ID_DELETE                       36945
#define ID_DELETE_PIER                  36946
#define ID_DELETE_SPAN                  36947
#define ID_INSERT                       36948
#define ID_INSERT_SPAN                  36949
#define ID_INSERT_PIER                  36950
#define ID_EDIT_DECK                    36951
#define ID_OPTIONS_HINTS                36952
#define ID_PROJECT_DESIGNGIRDERDIRECT_PRESERVEHAUNCH 36953
#define ID_REPORTS_                     36956
#define ID_OPTIONS_LABELS               36957
#define ID_RATING_SPEC                  36958
#define ID_MANAGE_PLUGINS               36960
#define ID_PROJECT_ANALYSIS             36962
#define ID_CONSTRUCTION_LOADS           36963
#define ID_EDIT_GIRDER                  36967
#define ID_INSERT_TEMPORARY_SUPPORT     36968
#define ID_EDIT_TEMPORARY_SUPPORT       36969
#define ID_DELETE_TEMPORARY_SUPPORT     36970
#define ID_EDIT_TIMELINE                36971
#define ID_ACTIVITIES_ERECT_PIERS       36973
#define ID_ACTIVITIES_REMOVE_TS         36974
#define ID_ACTIVITIES_CASTCLOSUREJOINTS 36975
#define ID_ACTIVITIES_CASTDECK          36976
#define ID_ACTIVITIES_CASTLONGITUDINALJOINTS 36977
#define ID_ACTIVITIES_APPLYLOADS        36978
#define ID_ACTIVITIES_CONSTRUCTSEGMENT  36979
#define ID_ACTIVITIES_STRESSTENDON      36980
#define ID_ACTIVITIES_ERECT_SEGMENTS    36981
#define ID_PROJECT_EFFECTIVEFLANGEWIDTH 36984
#define ID_EDIT_CLOSURE                 36985
#define ID_LOADS_LOADFACTORS            36986
#define ID_PROJECT_LOSSES               36987
#define ID_VIEW_GRAPHS                  36988
#define ID_GRAPHS_                      36989
#define ID_HELP_ABOUT                   36990
#define ID_PROJECT_PROFILE              36991
#define ID_EDIT_HAUNCH                  36994
#define ID_GIRDERVIEW_DESIGNGIRDERDIRECT 36995
#define ID_GIRDERVIEW_DESIGNGIRDERDIRECTHOLDSLABOFFSET 36996
#define ID_ADD_POINT_LOAD_CTX           36997
#define ID_ADD_DISTRIBUTED_LOAD_CTX     36998
#define ID_ADD_MOMENT_LOAD_CTX          36999
#define ID_PROJECT_BARRIER              37000
#define ID_EDIT_BEARING                 37001
#define IDM_ERECTION_TOWER              37002
#define IDM_STRONG_BACK                 37003
#define ID_COPY_GIRDER                  37004
#define ID_EDIT_COPYGIRDERPROPERTIES    37004
#define ID_COPY_PIER                    37005
#define ID_EDIT_COPYPIERPROPERTIES      37006
#define ID_EDIT_COPYTEMPSUPPORTPROPERTIES 37009
#define ID_OPTIONS_AUTOSAVE             37010
#define ID_COPY_TEMPORARYSUPPORT        37012
#define ID_TEMPORARYSUPPORT_PLACEHOLDER 37013
#define ID_ACTIVITIES_GEOMETRYCONTROLEVENT 37013
#define IDM_COPY_TEMPSUPPORT_PROPS      37014
#define IDM_COPY_PIER_PROPS             37015
#define ID_COPY_GIRDER_PROPS            37016
#define ID_COPY_PIER_PROPS              37017
#define ID_COPY_TEMPSUPPORT_PROPS       37019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        410
#define _APS_NEXT_COMMAND_VALUE         37014
#define _APS_NEXT_CONTROL_VALUE         2052
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
