///////////////////////////////////////////////////////////////////////
// PGSuper Beam Factory
// Copyright © 1999-2017  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This library is a part of the Washington Bridge Foundation Libraries
// and was developed as part of the Alternate Route Project
//
// This library is free software; you can redistribute it and/or modify it under
// the terms of the Alternate Route Library Open Source License as published by 
// the Washington State Department of Transportation, Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but is distributed 
// AS IS, WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
// or FITNESS FOR A PARTICULAR PURPOSE. See the Alternate Route Library Open Source 
// License for more details.
//
// You should have received a copy of the Alternate Route Library Open Source License 
// along with this program; if not, write to the Washington State Department of 
// Transportation, Bridge and Structures Office, P.O. Box  47340, 
// Olympia, WA 98503, USA or e-mail Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////
// The intent of licensing this interface with the ARLOSL is to provide
// third party developers a method of developing proprietary plug-ins
// to the software.
// 
// Any changes made to the interfaces defined in this file are
// are subject to the terms of the Alternate Route Library Open Source License.
//
// Components that implement the interfaces defined in this file are
// governed by the terms and conditions deemed appropriate by legal 
// copyright holder of said software.
///////////////////////////////////////////////////////////////////////


import "oaidl.idl";
import "ocidl.idl";

import "WBFLGeometry.idl";
import "WBFLGenericBridgeTools.idl";

[
   uuid(D3810B3E-91D6-4aed-A748-8ABEB87FCF44)
]
interface IDummyInterface : IUnknown
{
   [helpstring("method Dummy")] HRESULT Dummy();
};



// IStrandMover is defined in the GenericBridgeTools project. A default implementation
// is defined in Beams
[
   uuid(49D89070-3BC9-4b30-97E1-496E0715F636)
]
interface IConfigureStrandMover : IUnknown
{
   // offset limits and default increments for harped strands
   [helpstring("method SetHarpedStrandOffsetBounds")] HRESULT SetHarpedStrandOffsetBounds([in]Float64 topGirderElevation, [in]Float64 Hg,
																						  [in]Float64 topStartElevationBoundary,[in]Float64 botStartElevationBoundary,
																						  [in]Float64 topHp1ElevationBoundary,[in]Float64 botHp1ElevationBoundary,
																						  [in]Float64 topHp2ElevationBoundary,[in]Float64 botHp2ElevationBoundary,
																						  [in]Float64 topEndElevationBoundary,[in]Float64 botEndElevationBoundary,
																						  [in]Float64 endIncrement,[in]Float64 hpIncrement);
   // remove all regions
   [helpstring("method ClearAll")] HRESULT ClearAll();
   // Add a shape that is to be tested for PointInShape, and arcSlope (x/y) that a strand
   // point is to be moved along
   [helpstring("method AddRegion")] HRESULT AddRegion([in]IShape* shape,[in]Float64 arcSlope);

   // methods to help debugging
   [propget, helpstring("NumRegions")] HRESULT NumRegions([out,retval]CollectionIndexType* pNum);
   [helpstring("method GetRegion")] HRESULT GetRegion([in]CollectionIndexType index, [out]IShape** shape,[out]Float64* arcSlope);
};


[
	uuid(DC4B56B3-455B-41be-9509-289950E62190),
	version(1.00)
]
library PGSuperBeamFactory
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(EF144A97-4C75-4234-AF3C-71DC89B1C8F8)
	]
	coclass WFBeamFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(9EDBDD8D-ABBB-413a-9B2D-9EB2712BE914)
	]
	coclass TaperedIBeamFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(DA3C413D-6413-4485-BD29-E8A419E981AF)
	]
	coclass NUBeamFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(F72BA192-6D82-4d66-92CA-EB13466E6BA9)
	]
	coclass UBeamFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(DD999E90-E181-4ec8-BB82-FDFB364B7620)
	]
	coclass UBeam2Factory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(16CC6372-256E-4828-9BDA-3185C27DC65E)
	]
	coclass BulbTeeFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(51CB9247-8200-43e5-BFB0-E386C1E6A0D0)
	]
	coclass MultiWebFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(D8824656-6CB6-45c0-B5F7-13CFFA890F0B)
	]
	coclass MultiWeb2Factory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(A367FEEC-9E24-4ed6-9DD3-57F62AD752C9)
	]
	coclass DoubleTeeFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(E6F28403-A396-453b-91BE-15A68D194255)
	]
	coclass VoidedSlabFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(171FC948-C4CB-4920-B9FC-72D729F3E91A)
	]
	coclass VoidedSlab2Factory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(B195CB90-CEB0-4495-B91D-7FC6DFBF31CF)
	]
	coclass BoxBeamFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(B1F474E4-15F7-4ac8-AD2D-7FBD12E3B0EB)
	]
	coclass BoxBeam2Factory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(5D6AFD91-84F4-4755-9AF7-B760114A4551),
		helpstring("StrandMoverImpl Class")
	]
	coclass StrandMoverImpl
	{
		[default] interface IStrandMover;
      interface IConfigureStrandMover;
	};
	[
		uuid(2583C7C1-FF57-4113-B45B-702CFA6AD013),
	]
	coclass TxDotDoubleTFactory
	{
		[default] interface IDummyInterface;
	};

	[
		uuid(DEFA27AD-3D22-481b-9006-627C65D2648F)
	]
	coclass DeckedSlabBeamFactory
	{
		[default] interface IDummyInterface;
	};

   // PGSplice

   [
		uuid(94272D8A-4914-44bb-A0D2-937A6A8BD7B0)
	]
	coclass SplicedIBeamFactory
	{
		[default] interface IDummyInterface;
	};

   [
		uuid(6A00C215-C139-4755-8DD5-929EE2DED305)
	]
	coclass SplicedUBeamFactory
	{
		[default] interface IDummyInterface;
	};

   [
		uuid(42D8D32D-7A4E-4d07-A5B1-220DFCB99EE6)
	]
	coclass SplicedNUBeamFactory
	{
		[default] interface IDummyInterface;
	};

   // Distribution Factor Engineers
   [
      uuid(DFC0191F-F606-46aa-AC82-13B44878AA3B)
   ]
   coclass IBeamDistFactorEngineer
   {
      [default] interface IDummyInterface;
   };

   [
      uuid(FBD11B34-65A4-4d87-90FF-39A42EEACABA)
   ]
   coclass BoxBeamDistFactorEngineer
   {
      [default] interface IDummyInterface;
   };

   [
      uuid(49222DB8-F784-4576-811F-A831075FDDAF)
   ]
   coclass BulbTeeDistFactorEngineer
   {
      [default] interface IDummyInterface;
   };

   [
      uuid(27013EA9-0AA9-4b85-80D0-0904A3D762DA)
   ]
   coclass MultiWebDistFactorEngineer
   {
      [default] interface IDummyInterface;
   };

   [
      uuid(62C15951-4A40-46cf-B326-D40D248F1299)
   ]
   coclass UBeamDistFactorEngineer
   {
      [default] interface IDummyInterface;
   };

   [
      uuid(53884B6C-07D5-4e5e-9ED3-DF162DE1C27E)
   ]
   coclass VoidedSlabDistFactorEngineer
   {
      [default] interface IDummyInterface;
   };

   [
      uuid(7B95DAC5-4E68-4e16-8504-22D21A0E6B52)
   ]
   coclass VoidedSlab2DistFactorEngineer
   {
      [default] interface IDummyInterface;
   };
};
