///////////////////////////////////////////////////////////////////////
// PGSuperIE - PGSuper Import/Export Plug-in
// Copyright © 1999-2015  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This library is a part of the Washington Bridge Foundation Libraries
// and was developed as part of the Alternate Route Project
//
// This library is free software; you can redistribute it and/or modify it under
// the terms of the Alternate Route Library Open Source License as published by 
// the Washington State Department of Transportation, Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but is distributed 
// AS IS, WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
// or FITNESS FOR A PARTICULAR PURPOSE. See the Alternate Route Library Open Source 
// License for more details.
//
// You should have received a copy of the Alternate Route Library Open Source License 
// along with this program; if not, write to the Washington State Department of 
// Transportation, Bridge and Structures Office, P.O. Box  47340, 
// Olympia, WA 98503, USA or e-mail Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////
// The intent of licensing this interface with the ARLOSL is to provide
// third party developers a method of developing proprietary plug-ins
// to the software.
// 
// Any changes made to the interfaces defined in this file are
// are subject to the terms of the Alternate Route Library Open Source License.
//
// Components that implement the interfaces defined in this file are
// governed by the terms and conditions deemed appropriate by legal 
// copyright holder of said software.
///////////////////////////////////////////////////////////////////////
import "oaidl.idl";
import "ocidl.idl";

import "WBFLCore.idl";

cpp_quote("// {80D817C2-6E5D-4ffe-BAFC-F5B0A05B8112}")
cpp_quote("DEFINE_GUID(CATID_PGSuperProjectImporter,") 
cpp_quote("0x80d817c2, 0x6e5d, 0x4ffe, 0xba, 0xfc, 0xf5, 0xb0, 0xa0, 0x5b, 0x81, 0x12);")

cpp_quote("// {CF6FEC56-E107-4075-97D2-8DC80930D40A}")
cpp_quote("DEFINE_GUID(CATID_PGSuperDataImporter, ")
cpp_quote("0xcf6fec56, 0xe107, 0x4075, 0x97, 0xd2, 0x8d, 0xc8, 0x9, 0x30, 0xd4, 0xa);")

cpp_quote("// {4D284019-F81E-4e52-B32C-212FC305E33E}")
cpp_quote("DEFINE_GUID(CATID_PGSuperDataExporter, ")
cpp_quote("0x4d284019, 0xf81e, 0x4e52, 0xb3, 0x2c, 0x21, 0x2f, 0xc3, 0x5, 0xe3, 0x3e);")


[
   uuid(98B3DF17-7E0E-4d4a-B8A2-5443914FC608),
   pointer_default(unique)
]
interface IPGSuperDataImporter : IUnknown
{
   HRESULT Init(UINT nCmdID);
   HRESULT GetMenuText([out]BSTR*  bstrText);
   HRESULT GetBitmapHandle([out]HBITMAP* phBmp);
   HRESULT GetCommandHintText([out]BSTR*  bstrText);
   HRESULT Import([in]IBroker* pBroker);
};

[
   uuid(5DB8B1D3-C91D-4e62-81E6-A7B64B0D38FD),
   pointer_default(unique)
]
interface IPGSuperProjectImporter : IUnknown
{
   HRESULT GetItemText([out]BSTR* bstrText);
   HRESULT Import([in]IBroker* pBroker);
   HRESULT GetIcon([out] HICON* phIcon);
};

[
   uuid(BF6EC18A-43D2-4ea1-BC7F-54365DD645DA),
   pointer_default(unique)
]
interface IPGSuperDataExporter : IUnknown
{
   HRESULT Init(UINT nCmdID);
   HRESULT GetMenuText([out]BSTR*  bstrText);
   HRESULT GetBitmapHandle([out]HBITMAP* phBmp);
   HRESULT GetCommandHintText([out]BSTR*  bstrText);
   HRESULT Export([in]IBroker* pBroker);
};
