///////////////////////////////////////////////////////////////////////
// PGSuper - Prestressed Girder SUPERstructure Design and Analysis
// Copyright © 1999-2016  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////


// PGSuperLibrary.idl : IDL source for PGSuperLibrary.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (PGSuperLibrary.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(B9603863-5166-4c1c-BDD9-962819A48CC1),
	version(1.0),
	helpstring("PGSuperLibrary Library")
]
library PGSuperLibrary
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(E67716CF-F63C-472c-8FF9-3C959A736097),
		helpstring("LibraryAppPlugin Class")
	]
	coclass LibraryAppPlugin
	{
		interface IUnknown;
   };
};
