//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by psgLib.rc
//
#define ID_INDICATOR_MODIFIED           1
#define IDS_GIRDER_SHEET                1
#define ID_INDICATOR_STATUS             2
#define IDS_GIRDER_DIMENSIONS           2
#define IDS_GIRDER_MISC                 3
#define IDS_GIRDER_DIAPHRAGM            3
#define IDS_GIRDER_STRAND               4
#define IDS_GIRDER_LONG                 5
#define IDS_GIRDER_SHEAR                6
#define IDS_SPEC_CASTING_YARD           7
#define IDS_SPEC_BRIDGE_SITE            8
#define IDS_SPEC_DESCRIPTION            9
#define IDS_HAULING_ERECTION            10
#define IDS_SPEC_SHEET                  11
#define IDS_SPEC_CREEP                  12
#define IDS_SLOPE_O5_US                 13
#define IDS_SLOPE_O5_SI                 14
#define IDS_SLOPE_O6_US                 15
#define IDS_SLOPE_O6_SI                 16
#define IDS_SLOPE_O7_SI                 17
#define IDS_SLOPE_O7_US                 18
#define IDS_NWC_MESSAGE                 19
#define IDS_LWC_MESSAGE                 20
#define IDS_SPEC_STRAND                 27
#define IDS_SPEC_LOSS                   28
#define IDS_SPEC_ANALYSIS               29
#define IDS_GIRDER_HARPPOINT            30
#define IDD_SPEC_SHEAR_DESIGN           106
#define IDD_SHEAR_DESIGN                106
#define IDD_CONCRETE_ENTRY              129
#define IDD_TEST                        131
#define IDD_CONNECTION_ENTRY            132
#define IDB_GIRDER                      135
#define IDD_DIAPHRAGM_LAYOUT            136
#define IDD_STRAND_PATTERN              137
#define IDR_ADD_DELETE_POPUP            137
#define IDD_GIRDER_ERROR                138
#define IDD_SPEC_DESCR                  139
#define IDD_GIRDER_MAIN                 140
#define IDD_SPEC_BRIDGE_SITE            143
#define IDR_LIBRARYTYPE                 143
#define IDD_EDIT_SHEAR_STEEL            144
#define IDD_SPEC_CASTING_YARD           145
#define IDD_LONG_STEEL                  146
#define IDD_SPEC_HAULING_ERECTION       147
#define IDD_GIRDER_DIMENSIONS           148
#define IDD_SPEC_STRANDS                149
#define IDD_GIRDER_MISC                 150
#define IDR_LIBAPPPLUGIN                150
#define IDD_TRAFFIC_BARRIER             151
#define IDC_Y1_T                        151
#define IDB_Barrier                     152
#define IDD_SPEC_CREEP                  152
#define IDC_Y2_T                        152
#define IDC_Y3_T                        153
#define IDD_SPEC_LOSSES                 153
#define IDD_SPEC_LIFTING                154
#define IDD_STRAIGHT_STRAND             155
#define IDD_SPEC_BRIDGE_SITE2           156
#define IDD_SPEC_BRIDGE_SITE1           157
#define IDB_CONNECTION                  158
#define IDD_HARP_STRAND                 164
#define IDB_IN_USE                      164
#define IDB_IN_USE_AND_READ_ONLY        165
#define IDB_READ_ONLY                   166
#define IDI_CONCRETE_ENTRY              167
#define IDI_CONNECTION_ENTRY            168
#define IDI_GIRDER_ENTRY                169
#define IDI_SPECIFICATION_ENTRY         170
#define IDI_TRAFFIC_BARRIER_ENTRY       171
#define IDI_DIAPHRAGM_ENTRY             172
#define IDD_SECTIONVIEW                 173
#define IDD_LIVE_LOAD_ENTRY             174
#define IDD_LIBRARY_ENTRY_CONFLICT      175
#define IDD_RENAME_LIBRARY_ENTRY        176
#define IDI_LIVE_LOAD_ENTRY             176
#define IDD_SPEC_ANALYSIS               177
#define IDD_STRAND_DEFINITION           180
#define IDD_GIRDER_HARPPOINT            181
#define IDR_STRAIGHT_POPUP              183
#define IDD_GIRDER_DIAPHRAGM            183
#define IDD_INTERMEDATE_DIAPHRAGM       184
#define IDR_ADD_EDIT_DELETE_POPUP       184
#define IDD_SPEC_LIMITS                 186
#define IDD_SPEC_DESIGN                 189
#define IDD_SPEC_DEFLECTIONS            191
#define IDD_SPEC_SHEAR                  192
#define IDD_SPEC_MOMENT                 194
#define IDD_SPEC_DEBONDING              196
#define IDD_TRAFFICBARRIERVIEW          197
#define IDD_GIRDER_DEBOND_CRITERIA      198
#define IDI_DEFAULT_ENTRY               198
#define IDD_RATING_DESCR                199
#define IDI_FOLDER                      199
#define IDI_OPEN_FOLDER                 200
#define IDI_LIBRARY_MANAGER             201
#define IDI_RATING_ENTRY                202
#define IDI_ICON1                       203
#define IDD_STRAND_GENERATION           204
#define IDD_LIVE_LOAD_FACTORS           306
#define IDC_D1                          1001
#define IDC_W1                          1002
#define IDC_D2                          1003
#define IDC_DOWN_ADJUST                 1003
#define IDC_W2                          1004
#define IDC_BOTTOM_HEIGHT               1004
#define IDC_ACTIVEUNITCTRL1             1005
#define IDC_FC                          1005
#define IDC_END_DISTANCE                1005
#define IDC_D3                          1005
#define IDC_TOP_HEIGHT                  1005
#define IDC_X1                          1005
#define IDC_DS                          1006
#define IDC_BEARING_OFFSET              1006
#define IDC_ACTIVEUNITCTRL2             1006
#define IDC_W3                          1006
#define IDC_STRAND_COUNTER              1006
#define IDC_X2                          1006
#define IDC_ACTIVEUNITCTRL3             1007
#define IDC_DW                          1007
#define IDC_D4                          1007
#define IDC_MILD_STEEL_SELECTOR         1007
#define IDC_X3                          1007
#define IDC_ACTIVEUNITCTRL5             1008
#define IDC_AGG_SIZE                    1008
#define IDC_W4                          1008
#define IDC_X4                          1008
#define IDC_ACTIVEUNITCTRL4             1009
#define IDC_NAME                        1009
#define IDC_EDIT1                       1009
#define IDC_D5                          1009
#define IDC_SUPPORT_LOCATION            1009
#define IDC_HE_ERECTION_FS_CRACK        1009
#define IDC_DIST_TRAFFIC_BARRIER        1009
#define IDC_CREEP_FACTOR                1009
#define IDC_SHIPPING1                   1009
#define IDC_IMPACT_UPWARD_HAULING       1009
#define IDC_TF_SPACING                  1009
#define IDC_N                           1009
#define IDC_DEFLECTION_LIMIT            1009
#define IDC_SPLITTING_SPACING           1009
#define IDC_ACTIVEUNITCTRL23            1010
#define IDC_T1                          1010
#define IDC_Y1                          1010
#define IDC_BS_COMP_STRESS_SERV         1010
#define IDC_IMPACT_DOWNWARD_HAULING     1010
#define IDC_LWC_PHI                     1010
#define IDC_SPLITTING_ZL                1010
#define IDC_D6                          1011
#define IDC_DOWN_INC                    1011
#define IDC_DIAPHRAGM_GRID              1011
#define IDC_BS_COMP_STRESS_LLPERM2      1011
#define IDC_BS_COMP_STRESS_SERVICE1A    1011
#define IDC_X5                          1011
#define IDC_HPY                         1011
#define IDC_CONFINE_SPACING             1011
#define IDC_T2                          1012
#define IDC_UP_ADJUST                   1012
#define IDC_PICK_POINT_HEIGHT           1012
#define IDC_DIST_UTILITY                1012
#define IDC_Y2                          1012
#define IDC_GEX                         1012
#define IDC_CONFINE_ZL                  1012
#define IDC_UP_INC                      1013
#define IDC_D7                          1013
#define IDC_HE_HAULING_FS_CRACK         1013
#define IDC_BS_COMP_STRESS_SERVICE1B    1013
#define IDC_Y3                          1013
#define IDC_LIFTING_LOOP_TOLERANCE      1013
#define IDC_GEY                         1013
#define IDC_DRAW_GIRDER                 1014
#define IDC_NS_BOTTOM                   1014
#define IDC_INSERTROW                   1014
#define IDC_HE_HAULING_FS_ROLLOVER      1014
#define IDC_END_TOP_COVER               1014
#define IDC_REMOVEROWS                  1015
#define IDC_ROLL_STIFFNESS              1015
#define IDC_END_BOTTOM_COVER            1015
#define IDC_HEIGHT_GIRDER_BOTTOM        1016
#define IDC_APPEND_ROW                  1016
#define IDC_HP_INCREMENT                1016
#define IDC_INSERTHORIZROW              1016
#define IDC_EDIT2                       1017
#define IDC_ENTRY_NAME                  1017
#define IDC_ADD_HARPED_STRAND           1017
#define IDC_EDIT_DESCRIPTION            1017
#define IDC_NORMAL_MAX_MAX              1017
#define IDC_HOLD_DOWN_FORCE             1017
#define IDC_AXLE_SPACING                1017
#define IDC_CREEP_DURATION              1017
#define IDC_RELEASE                     1017
#define IDC_BEFORE_XFER                 1017
#define IDC_DIAPHRAGM_OFFSET            1017
#define IDC_CREEP_DURATION1             1017
#define IDC_CREEP_DURATION1_MIN         1017
#define IDC_H                           1017
#define IDC_GIRDER_FCI                  1017
#define IDC_MAX_STRANDS_PER_ROW         1017
#define IDC_NWC_GIRDER_FCI              1017
#define IDC_REMOVEHORIZROWS             1017
#define IDC_MAX_SPACING_CHG             1017
#define IDC_WEIGHT                      1018
#define IDC_DEL_HARPED_STRAND           1018
#define IDC_LONG_GRID                   1018
#define IDC_EXTREME_MAX_MAX             1018
#define IDC_MAX_STIRRUP_SPACING         1018
#define IDC_HEIGHT_ROLL_CENTER          1018
#define IDC_AFTER_XFER                  1018
#define IDC_CREEP_DURATION2             1018
#define IDC_CREEP_DURATION2_MIN         1018
#define IDC_LWC_GIRDER_FCI              1018
#define IDC_MAX_SHEARCAP_CHG            1018
#define IDC_HE_ROADWAY_SUPERELEVATION   1019
#define IDC_NORMAL_MAX_MAX2             1019
#define IDC_APPEND_HARPED_STRAND        1019
#define IDC_MAX_ZONELEN_BARS            1019
#define IDC_MIN_ZONELEN_BARS            1019
#define IDC_DEL_STRAIGHT_STRAND         1020
#define IDC_EXTREME_MAX_MAX2            1020
#define IDC_MAX_HAULING_SUPPORT_LENGTH  1020
#define IDC_ADD_HARPED_STRAND2          1020
#define IDC_EDIT_STRAND                 1020
#define IDC_NORMAL_MAX_MAX3             1020
#define IDC_MAX_ZONELEN_DIST            1020
#define IDC_MIN_ZONELEN_DIST            1020
#define IDC_SUPPORT_PLACEMENT_TOLERANCE 1021
#define IDC_DEL_TEMPORARY_STRAND        1021
#define IDC_DEL_HARPED_STRAND2          1021
#define IDC_MOVEUP_HARPED_STRAND        1021
#define IDC_CAMBER_CG_ADJUSTMENT        1022
#define IDC_APPEND_HARPED_STRAND2       1022
#define IDC_MOVEDOWN_HARPED_STRAND      1022
#define IDC_HARP_LOCATION               1023
#define IDC_HP_TOP_COVER                1023
#define IDC_HP_LSL                      1023
#define IDC_DIAPHRAGM_HEIGHT            1024
#define IDC_HP_BOTTOM_COVER             1024
#define IDC_HP_USL                      1024
#define IDC_EDIT                        1025
#define IDC_DIAPHRAGM_WIDTH             1025
#define IDC_HAULING_TENS_MAX            1025
#define IDC_SS_TOP_COVER                1025
#define IDC_LOOP_LOCATION               1026
#define IDC_FC_T                        1026
#define IDC_SS_BOTTOM_COVER             1026
#define IDC_LOOP_RANGE                  1027
#define IDC_DS_T                        1027
#define IDC_BEARING_OFFSET_T            1027
#define IDC_DW_T                        1028
#define IDC_DIAPHRAGM_HEIGHT_T          1028
#define IDC_X2_T                        1028
#define IDC_AGG_SIZE_T                  1029
#define IDC_DIAPHRAGM_WIDTH_T           1029
#define IDC_X3_T                        1029
#define IDC_END_DISTANCE_T              1030
#define IDC_X4_T                        1030
#define IDC_X5_T                        1031
#define IDC_STRAND_GRID                 1032
#define IDC_X1_T                        1032
#define IDC_HARP_STRAND_GRID            1033
#define IDC_W2_T                        1033
#define IDC_STRAIGHT_STRAND_GRID        1034
#define IDC_W3_T                        1034
#define IDC_LOOP_LOCATION_T             1034
#define IDC_HARP_STRAND_GRID2           1034
#define IDC_W4_T                        1035
#define IDC_LOOP_RANGE_T                1035
#define IDC_TEMPORARY_STRAND_GRID       1035
#define IDC_ENAME                       1036
#define IDC_SUPPORT_LOCATION_T          1036
#define IDC_NS_BOTTOM_SPIN              1037
#define IDC_T1_T                        1037
#define IDC_LAST_ZONE                   1038
#define IDC_T2_T                        1038
#define IDC_GIRDER_TAB                  1039
#define IDC_D1_T                        1039
#define IDC_LONG_STEEL_GRID             1040
#define IDC_D2_T                        1040
#define IDC_SHEAR_STEEL                 1041
#define IDC_SHEAR_GRID                  1041
#define IDC_D3_T                        1041
#define IDC_STIRRUP_DESIGN_OVERRIDE     1042
#define IDC_D4_T                        1042
#define IDC_HORIZ_GRID                  1042
#define IDC_D5_T                        1043
#define IDC_BAR_SIZE                    1044
#define IDC_D6_T                        1044
#define IDC_SPLITTING_NLEGS             1044
#define IDC_D7_T                        1045
#define IDC_TF_BAR_SIZE                 1045
#define IDC_SPLITTING_BAR_SIZE          1045
#define IDC_W1_T                        1046
#define IDC_BOTTOM_HEIGHT_T             1046
#define IDC_TF_BAR_SIZE2                1046
#define IDC_CONFINE_BAR_SIZE            1046
#define IDC_TOP_HEIGHT_T                1047
#define IDC_UP_INC_T                    1048
#define IDC_UP_ADJUST_T                 1049
#define IDC_END_TOP_COVER_T             1049
#define IDC_DOWN_ADJUST_T               1050
#define IDC_END_BOTTOM_COVER_T          1050
#define IDC_DOWN_INC_T                  1051
#define IDC_HP_INCREMENT_T              1052
#define IDC_HP_TOP_COVER_T              1053
#define IDC_HP_LSL_T                    1053
#define IDC_HP_BOTTOM_COVER_T           1054
#define IDC_HP_USL_T                    1054
#define IDC_SS_TOP_COVER_T              1055
#define IDC_SS_BOTTOM_COVER_T           1056
#define IDC_CHECK_NORMAL_MAX_MAX        1058
#define IDC_NORMAL_MAX_SQRT             1059
#define IDC_NORMAL_MAX_SQRT_UNITS       1060
#define IDC_NORMAL_MAX_MAX_UNITS        1061
#define IDC_NORMAL_MAX_SQRT_UNITS3      1061
#define IDC_EXTREME_MAX_SQRT            1062
#define IDC_HOLD_DOWN_FORCE_UNITS       1062
#define IDC_EXTREME_MAX_SQRT_UNITS      1063
#define IDC_MAX_STIRRUP_SPACING_UNITS   1063
#define IDC_PICK_POINT_HEIGHT_UNITS     1064
#define IDC_CHECK_EXTREME_MAX_MAX       1064
#define IDC_EXTREME_MAX_MAX_UNITS       1065
#define IDC_CHECK_HOLD_DOWN             1065
#define IDC_ROLL_STIFFNESS_UNITS        1065
#define IDC_LIFTING_LOOP_TOLERANCE_UNITS 1065
#define IDC_EXTREME_MAX_SQRT2           1066
#define IDC_HEIGHT_GIRDER_BOTTOM_UNITS  1067
#define IDC_CHECK_EXTREME_MAX_MAX2      1067
#define IDC_AXLE_SPACING_UNITS          1068
#define IDC_EXTREME_MAX_SQRT_UNITS2     1068
#define IDC_HEIGHT_ROLL_CENTER_UNITS    1069
#define IDC_EXTREME_MAX_MAX_UNITS2      1069
#define IDC_MAX_HAULING_SUPPORT_LENGTH_UNITS 1070
#define IDC_SUPPORT_PLACEMENT_TOLERANCE_UNITS 1071
#define IDC_PS_BEFORE_TRANSFER_SR       1072
#define IDC_AXLE_SPACING_UNITS4         1072
#define IDC_PS_BEFORE_TRANSFER_LR       1073
#define IDC_AXLE_SPACING_UNITS5         1073
#define IDC_CHECK_PS_AFTER_TRANSFER     1074
#define IDC_PS_AFTER_TRANSFER_SR        1075
#define IDC_PS_AFTER_TRANSFER_LR        1076
#define IDC_CHECK_STRAND_SLOPE          1077
#define IDC_STRAND_SLOPE_05             1078
#define IDC_STRAND_SLOPE_06             1079
#define IDC_FS_CY_CRACK                 1080
#define IDC_STRAND_SLOPE_07             1080
#define IDC_FS_CY_FAIL                  1081
#define IDC_GIRDER_SWEEP_TOL            1082
#define IDC_CY_ALLOW_SERVICE_COMP       1083
#define IDC_CY_ALLOW_HANDLING_COMP      1084
#define IDC_TEMP_REMOVE_ALLOW_SERVICE_COMP 1084
#define IDC_PS_AT_JACKING_SR            1085
#define IDC_MIN_CABLE_ANGLE             1085
#define IDC_PS_AT_JACKING_LR            1086
#define IDC_HE_COMP_STRESS_HANDLING     1088
#define IDC_PS_AFTER_LOSSES_SR          1088
#define IDC_PS_AFTER_ALL_LOSSES_SR      1088
#define IDC_HE_ERECTION_FS_FAIL         1089
#define IDC_PS_AFTER_LOSSES_LR          1089
#define IDC_PS_AFTER_ALL_LOSSES_LR      1089
#define IDC_STATIC_SLOPE_05             1091
#define IDC_STATIC_SLOPE_06             1092
#define IDC_STATIC_SLOPE_07             1093
#define IDC_DIST_TRAFFIC_BARRIER_SPIN   1094
#define IDC_DIST_UTILITY_SPIN           1095
#define IDC_HE_ROADWAY_SUPERELEVATION_UNITS 1095
#define IDC_CHECK_PS_AT_JACKING         1096
#define IDC_CHECK_PS_BEFORE_TRANSFER    1097
#define IDC_NORMAL_MAX_SQRT2            1099
#define IDC_NORMAL_MAX_SQRT_UNITS2      1100
#define IDC_NORMAL_MAX_SQRT3            1100
#define IDC_CHECK_NORMAL_MAX_MAX2       1101
#define IDC_NORMAL_MAX_MAX_UNITS2       1102
#define IDC_CREEP_DURATION_TAG          1103
#define IDC_CREEP_DURATION1_TAG         1103
#define IDC_CHECK_NORMAL_MAX_MAX3       1103
#define IDC_XFER_TIME                   1104
#define IDC_NORMAL_MAX_MAX_UNITS3       1104
#define IDC_CREEP_DURATION2_TAG         1105
#define IDC_XFER_TIME_TAG               1106
#define IDC_CREEP_METHOD                1107
#define IDC_RADIO2                      1108
#define IDC_CURING_METHOD               1110
#define IDC_FINAL                       1112
#define IDC_SHIPPING1_TAG               1113
#define IDC_BEFORE_TEMP_STRAND_REMOVAL  1113
#define IDC_RELEASE_TAG                 1114
#define IDC_BEFORE_XFER_TAG             1114
#define IDC_SHIPPING2                   1115
#define IDC_SHIPPING2_TAG               1116
#define IDC_FINAL_TAG                   1117
#define IDC_LIFTING                     1118
#define IDC_CREEP_METHOD2               1119
#define IDC_AFTER_XFER_TAG              1119
#define IDC_CREEP_FACTOR_TITLE          1120
#define IDC_SHIPPING3                   1120
#define IDC_LIFTING_TAG                 1120
#define IDC_MIN_CABLE_ANGLE_UNITS       1121
#define IDC_SHIPPING3_TAG               1121
#define IDC_BEFORE_TEMP_STRAND_REMOVAL_TAG 1121
#define IDC_HAULING_ALLOW_COMP          1122
#define IDC_SHIPPING4                   1122
#define IDC_AFTER_TEMP_STRAND_REMOVAL   1122
#define IDC_HAULING_MAX_TENSSQRT        1123
#define IDC_SHIPPING4_TAG               1123
#define IDC_AFTER_TEMP_STRAND_REMOVAL_TAG 1123
#define IDC_CHECK_HAULING_TENS_MAX      1124
#define IDC_AFTER_DECK_PLACEMENT        1124
#define IDC_HAULING_TENS_MAX_UNITS      1125
#define IDC_AFTER_DECK_PLACEMENT_TAG    1125
#define IDC_CY_ALLOW_LIFTING_COMP       1126
#define IDC_HAULING_MAX_TENSSQRT2       1126
#define IDC_AFTER_SIDL                  1126
#define IDC_LIFTING_NORMAL_MAX_SQRT     1127
#define IDC_AFTER_DECK_PLACEMENT_TAG2   1127
#define IDC_AFTER_SIDL_TAG              1127
#define IDC_LIFTING_NORMAL_MAX_SQRT_UNITS 1128
#define IDC_CHECK_LIFTING_NORMAL_MAX_MAX 1129
#define IDC_LIFTING_NORMAL_MAX_MAX      1130
#define IDC_LIFTING_NORMAL_MAX_MAX_UNITS 1131
#define IDC_HAULING_MAX_TENSSQRT_UNITS  1132
#define IDC_LIFTING_NORMAL_MAX_SQRT_UNITS2 1132
#define IDC_IMPACT_UPWARD_LIFTING       1133
#define IDC_IMPACT_DOWNWARD_LIFTING     1134
#define IDC_CYS_TENS_BYLINE             1135
#define IDC_LIFTING_NORMAL_MAX_SQRT2    1135
#define IDC_LIFT_TENS                   1136
#define IDC_CYS_TENS_BYLINE2            1136
#define IDC_HAUL_TENS                   1137
#define IDC_LIFT_TENS2                  1137
#define IDC_BS_NORMAL_TENS              1138
#define IDC_HAUL_TENS2                  1138
#define IDC_BS_EXTREME_TENS             1139
#define IDC_ADD_STRAIGHT_STRAND         1142
#define IDC_APPEND_STRAIGHT_STRAND      1143
#define IDC_ADD_TEMPORARY_STRAND        1144
#define IDC_APPLY_DR_TO_BEAM            1144
#define IDC_APPEND_TEMPORARY_STRAND     1145
#define IDC_APPLY_DR_TO_BEARING         1145
#define IDC_APPLY_DR_TO_BEARING2        1146
#define IDC_DONT_APPLY                  1146
#define IDC_DIAPHRAGM_OFFSET_UNITS      1147
#define IDC_CONNECTION_MF               1148
#define IDC_GIRDER_MF                   1149
#define IDC_TRAFFIC_BARRIER             1150
#define IDC_TF_SPACING_UNITS            1151
#define IDC_SPLITTING_SPACING_UNIT      1151
#define IDC_CHECK_MAX_MAX               1152
#define IDC_SPLITTING_ZL_UNIT           1152
#define IDC_MAXWGT                      1153
#define IDC_CONFINE_SPACING_UNIT        1153
#define IDC_MAXWGT_UNITS                1154
#define IDC_CONFINE_ZL_UNIT             1154
#define IDC_BEAMTYPES                   1155
#define IDC_DIMENSIONS                  1156
#define IDC_ODD_STRANDS                 1157
#define IDC_CHECK_PS_AFTER_ALL_LOSSES   1164
#define IDC_LOSS_METHOD                 1165
#define IDC_SHIPPING_LOSS_METHOD        1166
#define IDC_SHIPPING_LABEL              1167
#define IDC_SHIPPING                    1168
#define IDC_BEFORE_XFER_LABEL           1169
#define IDC_AFTER_XFER_LABEL            1170
#define IDC_RENAME_ENTRY                1170
#define IDC_SHIPPING2_LABEL             1171
#define IDC_ENTRY_TEXT                  1171
#define IDC_FINAL_LABEL                 1172
#define IDC_OVERWRITE                   1172
#define IDC_SHIPPING_TAG                1173
#define IDC_HARP_LOCATION_TAG           1174
#define IDC_LIFTING_LABEL               1174
#define IDC_BEFORE_TEMP_STRAND_REMOVAL_LABEL 1175
#define IDC_FRACTIONAL                  1176
#define IDC_AFTER_TEMP_STRAND_REMOVAL_LABEL 1176
#define IDC_ABSOLUTE                    1177
#define IDC_AFTER_DECK_PLACEMENT_LABEL  1177
#define IDC_LLDF                        1178
#define IDC_AFTER_SIDL_LABEL            1178
#define IDC_SHEAR_CAPACITY              1181
#define IDC_LRSH                        1182
#define IDC_CONFLICT_TOP                1182
#define IDC_LL_DEFLECTION               1183
#define IDC_CONFLICT_BOTTOM             1183
#define IDC_LL_DEF_STATIC               1184
#define IDC_VIEWSECTION                 1185
#define IDC_DRAW                        1186
#define IDC_VIEWSECTION_MID             1186
#define IDC_HS                          1187
#define IDC_SS                          1188
#define IDC_TS                          1189
#define IDC_SHOWS                       1190
#define IDC_MOMENT                      1191
#define IDC_DB                          1191
#define IDC_LUMPSUM_METHOD              1192
#define IDC_CONFIG_TYPE                 1192
#define IDC_AXLE_WEIGHT                 1193
#define IDC_LANE_LOAD                   1193
#define IDC_AXLE_WEIGHT_UNITS           1194
#define IDC_AXLE_STIFFNESS              1195
#define IDC_ADD                         1195
#define IDC_PERAXLE_METHOD              1196
#define IDC_DELETE                      1196
#define IDC_AXLE_STIFFNESS_UNITS        1197
#define IDC_AXLES_GRID                  1197
#define IDC_ADD2                        1197
#define IDC_SPEC_UNITS_SI               1198
#define IDC_MIN_ROLL_STIFFNESS          1198
#define IDC_CHECK_NOTIONAL              1198
#define IDC_DELETE2                     1198
#define IDC_SPEC_UNITS_US               1199
#define IDC_MIN_ROLL_STIFFNESS_UNITS    1199
#define IDC_LANE_LOAD_UNITS             1199
#define IDC_MAXOVERHANG                 1200
#define IDC_STATIC_GRID                 1200
#define IDC_MAXOVERHANG_UNITS           1201
#define IDC_HPREFERENCE                 1202
#define IDC_CREEP_DURATION1_MAX         1205
#define IDC_CREEP_DURATION2_MAX         1206
#define IDC_NC_CREEP                    1207
#define IDC_NC_CREEP_TAG                1208
#define IDC_SPECIFICATION               1209
#define IDC_K1                          1210
#define IDC_EC_K1                       1210
#define IDC_MAX_DEBOND                  1211
#define IDC_EC_K2                       1211
#define IDC_MAX_DEBOND_PER_ROW          1212
#define IDC_CREEP_K1                    1212
#define IDC_MAXDEBOND                   1213
#define IDC_CREEP_K2                    1213
#define IDC_FRAMAXDEBOND                1214
#define IDC_SHRINKAGE_K1                1214
#define IDC_DEBOND                      1215
#define IDC_SHRINKAGE_K2                1215
#define IDC_DEFAULT_DEBOND              1216
#define IDC_DEFAULT_DEBOND_UNITS        1217
#define IDC_STIRRUPS_ENGAGE_DECK        1218
#define IDC_SYMMETRICAL                 1218
#define IDC_INCLUDE_REBAR_SHEAR         1219
#define IDC_INCLUDE_REBAR_MOMENT        1220
#define IDC_ANALYSIS                    1221
#define IDC_USE_DIFF_GRID               1222
#define IDC_ALLOW_END_ADJUST            1223
#define IDC_ALLOW_HP_ADJUST             1224
#define IDC_END_INCREMENT               1225
#define IDC_END_INCREMENT_T             1226
#define IDC_STRESS_DESIGN               1227
#define IDC_END_LSL                     1227
#define IDC_STRAND_TYPE                 1228
#define IDC_STATIC_END                  1228
#define IDC_END_LSL_T                   1229
#define IDC_FILL_ORDER                  1230
#define IDC_END_USL                     1230
#define IDC_HPX                         1231
#define IDC_END_USL_T                   1231
#define IDC_HPX_T                       1232
#define IDC_HPY_T                       1233
#define IDC_GEX_T                       1234
#define IDC_GEY_T                       1235
#define IDC_HS_BOX                      1236
#define IDC_HS_TXT                      1237
#define IDC_HS_XT                       1238
#define IDC_HS_YT                       1239
#define IDC_HP_INCREMENT_S              1240
#define IDC_END_INCREMENT_S             1241
#define IDC_FR                          1242
#define IDC_FR_UNIT                     1243
#define IDC_FR_LABEL                    1244
#define IDC_FR2                         1244
#define IDC_MEASURE                     1245
#define IDC_BEARING_OFFSET_MEASURE      1245
#define IDC_MINIMUM                     1246
#define IDC_END_DISTANCE_MEASURE        1246
#define IDC_MIN_HP                      1247
#define IDC_MIN_HP_UNIT                 1248
#define IDC_L                           1249
#define IDC_MOD_E                       1250
#define IDC_EC                          1251
#define IDC_EC_T                        1252
#define IDC_DESCRIPTION                 1253
#define IDC_THICKNESS                   1254
#define IDC_TYPE                        1255
#define IDC_CONSTRUCTION                1256
#define IDC_MEASUREMENT_TYPE            1257
#define IDC_MEASURED_FROM               1258
#define IDC_LOCATION                    1259
#define IDC_LOWER_VEHICLE_WEIGHT        1259
#define IDC_LOCATION_UNIT               1260
#define IDC_H_UNIT                      1261
#define IDC_THICKNESS_UNIT              1262
#define IDC_BUTTON1                     1263
#define IDC_VIEW                        1263
#define IDC_ENDVIEW                     1263
#define IDC_RESTORE_DEFAULTS            1263
#define IDC_SPAN1                       1267
#define IDC_SPAN2                       1268
#define IDC_SPAN_UNIT                   1269
#define IDC_FC_SLAB                     1270
#define IDC_SPAN3                       1270
#define IDC_NWC_FC_SLAB                 1270
#define IDC_FC_SLAB_UNIT                1271
#define IDC_NWC_FC_SLAB_UNIT            1271
#define IDC_GIRDER_FCI_UNIT             1272
#define IDC_NWC_GIRDER_FCI_UNIT         1272
#define IDC_GIRDER_FC                   1273
#define IDC_NWC_GIRDER_FC               1273
#define IDC_GIRDER_FC_UNIT              1274
#define IDC_NWC_GIRDER_FC_UNIT          1274
#define IDC_UNIT_WEIGHT                 1275
#define IDC_NWC_UNIT_WEIGHT             1275
#define IDC_UNIT_WEIGHT_UNIT            1276
#define IDC_NWC_UNIT_WEIGHT_UNIT        1276
#define IDC_LWC_FC_SLAB                 1277
#define IDC_LWC_FC_SLAB_UNIT            1278
#define IDC_AGG_SIZE_UNIT               1279
#define IDC_NWC_AGG_SIZE_UNIT           1279
#define IDC_CHECK_ENABLE_LIFTING        1280
#define IDC_LWC_GIRDER_FCI_UNIT         1280
#define IDC_STATIC_LP                   1281
#define IDC_LWC_GIRDER_FC               1281
#define IDC_STATIC_FS                   1282
#define IDC_LWC_GIRDER_FC_UNIT          1282
#define IDC_STATIC_MFSC                 1283
#define IDC_LWC_UNIT_WEIGHT             1283
#define IDC_STATIC_MFSF                 1284
#define IDC_LWC_UNIT_WEIGHT_UNIT        1284
#define IDC_STATIC_LCY                  1285
#define IDC_NWC_AGG_SIZE_UNIT2          1285
#define IDC_LWC_AGG_SIZE_UNIT           1285
#define IDC_STATIC_LCYUP                1286
#define IDC_STATIC_ACS                  1288
#define IDC_STATIC_ACSCS                1289
#define IDC_STATIC_ACSTS                1290
#define IDC_STATIC_ACSSB                1291
#define IDC_STATIC_LCYDOWN              1292
#define IDC_STATIC_LCP                  1293
#define IDC_STATIC_LCPHPP               1294
#define IDC_STATIC_LCPLPT               1295
#define IDC_STATIC_LCP_ST               1296
#define IDC_STATIC_LCPLL                1297
#define IDC_STATIC_LCP_INC              1298
#define IDC_CHECK_ENABLE_HAULING        1299
#define IDC_STATIC_GH1                  1300
#define IDC_STATIC_GH2                  1301
#define IDC_STATIC_GH3                  1302
#define IDC_STATIC_GH4                  1303
#define IDC_STATIC_GH5                  1304
#define IDC_STATIC_GH6                  1305
#define IDC_STATIC_GH7                  1306
#define IDC_STATIC_GH8                  1307
#define IDC_STATIC_GH9                  1308
#define IDC_METHOD1                     1309
#define IDC_STATIC_GH10                 1309
#define IDC_METHOD2                     1310
#define IDC_STATIC_GH11                 1310
#define IDC_METHOD3                     1311
#define IDC_STATIC_GH12                 1311
#define IDC_METHOD4                     1312
#define IDC_STATIC_GH13                 1312
#define IDC_METHOD5                     1313
#define IDC_STATIC_GH14                 1313
#define IDC_STATIC_GH15                 1314
#define IDC_STATIC_GH16                 1315
#define IDC_STATIC_GH17                 1316
#define IDC_STATIC_GH18                 1317
#define IDC_STATIC_GH19                 1318
#define IDC_STATIC_GH20                 1319
#define IDC_STATIC_GH21                 1320
#define IDC_STATIC_GH22                 1321
#define IDC_STATIC_GH23                 1322
#define IDC_STATIC_GH24                 1323
#define IDC_STATIC_GH25                 1324
#define IDC_STATIC_GH26                 1325
#define IDC_FR_SQRT                     1327
#define IDC_ALWC_FR_SQRT                1328
#define IDC_APPROXIMATE_SHIPPING_TIME_NOTE 1329
#define IDC_SLWC_FR_SQRT                1329
#define IDC_ALWC_FR_SQRT2               1329
#define IDC_SHIPPING_TIME_LABEL         1330
#define IDC_SHIPPING_TIME               1331
#define IDC_SHIPPING_TIME_TAG           1332
#define IDC_COMBO_HP_LSL                1333
#define IDC_COMBO_END_LSL               1334
#define IDC_COMBO_HP_USL                1335
#define IDC_COMBO_END_USL               1336
#define IDC_HP_LSL_S                    1337
#define IDC_HP_USL_S                    1338
#define IDC_END_LSL_S                   1339
#define IDC_END_USL_S                   1340
#define IDC_CHECK_A                     1343
#define IDC_DESIGN_A                    1344
#define IDC_CHECK_LIFTING               1345
#define IDC_DESIGN_LIFTING              1346
#define IDC_CHECK_HAULING               1347
#define IDC_DESIGN_HAULING              1348
#define IDC_CHECK_HD                    1349
#define IDC_DESIGN_HD                   1350
#define IDC_CHECK_SLOPE                 1351
#define IDC_DESIGN_SLOPE                1352
#define IDC_RADIO_FILL_PERMANENT        1353
#define IDC_FR_STATIC                   1354
#define IDC_CHECK_ANCHORAGE             1354
#define IDC_ENABLE_NOTE                 1356
#define IDC_LIFTING_NOTE                1357
#define IDC_SS_NOTE                     1358
#define IDC_HD_NOTE                     1359
#define IDC_EFF_FLANGE_WIDTH            1359
#define IDC_TRIB_WIDTH                  1360
#define IDC_EFF_FLANGE_WIDTH2           1360
#define IDC_OVERLAY_DISTR               1360
#define IDC_SLABOFFSET                  1361
#define IDC_SHEAR_FLOW_METHOD           1362
#define IDC_WEIGHT_METHOD               1363
#define IDC_WEIGHT_UNIT                 1364
#define IDC_CURING_TIME_FACTOR          1365
#define IDC_WEIGHT_UNIT2                1365
#define IDC_EC_UNIT                     1365
#define IDC_ANCHORSET                   1367
#define IDC_WOBBLE                      1368
#define IDC_FRICTION                    1369
#define IDC_WOBBLE_TAG                  1370
#define IDC_ANCHORSET_TAG               1371
#define IDC_MIN_TRUCK_SUPPORT           1372
#define IDC_MIN_TRUCK_SUPPORT_UNIT      1373
#define IDC_TRUCK_SUPPORT_LOCATION_ACCURACY 1374
#define IDC_TRUCK_SUPPORT_LOCATION_ACCURACY_UNIT 1375
#define IDC_MIN_LIFTING_POINT           1376
#define IDC_MIN_LIFTING_POINT_UNIT      1377
#define IDC_LIFTING_POINT_LOCATION_ACCURACY 1378
#define IDC_LIFTING_POINT_LOCATION_ACCURACY_UNIT 1379
#define IDC_CONFIGURATION               1383
#define IDC_H1                          1384
#define IDC_H2                          1385
#define IDC_H1_UNIT                     1386
#define IDC_H2_UNIT                     1387
#define IDC_W                           1388
#define IDC_W_UNIT                      1389
#define IDC_TB_POINTS                   1392
#define IDC_PB_POINTS                   1393
#define IDC_SECTION_PROPERTIES          1393
#define IDC_SUPPORT_WIDTH               1394
#define IDC_SUPPORT_WIDTH_T             1395
#define IDC_GROUP_DESIGN                1398
#define IDC_MIN_TRUCK_SUPPORT_LABEL     1399
#define IDC_TRUCK_SUPPORT_LOCATION_ACCURACY_LABEL 1400
#define IDC_LRFD_1994                   1401
#define IDC_MIN_LIFTING_POINT_LABEL     1401
#define IDC_LRFD_1996                   1402
#define IDC_LIFTING_POINT_LOCATION_ACCURACY_LABEL 1402
#define IDC_LRFD_1997                   1403
#define IDC_LIFTING_DESIGN_GROUP        1403
#define IDC_LRFD_1998                   1404
#define IDC_LOSSES_NOTE                 1404
#define IDC_LRFD_1999                   1405
#define IDC_CONTINOUOUS_BARRIER         1405
#define IDC_LRFD_2000                   1406
#define IDC_IGNORE                      1406
#define IDC_LRFD_2001                   1407
#define IDC_ALLOW_DEBONDING             1407
#define IDC_LRFD_2002                   1408
#define IDC_MIDVIEW                     1408
#define IDC_LRFD_2003                   1409
#define IDC_SS_STATUS                   1409
#define IDC_LRFD_2004                   1410
#define IDC_DB_STATUS                   1410
#define IDC_HS_STATUS                   1411
#define IDC_TT_STATUS                   1412
#define IDC_MAX_NUM_PER_SECTION         1413
#define IDC_MAX_FRACTION_PER_SECTION    1414
#define IDC_CHECK_MAX_LENGTH_FRACTION   1415
#define IDC_MAX_LENGTH_FRACTION         1416
#define IDC_CHECK_MAX_LENGTH            1417
#define IDC_MAX_LENGTH                  1418
#define IDC_MIN_DISTANCE                1420
#define IDC_DEFAULT_DISTANCE            1421
#define IDC_MAX_TOTAL_STRANDS           1422
#define IDC_MAX_LENGTH_UNIT             1423
#define IDC_LL_METHOD                   1423
#define IDC_MIN_DISTANCE_UNIT           1424
#define IDC_DEFAULT_DISTANCE_UNIT       1425
#define IDC_CURBOFFSET                  1426
#define IDC_CURBOFFSET_UNIT             1427
#define IDC_UP                          1428
#define IDC_DOWN                        1429
#define IDC_MAXGIRDERANGLE              1430
#define IDC_MAXGIRDERANGLE_UNIT         1431
#define IDC_GIRDERSTIFFNESSRATIO        1432
#define IDC_GIRDER_SPACING_LOCATION     1433
#define IDC_LANESBEAMS                  1434
#define IDC_COMBO_TRANSFER              1435
#define IDC_PED_LIVE_LOAD               1435
#define IDC_ANCHORAGE_NOTE              1436
#define IDC_ANCHORAGE_DISABLED          1436
#define IDC_PED_LIVE_LOAD_UNIT          1436
#define IDC_REVERSE_HARPED_STRAND_ORDER 1437
#define IDC_MIN_SIDEWALK_WIDTH          1437
#define IDC_FATIGUE_LABEL               1438
#define IDC_WEIGHT_LABEL                1439
#define IDC_MIN_SIDEWALK_WIDTH_UNIT     1439
#define IDC_EC_LABEL                    1440
#define IDC_COMBO1                      1441
#define IDC_USAGE                       1441
#define IDC_STRAND_GENERATION           1441
#define IDC_METHOD                      1441
#define IDC_CONCRETE_TYPE               1441
#define IDC_LONG_REINF_SHEAR_METHOD     1441
#define IDC_RELAXATION_LOSS_METHOD      1441
#define IDC_WEB_STRAND_TYPE_COMBO       1441
#define IDC_DIST_TRAFFIC_BARRIER_BASIS  1442
#define IDC_NWC_NOTE                    1443
#define IDC_CHECK1                      1444
#define IDC_ALWAYS_RATE                 1444
#define IDC_IS_VARIABLE_AXLE_TRUCK      1444
#define IDC_HAS_AGG_STRENGTH            1444
#define IDC_STRAND_EXTENSIONS           1444
#define IDC_CHECK_SPLITTING             1444
#define IDC_TOP_FLANGE_ROUGHENED        1444
#define IDC_BRIDGE_LENGTH               1445
#define IDC_EXTEND_DECK_BARS            1445
#define IDC_DESIGN_SPLITTING            1445
#define IDC_BRIDGE_LENGTH_UNITS         1446
#define IDC_USER_OVERRIDE               1446
#define IDC_ROUGHENED                   1446
#define IDC_BARS_PROVIDE_SPLITTING      1446
#define IDC_CHECK_CONFINEMENT           1446
#define IDC_LANE_LOAD_LABEL             1447
#define IDC_BARS_PROVIDE_CONFINEMENT    1447
#define IDC_DESIGN_SPLITTING2           1447
#define IDC_DESIGN_CONFINEMENT          1447
#define IDC_BRIDGE_LENGTH_LABEL         1448
#define IDC_AXLE_LIST                   1449
#define IDC_VARIABLE_AXLE_SPACING       1450
#define IDC_VARIABLE_AXLE_SPACING_UNITS 1451
#define IDC_AXLE_LIST_LABEL             1452
#define IDC_LF_SERVICE_1_LABEL          1453
#define IDC_LF_SERVICE_1                1454
#define IDC_LF_SERVICE_2_LABEL          1455
#define IDC_GENERATE                    1455
#define IDC_LF_SERVICE_2                1456
#define IDC_LF_SERVICE_3_LABEL          1457
#define IDC_START_X                     1457
#define IDS_CONFLICT_TOP_IMPORT         1458
#define IDC_LF_SERVICE_3                1458
#define IDC_START_X_UNIT                1458
#define IDS_CONFLICT_TOP_MASTER         1459
#define IDC_LF_SERVICE_3_LABEL2         1459
#define IDC_LF_SERVICE_4_LABEL          1459
#define IDC_START_Y                     1459
#define IDC_LF_SERVICE_4                1460
#define IDC_START_Y_UNIT                1460
#define IDC_END_X                       1461
#define IDC_END_X_UNIT                  1462
#define IDC_END_Y                       1463
#define IDC_END_Y_UNIT                  1464
#define IDC_NSTRANDS_X                  1465
#define IDC_NSTRANDS_Y                  1466
#define IDC_LAYOUT                      1467
#define IDC_END_LABEL                   1468
#define IDC_START_LABEL                 1469
#define IDC_SCHEMATIC                   1470
#define IDC_GROUP1                      1471
#define IDC_START_LABEL2                1472
#define IDC_START_X2                    1473
#define IDC_START_X_UNIT2               1474
#define IDC_START_Y2                    1475
#define IDC_START_Y_UNIT2               1476
#define IDC_HEADING                     1477
#define IDC_END_LABEL2                  1478
#define IDC_END_X2                      1479
#define IDC_END_X_UNIT2                 1480
#define IDC_END_Y2                      1481
#define IDC_END_Y_UNIT2                 1482
#define IDC_HEADING2                    1483
#define IDC_GROUP2                      1484
#define IDC_X_LABEL                     1485
#define IDC_Y_LABEL                     1486
#define IDC_X_LABEL2                    1487
#define IDC_Y_LABEL2                    1488
#define IDC_BUTTON2                     1489
#define IDC_HEIGHT_LABEL                1491
#define IDC_THICKNESS_LABEL             1492
#define IDC_AGG_STRENGTH                1493
#define IDC_AGG_STRENGTH_T              1494
#define IDC_NWC_FR_LABEL                1495
#define IDC_SLWC_FR_LABEL               1496
#define IDC_FR_HEADING                  1497
#define IDS_CONFLICT_BOTTOM_MASTER      1498
#define IDC_SLWC_FR                     1498
#define IDS_CONFLICT_BOTTOM_IMPORT      1499
#define IDC_SLWC_FR_UNIT                1499
#define IDC_FR_LABEL_SLWC               1500
#define IDC_ALWC_FR_LABEL               1501
#define IDC_NWC_FR_TXT                  1502
#define IDC_ALWC_FR_UNIT                1503
#define IDC_FR_LABEL_ALWC               1504
#define IDC_SLWC_FR_TXT                 1504
#define IDC_ALWC_FR_TXT                 1505
#define IDC_PHI_GROUP                   1506
#define IDC_PHI_NWC_HEADER              1507
#define IDC_NWC_PHI_TENSION_RC          1508
#define IDC_NWC_PHI_TENSION_RC_LABEL    1509
#define IDC_NWC_PHI_COMPRESSION         1510
#define IDC_NWC_PHI                     1510
#define IDC_NWC_PHI_COMPRESSION_LABEL   1511
#define IDC_EC_K1_LABEL                 1511
#define IDC_PHI_LWC_HEADER              1512
#define IDC_EC_K2_LABEL                 1512
#define IDC_NWC_AGG_SIZE                1512
#define IDC_LWC_PHI_TENSION_RC          1513
#define IDC_CREEP_K1_LABEL              1513
#define IDC_LWC_AGG_SIZE                1513
#define IDC_BARS_LEGS_GRID              1513
#define IDC_LWC_PHI_TENSION_RC_LABEL    1514
#define IDC_CREEP_K2_LABEL              1514
#define IDC_EDIT_BAR_SPACINGS           1514
#define IDC_LWC_PHI_COMPRESSION         1515
#define IDC_SHRINKAGE_K1_LABEL          1515
#define IDC_EDIT_BAR_SPACINGS_UNIT      1515
#define IDC_LWC_PHI_COMPRESSION_LABEL   1516
#define IDC_SHRINKAGE_K2_LABEL          1516
#define IDC_MAX_SPACING_CHG_UNIT        1516
#define IDC_EG_SLAB                     1516
#define IDC_NWC_PHI_TENSION_PS          1517
#define IDC_MAX_SHEARCAP_CHG_UNIT       1517
#define IDC_EG_SLAB_UNIT                1517
#define IDC_NWC_PHI_TENSION_PS_LABEL    1518
#define IDC_MAX_ZONELEN_DIST_UNIT       1518
#define IDC_MIN_ZONELEN_DIST_UNIT       1518
#define IDC_EG_SLAB_LABEL               1518
#define IDC_LWC_PHI_TENSION_PS          1519
#define IDC_EG_SLABPAD                  1519
#define IDC_LWC_PHI_TENSION_PS_LABEL    1520
#define IDC_EG_SLABPAD_UNIT             1520
#define IDC_NEG_MOMENT                  1521
#define IDC_EG_SLABPAD_LABEL            1521
#define IDC_EG_DIAPHRAGM                1522
#define IDC_EG_DIAPHRAGM_UNIT           1523
#define IDC_EG_DIAPHRAGM_LABEL          1524
#define IDC_EG_DC_BS2                   1525
#define IDC_EG_DC_BS2_UNIT              1526
#define IDC_EG_DC_BS2_LABEL             1527
#define IDC_EG_DW_BS2                   1528
#define IDC_EG_DW_BS2_UNIT              1529
#define IDC_EG_DW_BS2_LABEL             1530
#define IDC_EG_DC_BS3                   1531
#define IDC_EG_DC_BS3_UNIT              1532
#define IDC_EG_DC_BS3_LABEL             1533
#define IDC_EG_DW_BS3                   1534
#define IDC_EG_DW_BS3_UNIT              1535
#define IDC_EG_DW_BS3_LABEL             1536
#define IDC_EG_RAILING                  1537
#define IDC_EG_RAILING_UNIT             1538
#define IDC_EG_RAILING_LABEL            1539
#define IDC_EG_SHRINKAGE                1540
#define IDC_EG_SHRINKAGE_UNIT           1541
#define IDC_EG_SHRINKAGE_LABEL          1542
#define IDC_EG_LIVELOAD                 1543
#define IDC_EG_LABEL                    1543
#define IDC_EG_SHRINKAGE_UNIT2          1544
#define IDC_EG_LIVELOAD_UNIT            1544
#define IDC_RELAXATION_LOSS_METHOD_LABEL 1544
#define IDC_EG_LIVELOAD_LABEL           1545
#define IDC_STATIC_HP                   1545
#define IDC_INTERPOLATE                 1546
#define IDC_EG_OVERLAY                  1546
#define IDC_VERT_ADJUST_GROUP           1546
#define IDC_EG_RAILING_UNIT2            1547
#define IDC_EG_OVERLAY_UNIT             1547
#define IDC_HP_BOX                      1547
#define IDC_EG_OVERLAY_LABEL            1548
#define IDC_LOWER_VEHICLE_WEIGHT_UNIT   1565
#define IDC_LOWER_VEHICLE_WEIGHT_LABEL  1566
#define IDC_UPPER_VEHICLE_WEIGHT_LABEL  1567
#define IDC_UPPER_VEHICLE_WEIGHT        1568
#define IDC_UPPER_VEHICLE_WEIGHT_UNIT   1569
#define IDC_ADTT1_LABEL                 1570
#define IDC_ADTT1                       1571
#define IDC_LF_LOWER1_LABEL             1572
#define IDC_LF_LOWER1                   1573
#define IDC_LF_UPPER1_LABEL             1574
#define IDC_LF_UPPER1                   1575
#define IDC_ADTT2_LABEL                 1576
#define IDC_ADTT2                       1577
#define IDC_LF_LOWER2_LABEL             1578
#define IDC_LF_LOWER2                   1579
#define IDC_LF_UPPER2_LABEL             1580
#define IDC_LF_UPPER2                   1581
#define IDC_ADTT3_LABEL                 1582
#define IDC_ADTT3                       1583
#define IDC_LF_LOWER3_LABEL             1584
#define IDC_LF_LOWER3                   1585
#define IDC_LF_UPPER3_LABEL             1586
#define IDC_LF_UPPER3                   1587
#define IDC_ADTT4                       1588
#define IDC_ADTT4_LABEL                 1588
#define IDC_LF_LOWER4_LABEL             1589
#define IDC_LF_LOWER4                   1590
#define IDC_LF_UPPER4_LABEL             1591
#define IDC_LF_UPPER4                   1592
#define IDC_VEHICLE_WEIGHT_LABEL        1593
#define IDS_E_BADINSTALL                1636
#define IDS_E_PROBPERSISTS              1638
#define IDS_E_INVALIDFORMAT             1640
#define IDS_E_FILENOTFOUND              1642
#define IDS_E_READ                      1644
#define IDS_E_FORMAT                    1646
#define IDS_E_WRITE                     1650
#define IDS_E_INVALIDVERSION            1750
#define IDS_E_USERDEFINED               1752
#define IDC_ALWC_FR                     2017
#define IDR_LIBEDITORTOOLBAR            12132
#define IDM_ADD_ENTRY                   36864
#define IDM_EDIT_ENTRY                  36865
#define IDM_DELETE_ENTRY                36866
#define IDM_DUPLICATE_ENTRY             36867
#define IDM_LARGE_ICONS                 36868
#define IDM_SMALL_ICONS                 36869
#define IDM_LIST_ICONS                  36870
#define IDM_ARRANGE_ICONS               36871
#define IDM_RENAME_ENTRY                36872
#define ID_FILE_IMPORT                  36873
#define ID_EDIT_INSERTROW               36874
#define ID_EDIT_DELETEROW               36875
#define ID_EDIT_REMOVEROWS              36876
#define ID_EDIT_ROW                     36877
#define ID_STR_INSERT                   36878
#define ID_STR_DELETE                   36879
#define ID_MANAGE_PLUGINS               36880

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         36881
#define _APS_NEXT_CONTROL_VALUE         1548
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
