F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\BT84_0.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\BT84_0@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\differentNumBeams.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\differentNumBeams@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeamSplayedVictoria.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeamSplayedVictoria@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_TsOutRange.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_TsOutRange@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_TsOutRange_Ignore.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_TsOutRange_Ignore@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_TsOutRange_IgnoreLever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_TsOutRange_IgnoreLever@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_TsOutRange_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_TsOutRange_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_UserInput.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_UserInput@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_UserInput_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\IBeam_UserInput_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Skew1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Skew1@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test02.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test02@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test05.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test05@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test12.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test12@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test15.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test15@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test17.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test17@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test27.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test27@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test30.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test30@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test32.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test32@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test35.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test35@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test45.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test45@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test46.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test46@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test53.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\Test53@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\vSlab_SingleSlab.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\vSlab_SingleSlab@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\vSlab_SingleSlab_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\vSlab_SingleSlab_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\vSlab_SingleSlab_lever2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\vSlab_SingleSlab_lever2@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\vSlab_SingleSlab_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\vSlab_SingleSlab_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_1@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_3@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_4_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_5@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_5_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_5_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_6.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_6@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_6_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_6_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_7.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\BoxAdjBeam_AASHTO_7@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_2_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_4_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_5_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_5_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_7.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_7@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_8.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DeckBulbT_AASHTO_8@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_2_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_4_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_5_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_5_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_6.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_6@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_6_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_6_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_7.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_7@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_7_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_7_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_8.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\DoubleT_AASHTO_8@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_DeOR.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_DeOR@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_Nb3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_Nb3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_Nb3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_Nb3_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_Rigid.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_Rigid@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay_nu.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay_nu@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay_nu_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay_nu_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay_nu_lever_screwb.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay_nu_lever_screwb@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay_skew.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\IBeam_AASHTO_splay_skew@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_1@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_3@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_3_or_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_3_or_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_4_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\UBeam_AASHTO_5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_1_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_1_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_1_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_3_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_4_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_5@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_6.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\AASHTO\vSlab_AASHTO_6@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew1_Left.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew1_Left@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew1_Right.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew1_Right@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew2_Left.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew2_Left@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew2_Right.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew2_Right@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew3_Left.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew3_Left@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew3_Right.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew3_Right@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\LRFD_7th_Edition_2014\TypeAEKIJ_Skew4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TxDOT_10.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TxDOT_10@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT_11_skew.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT_11_skew@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TxDOT_7.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TxDOT_7@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TxDOT_7_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TxDOT_7_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT_9.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT_9@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__10.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__10@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__13_skew.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__13_skew@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__2_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__4_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__5_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__5_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__6.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__6@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__6_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__6_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__8.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__8@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__8_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__8_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__9.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxAdjBeam_TXDOT__9@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_1@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\BoxSpr_TxDOT_4@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_2_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_4_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_5_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_5_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_6.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_6@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_6_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_6_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_7.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_7@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_7_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_7_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_8.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_8@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_8_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_8_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_9.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DeckBulbT_TXDOT_9@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_2@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_4@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_4_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_5_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_5_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_6.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_6@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_6_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_6_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_7.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_7@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_7_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_7_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_8.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_8@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_Skew.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_Skew@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_skew2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\DoubleT_Txdot_skew2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_DeOR.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_DeOR@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_DeOR_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_DeOR_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_ExteriorShearBug.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_ExteriorShearBug@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_ExteriorShearBug_lever_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_ExteriorShearBug_lever_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_ExteriorShearBug_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_ExteriorShearBug_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_GS2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_GS2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_GS2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_GS2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_Huge_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_Huge_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_lever@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_Nb3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_Nb3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_Nb3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_Nb3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_Skew.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\IBeam_TxDOT_Skew@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_2_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_2_lever@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_4@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_4_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_5_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_5_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_5_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\UBeam_TxDOT_5_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_1_skew.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_1_skew@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_2@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_3_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_3_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDOT_3_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDot_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDot_5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDot_5_leverl.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDot_5_leverl@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDot_6.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\TxDOT\vSlab_TxDot_6@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__1_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__3_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__4_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__5_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__5_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__6.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__6@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__6_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\BoxAdjBeam_WSDOT__6_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_1@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_1_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_3_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_4@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_4_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_4_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_5.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_5@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_5_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_5_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_6.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_6@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_6_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_6_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_7.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\DeckBulbT_WSDOT_7@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\IBeam_WSDOT_ExteriorBug.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\IBeam_WSDOT_ExteriorBug@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\IBeam_WSDOT_ExteriorBug_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\IBeam_WSDOT_ExteriorBug_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\IBeam_WSDOT_Nb3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\IBeam_WSDOT_Nb3@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\IBeam_WSDOT_Nb3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\IBeam_WSDOT_Nb3_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_1.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_1@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_1_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_1_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_2.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_2@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_2_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_2_si@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_3.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_3@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_3_lver.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_3_lver@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_3_or_lever.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_3_or_lever@TestDF_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_3_si.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_3_si@TestDF_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TestDF F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_4.pgs F:\ARP\PGSuper\RegressionTest\Current\LlDistribution-TestDF\WSDOT\UBeam_WSDOT_4@TestDF_All_EI.Test All EI
