F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_2015.pgs F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_2015@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_2016.pgs F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_2016@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_2016_MultiSpan.pgs F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_2016_MultiSpan@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_And_Deck_2015.pgs F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_And_Deck_2015@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_And_Deck_2016.pgs F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_And_Deck_2016@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_And_Deck_VciVcw_2015.pgs F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_And_Deck_VciVcw_2015@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_And_Deck_VciVcw_2016.pgs F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_And_Deck_VciVcw_2016@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_VciVcw_2015.pgs F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_VciVcw_2015@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_VciVcw_2016.pgs F:\ARP\PGSuper\RegressionTest\Current\LWC-TxDT\LWC_Girders_VciVcw_2016@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
