F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\JansenCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\JansenCreek@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\PartialLongRebarStandardGirder.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\PartialLongRebarStandardGirder@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\PartialLongRebarVoidedSlab.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\PartialLongRebarVoidedSlab@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TempStrandsOnly.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TempStrandsOnly@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\VoidedSlab_Extended_Debonded.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\VoidedSlab_Extended_Debonded@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\DeckedSlab_07fpu.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\DeckedSlab_07fpu@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\DeckedSlab_hybrid.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\DeckedSlab_hybrid@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\DeckedSlab_iterative.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\DeckedSlab_iterative@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\NewLossesTypeC.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\NewLossesTypeC@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\SpreadSlab_07fpu.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\SpreadSlab_07fpu@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\SpreadSlab_hybrid.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\SpreadSlab_hybrid@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\SpreadSlab_iterative.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\SpreadSlab_iterative@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\Tx46_07fpu.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\Tx46_07fpu@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\Tx46_hybrid.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\Tx46_hybrid@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\Tx46_Iterative.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\Tx46_Iterative@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\Tx62_wTempStrands.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\Tx62_wTempStrands@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\TxDOTLosses2013Tx28.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\TxDOTLosses2013Tx28@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\TxDOTLosses2013Tx62.pgs F:\ARP\PGSuper\RegressionTest\Current\Miscellaneous-TxAT\TxDOTLosses2013\TxDOTLosses2013Tx62@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
