F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\38_Tx62_40.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\38_Tx62_40@TxDS_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\40_Tx28.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\40_Tx28@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\4XB20_32.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\4XB20_32@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\6T36_60_HorizShear.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\6T36_60_HorizShear@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\6T36_60_HorizShear2.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\6T36_60_HorizShear2@TxDS_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\BigBars.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\BigBars@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\CAWF84ShearBug.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\CAWF84ShearBug@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\Final.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\Final@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\NonSymmBulbT.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\NonSymmBulbT@TxDS_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\StirrupDesign.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\StirrupDesign@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\StirrupDesign_SpreadSlab.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\StirrupDesign_SpreadSlab@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\TripleTee.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\TripleTee@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\Tx6T28Shear.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\Tx6T28Shear@TxDS_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\Tx82Shear.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\Tx82Shear@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\TypeIV_LongReinfShear.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\TypeIV_LongReinfShear@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\TypeIV_SecondaryBars.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\TypeIV_SecondaryBars@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\U54Shear.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\U54Shear@TxDS_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\U54_9.0ftSingleSpaLRS.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\U54_9.0ftSingleSpaLRS@TxDS_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\VciVcw.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\VciVcw@TxDS_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDS F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\w32btg.pgs F:\ARP\PGSuper\RegressionTest\Current\ShearDesign-TxDS\w32btg@TxDS_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
