F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AdjacentBoxSw.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AdjacentBoxSw@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AdjacentBoxSw2.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AdjacentBoxSw2@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AllBarriers.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AllBarriers@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AllBarriersMany.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AllBarriersMany@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AllBarriersToNoGirders.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AllBarriersToNoGirders@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AllBarriersToOneGirder.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\AllBarriersToOneGirder@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\Barriers_NLI.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\Barriers_NLI@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\HugePedestrian.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\HugePedestrian@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\LargeRightSw.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\LargeRightSw@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\LeftBarriersMany.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\LeftBarriersMany@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\LeftSwOnly.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\LeftSwOnly@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\RightOnlyBarriers.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\RightOnlyBarriers@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\RightSwOnly.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\RightSwOnly@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\SidewalkDisplayBug.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\SidewalkDisplayBug@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\SidewalkSplay.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\SidewalkSplay@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\SlabLoadBug.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\SlabLoadBug@TxAT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\SplayedUBeams.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\SplayedUBeams@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxAT F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\WideSidewalk.pgs F:\ARP\PGSuper\RegressionTest\Current\SidewalksBarriers-TxAT\WideSidewalk@TxAT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
