F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=TOGA /Configuration="TxDOTRegressionTest":"TxDOTRegressionTest"
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\box4b20.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\box4b20@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\DeckedSlab7DS23.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\DeckedSlab7DS23@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\SlabBeam4SB15Adjacent.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\SlabBeam4SB15Adjacent@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_1.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_1@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_2.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_2@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_3.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_3@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_4.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_4@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_5.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_5@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_6.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_6@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_7.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_7@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_8.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_8@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_8A.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_8A@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_8_2010.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_8_2010@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_9.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_9@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_9A.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_9A@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_9B.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_9B@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_9C.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Test46_9C@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_1.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_1@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_10.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_10@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_2.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_2@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_3.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_3@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_4.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_4@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_4_2010.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_4_2010@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_5.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_5@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_6.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_6@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_7.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_7@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_8.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_8@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_8_2010.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_8_2010@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_9.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\TOGA_9@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Tx70_Debond.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\Tx70_Debond@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\U40_Debond.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\U40_Debond@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxToga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\XBeam_5XB28.toga F:\ARP\PGSuper\RegressionTest\Current\TOGA-TxToga\XBeam_5XB28@TxToga.Test
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="WSDOT":"WSDOT"
