F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\ChiltipinCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\ChiltipinCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\FM1179rev2.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\FM1179rev2@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\FM388Overpass.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\FM388Overpass@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\LittleCrotonCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\LittleCrotonCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\MedioCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\MedioCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\PamplinCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\PamplinCreek@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\RabbsCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\RabbsCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\RedMudCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\RedMudCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\SH78_overpass.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\SH78_overpass@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\SandyCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\SandyCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\Tx40'sTaylor1.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\Tx40'sTaylor1@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\WestProng.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\WestProng@TxDT_All_EI.Test All EI
