F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\24S_5SB12_25.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\24S_5SB12_25@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\24S_5SB12_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\24S_5SB12_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\24S_5SB15_25.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\24S_5SB15_25@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\24S_5SB15_50.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\24S_5SB15_50@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30S_4SB12_25.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30S_4SB12_25@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30S_4SB12_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30S_4SB12_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30S_4SB15_25.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30S_4SB15_25@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30S_4SB15_50.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30S_4SB15_50@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30_B20.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30_B20@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30_B28.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30_B28@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30_B34.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30_B34@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30_B40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\30_B40@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx28_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx28_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx28_70.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx28_70@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx34_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx34_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx34_80.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx34_80@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx40_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx40_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx40_95.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx40_95@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx46_105.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx46_105@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx46_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx46_40@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx54_125.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx54_125@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx54_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx54_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx62_140.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx62_140@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx62_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx62_40@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx70_155.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx70_155@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx70_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\38_Tx70_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4B_5B20_ShearKey.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4B_5B20_ShearKey@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4B_5B34_ShearKey.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4B_5B34_ShearKey@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB20_32.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB20_32@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB20_44.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB20_44@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB28_32.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB28_32@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB28_44.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB28_44@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB34_32.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB34_32@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB34_44.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB34_44@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB40_32.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB40_32@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB40_44.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\4XB40_44@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB20_32.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB20_32@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB20_44.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB20_44@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB28_32.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB28_32@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB28_44.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB28_44@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB34_32.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB34_32@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB34_44.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB34_44@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB40_32.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB40_32@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB40_44.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\5XB40_44@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT22_40_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT22_40_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT22_45.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT22_45@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT22_50_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT22_50_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT22_55.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT22_55@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT28_55_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT28_55_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT28_60.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT28_60@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT28_65.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT28_65@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT28_65_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT28_65_O@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT36_65.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT36_65@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT36_65_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT36_65_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT36_85.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT36_85@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT36_85_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6HT36_85_O@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T22_30.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T22_30@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T22_30_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T22_30_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T22_35_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T22_35_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T22_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T22_40@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T28_30.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T28_30@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T28_30_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T28_30_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T28_50_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T28_50_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T28_55.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T28_55@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T36_30.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T36_30@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T36_30_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T36_30_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T36_60.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T36_60@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T36_60_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\6T36_60_O@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT22_40_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT22_40_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT22_45.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT22_45@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT22_50_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT22_50_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT22_55.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT22_55@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT28_55_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT28_55_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT28_60.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT28_60@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT28_65.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT28_65@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT28_65_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT28_65_O@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT36_65.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT36_65@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT36_65_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT36_65_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT36_85.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT36_85@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT36_85_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7HT36_85_O@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T22_30.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T22_30@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T22_30_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T22_30_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T22_35_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T22_35_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T22_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T22_40@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T28_30.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T28_30@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T28_30_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T28_30_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T28_50_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T28_50_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T28_55.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T28_55@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T36_30.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T36_30@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T36_30_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T36_30_O@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T36_60.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T36_60@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T36_60_O.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\7T36_60_O@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\B20_Slab.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\B20_Slab@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\B28_Slab.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\B28_Slab@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\B34_Slab.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\B34_Slab@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\B40_Slab.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\B40_Slab@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\BI36_AASHTO.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\BI36_AASHTO@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\BI36_AASHTO_AltKey.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\BI36_AASHTO_AltKey@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\BI36_TxDOT.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\BI36_TxDOT@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\DebondBug485.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\DebondBug485@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\DS20.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\DS20@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\SpreadSlab.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\SpreadSlab@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\SpreadSlab_SIP.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\SpreadSlab_SIP@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_A_30.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_A_30@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_A_50.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_A_50@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_B_30.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_B_30@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_B_60.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_B_60@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_C_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_C_40@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_C_80.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_C_80@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_IV_115.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_IV_115@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_IV_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_IV_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_VI_135.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_VI_135@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_VI_80.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Test_VI_80@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx28_RaisedStraightTest.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx28_RaisedStraightTest@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx34_ADIM_VertCurve.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx34_ADIM_VertCurve@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx40ADim_TxDOTCamberFactors.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx40ADim_TxDOTCamberFactors@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx54_RaisedStraightTest.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx54_RaisedStraightTest@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx70_RaisedStraightTest.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\Tx70_RaisedStraightTest@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTSlab15FilletTest.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTSlab15FilletTest@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_16_58_6_75_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_16_58_6_75_40@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_16_58_6_75_80.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_16_58_6_75_80@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_7_5_5_105.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_7_5_5_105@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_7_5_5_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_7_5_5_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_9_25_5_100.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_9_25_5_100@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_9_25_5_100T.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_9_25_5_100T@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_9_25_5_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_9_25_5_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_Endblox.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U40_Endblox@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_10_25_5_120.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_10_25_5_120@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_10_25_5_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_10_25_5_40@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_16_58_6.75_100.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_16_58_6.75_100@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_16_58_6.75_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_16_58_6.75_40@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_BT206_Bug.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\U54_BT206_Bug@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24S_5SB12_40.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24S_5SB12_40@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24S_5SB15_25.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24S_5SB15_25@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24_4B34_100.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24_4B34_100@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24_5B20_65.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24_5B20_65@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24_5B34_100.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24_5B34_100@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24_5B40_120.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\24_5B40_120@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28S_5SB15_25.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28S_5SB15_25@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28S_5SB15_50.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28S_5SB15_50@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28_5B20_65.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28_5B20_65@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28_5B28_80.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28_5B28_80@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28_5B40_120.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\28_5B40_120@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30S_4SB15_25.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30S_4SB15_25@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30_4B20_65.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30_4B20_65@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30_5B20_65.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30_5B20_65@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30_5B28_75.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30_5B28_75@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30_5B40_120.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\30_5B40_120@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\U40_7.5_5_105.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\U40_7.5_5_105@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\U54_10.25_5_120.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\EqualizedLosses\U54_10.25_5_120@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\ChiltipinCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\ChiltipinCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\FM1179rev2.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\FM1179rev2@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\FM388Overpass.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\FM388Overpass@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\LittleCrotonCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\LittleCrotonCreek@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\MedioCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\MedioCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\PamplinCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\PamplinCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\RabbsCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\RabbsCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\RedMudCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\RedMudCreek@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\SandyCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\SandyCreek@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\SH78_overpass.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\SH78_overpass@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\Tx40'sTaylor1.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\Tx40'sTaylor1@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\WestProng.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\RealExamples\WestProng@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\DeckedSlab_07fpu.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\DeckedSlab_07fpu@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\DeckedSlab_hybrid.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\DeckedSlab_hybrid@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\DeckedSlab_iterative.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\DeckedSlab_iterative@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\SpreadSlab_07fpu.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\SpreadSlab_07fpu@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\SpreadSlab_hybrid.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\SpreadSlab_hybrid@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\SpreadSlab_iterative.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\SpreadSlab_iterative@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\Tx46_07fpu.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\Tx46_07fpu@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\Tx46_hybrid.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\Tx46_hybrid@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\Tx46_Iterative.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\Tx46_Iterative@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\Tx62_wTempStrands.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\TxDOT\TxDOTLosses2013\Tx62_wTempStrands@TxDT_All_EI.Test All EI
