F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe /App=PGSUPER /Configuration="Regression":"Regression"
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\18_inch_BD.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\18_inch_BD@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\1_0_SolidSlab.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\1_0_SolidSlab@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\1_6_VoidedSlab.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\1_6_VoidedSlab@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\2_0_VoidedSlab.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\2_0_VoidedSlab@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\ChainupCheck.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\ChainupCheck@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\OverhangBug.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\OverhangBug@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\PG_139th_B2_anyway.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\PG_139th_B2_anyway@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\RibbedGirder.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\RibbedGirder@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew1_Left.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew1_Left@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew1_Right.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew1_Right@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew2_Left.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew2_Left@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew2_Right.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew2_Right@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew3_Left.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew3_Left@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew3_Right.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew3_Right@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew4.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\TypeAEKIJ_Skew4@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54g4.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54g4@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54G5(Debond).pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54G5(Debond)@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54G5(Harped).pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54G5(Harped)@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54g5.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54g5@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54g6.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\U54g6@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\vSlab_debond_1.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\vSlab_debond_1@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\vSlab_debond_1si.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\vSlab_debond_1si@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w32btg.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w32btg@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W35DG.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W35DG@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w38btg.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w38btg@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W40DG.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W40DG@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W42G.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W42G@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w50g.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w50g@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W53DG.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W53DG@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W54_debond.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W54_debond@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w58g.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w58g@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w62btg.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w62btg@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W65DG.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\W65DG@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w75g.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\w75g@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\WF.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\WF@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf42g.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf42g@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf50g.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf50g@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf58g.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf58g@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf74g.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf74g@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf74gorig.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf74gorig@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf83g.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf83g@TxDT_All_EI.Test All EI
cmd.exe /C START "XYZ" F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf95g.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\wf95g@TxDT_All_EI.Test All EI
F:\ARP\BridgeLink\RegFreeCOM\X64\RELEASE\BridgeLink.exe  /TxDT F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\RealExamples\SwaukCreek.pgs F:\ARP\PGSuper\RegressionTest\Current\Designer-TxDT\WsDOT\RealExamples\SwaukCreek@TxDT_All_EI.Test All EI
