//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TxDOTAgent.rc
//
#define IDS_PROJNAME                    100
#define IDR_TXDOTAGENT                  101
#define IDS_TEMPLATE_SUFFIX             101
#define IDR_GIRDER_VIEW_CTX             101
#define IDS_SHEETNAME                   102
#define IDR_TXDOTAGENTIMP               103
#define IDR_TXDOTCADEXPORTER            104
#define IDR_TXDOTCOMPONENTINFO          105
#define IDR_TXDOTAPPPLUGIN              106
#define IDR_TXDOTOPTIONALDESIGN         107
#define IDR_TXDOTOPTIONALDESIGNTOOLBAR  107
#define IDD_REPORT_PAGE                 107
#define IDD_BRIDGE_INPUT_PAGE           108
#define IDD_GIRDER_EDITOR_SECTION_PAGE  160
#define IDD_GIRDER_EDITOR_ELEVATION_PAGE 161
#define IDR_GIRDER_CTX                  162
#define IDD_SECTION_CUT_DIALOG_EX       188
#define IDD_EXPORT_TXDOTCADDATA         201
#define IDC_SPAN                        202
#define IDD_GIRDER_INPUT_PAGE           202
#define IDC_GIRDER                      203
#define IDC_EXTENDED                    204
#define IDI_TXDOT                       205
#define IDC_REPORT_COMBO                205
#define IDC_ERROR_STATIC                206
#define IDC_BRIDGE                      208
#define IDD_GIRDER_VIEW_PAGE            209
#define IDC_BRIDGE_ID                   209
#define IDC_JOB_NUMBER                  210
#define IDC_BEAM_TYPE                   211
#define IDD_STANDARD_FILL_DLG           211
#define IDC_SPAN_NO                     212
#define IDD_ECC_DLG                     212
#define IDD_NONSTANDARD_FILL_DLG        213
#define IDC_ENGINEER                    214
#define IDC_COMPANY                     215
#define IDC_COMMENTS                    216
#define IDC_BEAM_NO                     217
#define IDC_BEAM_SPACING                218
#define IDC_SPAN_LENGTH                 219
#define IDC_SLAB_THICKNESS              220
#define IDC_RELATIVE_HUMIDITY           221
#define IDC_LLDF_MOMENT                 222
#define IDC_LLDF_SHEAR                  223
#define IDC_EC_SLAB                     224
#define IDC_EC_BEAM                     225
#define IDC_FC_SLAB                     226
#define IDC_FT                          227
#define IDC_OPT_FC                      227
#define IDC_FB                          228
#define IDC_OPT_TO                      228
#define IDC_ORIG_FC                     228
#define IDC_EDIT21                      229
#define IDC_MU                          229
#define IDC_W_NONCOMP_DC                230
#define IDC_W_COMP_DC                   231
#define IDC_W_COMP_DW                   232
#define IDC_BEAM_SPACING_UNITS          234
#define IDC_SPAN_LENGTH_UNITS           235
#define IDC_SLAB_THICKNESS_UNITS        236
#define IDC_EC_SLAB_UNITS               237
#define IDC_EC_BEAM_UNITS               238
#define IDC_FC_SLAB_UNITS               239
#define IDC_FT_UNITS                    240
#define IDC_OPT_FC_UNITS                240
#define IDC_FB_UNITS                    241
#define IDC_OPT_TO_UNITS                241
#define IDC_ORIG_FC_UNITS               241
#define IDC_W_NONCOMP_DC_UNITS          242
#define IDC_W_COMP_DC_UNITS             243
#define IDC_W_COMP_DW_UNITS             244
#define IDC_MU_UNITS                    245
#define IDC_OPT_STANDARD_FILL           246
#define IDC_OPT_STRAND_SIZE             247
#define IDC_OPT_FCI                     248
#define IDC_OPT_FCI_UNITS               249
#define IDC_OPT_NUM_STRANDS             250
#define IDC_ORIG_STANDARD_FILL          250
#define IDC_OPT_NO_DEPRESSED            251
#define IDC_ORIG_STRAND_SIZE            251
#define IDC_OPT_COMPUTE                 252
#define IDC_ORIG_FCI                    252
#define IDC_ORIGINAL_BOX                253
#define IDC_OPT_BOX                     253
#define IDC_OPT_STRAND_TYPE             254
#define IDC_OPT_TO_VALID_RANGE          255
#define IDC_BUTTON1                     255
#define IDC_ORIG_STRAND_TYPE            255
#define IDC_TO_TAG                      256
#define IDC_OPT_TO_TAG                  256
#define IDC_ORIG_BOX                    256
#define IDC_ECC_TEXT                    257
#define IDC_ORIG_FCI_UNITS              257
#define IDC_CL_GRID                     258
#define IDC_CL_NO_STRANDS               259
#define IDC_OPT_USE_DEPRESSED           260
#define IDC_END_GRID                    260
#define IDC_END_NO_STRANDS              261
#define IDC_ORIG_USE_DEPRESSED          261
#define IDC_ENDS_GROUP                  262
#define IDC_ERROR_MSG                   263
#define IDC_CHECK1                      264
#define IDC_HIGHER_COMPRESSION          264
#define IDC_VALUE                       1018
#define IDC_VALUE_UNITS                 1026
#define ID_SELECTED_GIRDER              1086
#define IDC_SHOW_PS_CG                  1092
#define IDC_SHOW_DIMENSIONS             1151
#define IDC_SHOW_SCHEMATIC              1155
#define IDC_SHOW_STRANDS                1157
#define IDC_SHOW_LONG_REINF             1158
#define IDC_SHOW_SHOW_LONG_REINF        1159
#define IDC_SECTION_CUT                 1161
#define IDC_BROWSER                     1177
#define IDC_LEFT_END                    1179
#define IDC_LEFT_HARP                   1183
#define IDC_GIRDER_MIDDLE               1184
#define IDC_RIGHT_HARP                  1186
#define IDC_RIGHT_END                   1188
#define IDC_USER_CUT                    1191
#define IDC_SHOW_TRANSV_REINF           1457
#define IDS_E_BADINSTALL                1636
#define IDS_E_PROBPERSISTS              1638
#define IDS_E_INVALIDFORMAT             1640
#define IDS_E_FILENOTFOUND              1642
#define IDS_E_READ                      1644
#define IDS_E_FORMAT                    1646
#define IDS_E_INVALIDVERSION            1750
#define IDS_E_USERDEFINED               1752
#define IDS_GDR_ERROR                   1754
#define IDS_GDR_ERROR2                  1755
#define IDS_CONN_ERROR                  1755
#define ID_LEFTEND                      33174
#define ID_RIGHTEND                     33175
#define ID_LEFT_HP                      33176
#define ID_CENTER                       33177
#define ID_RIGHT_HP                     33178
#define ID_USER_CUT                     33179
#define ID_HELP_JOINARPLIST             33188
#define ID_FILE_SAVEAS                  33300
#define ID_FILE_EXPORTPGSUPERMODEL      33301
#define ID_FILE_CLOSE33302              33302
#define ID_BUTTON33303                  33303
#define ID_GIRDERSECTION_EDITVIEWSETTINGS 33304
#define ID_SECTION_VIEWSETTINGS         33305
#define ID_VIEWSETTINGS                 33306
#define ID_HELP_INFO                    33307
#define ID_LICENSE_AGREEMENT            33308
#define ID_HELP_ABOUTPGSUPER            33309
#define ID_HELP_A                       33310
#define ID_VIEW_SECTIONCUTLOCATION      33312
#define ID_VIEW_GIRDERVIEWSETTINGS      33313
#define ID_VIEW_STATUSCENTER            33314
#define ID_STATUSCENTER_VIEW            33315

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         33316
#define _APS_NEXT_CONTROL_VALUE         265
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
