//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TxDOTAgent.rc
//
#define IDS_PROJNAME                    100
#define IDR_TXDOTAGENT                  101
#define IDS_TEMPLATE_SUFFIX             101
#define IDS_SHEETNAME                   102
#define IDR_TXDOTAGENTIMP               103
#define IDR_TXDOTCADEXPORTER            104
#define IDR_TXDOTCOMPONENTINFO          105
#define IDR_TXDOTAPPPLUGIN              106
#define IDR_TXDOTOPTIONALDESIGN         107
#define IDR_TXDOTOPTIONALDESIGNTOOLBAR  107
#define IDD_REPORT_PAGE                 107
#define IDD_BRIDGE_INPUT_PAGE           108
#define IDD_EXPORT_TXDOTCADDATA         201
#define IDC_SPAN                        202
#define IDD_GIRDER_INPUT_PAGE           202
#define IDC_GIRDER                      203
#define IDC_EXTENDED                    204
#define IDI_TXDOT                       205
#define IDC_REPORT_COMBO                205
#define IDC_ERROR_STATIC                206
#define IDC_BRIDGE                      208
#define IDD_GIRDER_VIEW_PAGE            209
#define IDC_BRIDGE_ID                   209
#define IDC_JOB_NUMBER                  210
#define IDC_BEAM_TYPE                   211
#define IDD_STANDARD_FILL_DLG           211
#define IDC_SPAN_NO                     212
#define IDD_ECC_DLG                     212
#define IDD_NONSTANDARD_FILL_DLG        213
#define IDC_ENGINEER                    214
#define IDC_COMPANY                     215
#define IDC_COMMENTS                    216
#define IDC_BEAM_NO                     217
#define IDC_BEAM_SPACING                218
#define IDC_SPAN_LENGTH                 219
#define IDC_SLAB_THICKNESS              220
#define IDC_RELATIVE_HUMIDITY           221
#define IDC_LLDF_MOMENT                 222
#define IDC_LLDF_SHEAR                  223
#define IDC_EC_SLAB                     224
#define IDC_EC_BEAM                     225
#define IDC_FC_SLAB                     226
#define IDC_FT                          227
#define IDC_OPT_FC                      227
#define IDC_FB                          228
#define IDC_OPT_TO                      228
#define IDC_ORIG_FC                     228
#define IDC_EDIT21                      229
#define IDC_MU                          229
#define IDC_W_NONCOMP_DC                230
#define IDC_W_COMP_DC                   231
#define IDC_W_COMP_DW                   232
#define IDC_BEAM_SPACING_UNITS          234
#define IDC_SPAN_LENGTH_UNITS           235
#define IDC_SLAB_THICKNESS_UNITS        236
#define IDC_EC_SLAB_UNITS               237
#define IDC_EC_BEAM_UNITS               238
#define IDC_FC_SLAB_UNITS               239
#define IDC_FT_UNITS                    240
#define IDC_OPT_FC_UNITS                240
#define IDC_FB_UNITS                    241
#define IDC_OPT_TO_UNITS                241
#define IDC_ORIG_FC_UNITS               241
#define IDC_W_NONCOMP_DC_UNITS          242
#define IDC_W_COMP_DC_UNITS             243
#define IDC_W_COMP_DW_UNITS             244
#define IDC_MU_UNITS                    245
#define IDC_OPT_STANDARD_FILL           246
#define IDC_OPT_STRAND_SIZE             247
#define IDC_OPT_FCI                     248
#define IDC_OPT_FCI_UNITS               249
#define IDC_OPT_NUM_STRANDS             250
#define IDC_ORIG_STANDARD_FILL          250
#define IDC_OPT_NO_DEPRESSED            251
#define IDC_ORIG_STRAND_SIZE            251
#define IDC_OPT_COMPUTE                 252
#define IDC_ORIG_FCI                    252
#define IDC_ORIGINAL_BOX                253
#define IDC_OPT_BOX                     253
#define IDC_OPT_STRAND_TYPE             254
#define IDC_OPT_TO_VALID_RANGE          255
#define IDC_BUTTON1                     255
#define IDC_ORIG_STRAND_TYPE            255
#define IDC_TO_TAG                      256
#define IDC_OPT_TO_TAG                  256
#define IDC_ORIG_BOX                    256
#define IDC_ECC_TEXT                    257
#define IDC_ORIG_FCI_UNITS              257
#define IDC_CL_GRID                     258
#define IDC_CL_NO_STRANDS               259
#define IDC_OPT_USE_DEPRESSED           260
#define IDC_END_GRID                    260
#define IDC_END_NO_STRANDS              261
#define IDC_ORIG_USE_DEPRESSED          261
#define IDC_ENDS_GROUP                  262
#define IDC_BROWSER                     1177
#define IDS_E_BADINSTALL                1636
#define IDS_E_PROBPERSISTS              1638
#define IDS_E_INVALIDFORMAT             1640
#define IDS_E_FILENOTFOUND              1642
#define IDS_E_READ                      1644
#define IDS_E_FORMAT                    1646
#define IDS_E_INVALIDVERSION            1750
#define IDS_E_USERDEFINED               1752
#define ID_FILE_SAVEAS                  33300
#define ID_FILE_EXPORTPGSUPERMODEL      33301
#define ID_FILE_CLOSE33302              33302
#define ID_BUTTON33303                  33303

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         33304
#define _APS_NEXT_CONTROL_VALUE         263
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
