///////////////////////////////////////////////////////////////////////
// PGSuper - Prestressed Girder SUPERstructure Design and Analysis
// Copyright © 1999-2012  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// TxDOTAgent.idl : IDL source for TxDOTAgent
//

// This file will be processed by the MIDL tool to
// produce the type library (TxDOTAgent.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "WBFLCore.idl";
import "PGSuperIEPlugin.idl";

[
	uuid(17D09C05-E1AC-42D5-9CFE-B72414564E26),
	version(1.0),
	helpstring("TxDOTAgent 1.0 Type Library")
]
library TxDOTAgentLib
{
	importlib("stdole2.tlb");
	[
		uuid(360F7694-BE5B-4E97-864F-EF3575689C6E),
		helpstring("TxDOTAgent Class")
	]
	coclass TxDOTAgent
	{
		[default] interface IAgentEx;
	};

   [
      uuid(F106BA9D-6C17-40b9-BF97-A43103CABECF),
      helpstring("TxDOTCadExporter Class")
   ]
   coclass TxDOTCadExporter
   {
      [default] interface IPGSuperDataExporter;
   };

	[
		uuid(FB446ED8-EBFA-46a0-9D84-8E5DC53A371F),
		helpstring("TxDOTAppPlugin Class")
	]
	coclass TxDOTAppPlugin
	{
		interface IUnknown;
   };

   [
      uuid(539E5AB9-4302-45f9-9FAD-B8E2DB6867F1)
   ]
   coclass TxDOTComponentInfo
   {
      [default] interface IUnknown;
   };
};
