///////////////////////////////////////////////////////////////////////
// PGSuper - Prestressed Girder SUPERstructure Design and Analysis
// Copyright © 1999-2014  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// TxDOTAgent.idl : IDL source for TxDOTAgent
//

// This file will be processed by the MIDL tool to
// produce the type library (TxDOTAgent.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "WBFLCore.idl";
import "PGSuperIEPlugin.idl";

[
	uuid(17D09C05-E1AC-42D5-9CFE-B72414564E26),
	version(1.0),
	helpstring("TxDOTAgent 1.0 Type Library")
]
library TxDOTAgentLib
{
	importlib("stdole2.tlb");
	[
		uuid(3700B253-8489-457c-8A6D-D174F95C457C),
		helpstring("TxDOTAgent Class")
	]
	coclass TxDOTAgent
	{
		[default] interface IAgentEx;
	};

   [
      uuid(9274354C-D0B7-437c-A5B3-3FFBFB17ADE3),
      helpstring("TxDOTCadExporter Class")
   ]
   coclass TxDOTCadExporter
   {
      [default] interface IPGSuperDataExporter;
   };

	[
		uuid(F4629B75-7EF8-4159-A09A-9F4F30B60501),
		helpstring("TxDOTAppPlugin Class")
	]
	coclass TxDOTAppPlugin
	{
		interface IUnknown;
   };

   [
      uuid(785F2ACE-127B-4647-8062-ED49537E962C)
   ]
   coclass TxDOTComponentInfo
   {
      [default] interface IUnknown;
   };
};
