///////////////////////////////////////////////////////////////////////
// PGSuper - Prestressed Girder SUPERstructure Design and Analysis
// Copyright © 1999-2017  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// GraphingAgent.idl : IDL source for GraphingAgent.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (GraphingAgent.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "WBFLTypes.idl";

[
	uuid(35C335FA-52B7-4ff0-AAD8-6B8C85D34F9D),
	version(1.0),
	helpstring("GraphingAgent 1.0 Type Library")
]
library PGSuperGraphingAgent
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
   importlib("WBFLCore.tlb");

	[
		uuid(B4639189-ED38-4a68-8A18-38026202E9DE),
		helpstring("Grapher Class")
	]
	coclass PGSuperGraphingAgent
	{
	    [default] interface IAgent;
	};

	[
		uuid(EDAAB718-3128-4b1c-956C-CCAAD32D01DB),
		helpstring("PGSpliceGraphAgent Class")
	]
	coclass PGSpliceGraphingAgent
	{
	    [default] interface IAgent;
	};
};
