//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Graphs.rc
//
#define IDOK2                           3
#define IDCANCEL2                       4
#define IDD_ANALYSISRESULTS_GRAPH_CONTROLLER 103
#define IDD_PGSUPER_STABILITY_BAR       195
#define IDD_PGSPLICE_STABILITY_BAR      196
#define IDD_EFFECTIVEPRESTRESS_GRAPH_CONTROLLER 197
#define IDD_STRESSHISTORY_GRAPH_CONTROLLER 198
#define IDD_GIRDER_PROPERTIES_GRAPH_CONTROLLER 199
#define IDD_CONCRETE_PROPERTY_GRAPH_CONTROLLER 200
#define IDD_DEFLECTIONHISTORY_GRAPH_CONTROLLER 201
#define IDD_ANALYSISRESULTS_GRAPH_CONTROLLER2 202
#define IDD_INITIALSTRAIN_GRAPH_CONTROLLER 203
#define IDD_SEGMENT_ANALYSISRESULTS_GRAPH_CONTROLLER 204
#define IDD_FINISHED_ELEVATION_GRAPH_CONTROLLER 205
#define IDD_FILL_HAUNCH                 215
#define IDC_EVENT                       1096
#define IDC_FROM_SPAN                   1422
#define IDC_FROM_GIRDER                 1435
#define IDC_COMPUTE_HAUNCH_COMBO        1436
#define IDC_COMPUTE_HAUNCH_GIRDER       1437
#define IDC_SIMPLE                      1478
#define IDC_SIMPLE2                     1479
#define IDC_SIMPLE3                     1480
#define IDC_ANALYSISTYPE                1744
#define IDC_PRECAST_SEGMENT             3009
#define IDC_CLOSURE_JOINT               3010
#define IDC_DECK                        3011
#define IDC_GROUP                       3012
#define IDC_GIRDER                      3013
#define IDC_SEGMENT                     3014
#define IDC_GIRDER2                     3014
#define IDC_CLOSURE                     3015
#define IDC_INTERVAL                    3016
#define IDC_CLOSURE2                    3016
#define IDC_DECK_CASTING_REGION         3016
#define IDC_GRAPH_TYPE                  3017
#define IDC_PLOT_AT                     3018
#define IDC_ACTION                      3020
#define IDC_GRID                        3021
#define IDC_DUCT                        3022
#define IDC_PGL                         3022
#define IDC_POI                         3023
#define IDC_FINISHED_DECK2              3023
#define IDC_FINISHED_DECK               3023
#define IDC_TOPDECK                     3024
#define IDC_FINISHED_DECK_BOTTOM        3024
#define IDC_BOTTOMDECK                  3025
#define IDC_FINISHED_GIRDER_TOP         3025
#define IDC_TOPGIRDER                   3026
#define IDC_FINISHED_GIRDER_BOTTOM      3026
#define IDC_BOTTOMGIRDER                3027
#define IDC_GIRDER_CHORD                3027
#define IDC_ELEVATION_TOLERANCE         3028
#define IDC_PROPERTY                    3030
#define IDC_BEAM                        3031
#define IDC_TRANSFORMED                 3032
#define IDC_BEAM2                       3032
#define IDC_HAUNCH_DEPTH                3032
#define IDC_GROSS                       3033
#define IDC_10TH_POINTS                 3033
#define IDC_FC                          3034
#define IDC_EC                          3035
#define IDC_SH                          3036
#define IDC_CR                          3037
#define IDC_TIME_LINEAR                 3041
#define IDC_TIME_LOG                    3042
#define IDC_AGE_LINEAR                  3043
#define IDC_AGE_LOG                     3044
#define IDC_INTERVALS                   3045
#define IDC_STRESS                      3046
#define IDC_FORCE                       3047
#define IDC_MODE                        3048
#define IDC_LIST_INFO                   3049
#define IDC_DROP_LIST                   3050
#define IDC_SELECT_LIST                 3051
#define IDC_SELECT_LIST_TITLE           3052
#define IDC_INCREMENTAL                 3056
#define IDC_CUMULATIVE                  3057
#define IDC_TOP_GIRDER                  3058
#define IDC_BOTTOM_GIRDER               3059
#define IDC_TOP_DECK                    3060
#define IDC_BOTTOM_DECK                 3061
#define IDC_ELEV_ADJUSTMENT             3065
#define IDC_CREEP                       3065
#define IDC_SHRINKAGE                   3066
#define IDC_PRECAMBER                   3066
#define IDC_ELEV_ADJUSTMENT2            3066
#define IDC_RELAXATION                  3067
#define IDC_NET_GIRDER                  3069
#define IDC_NET_DECK                    3070
#define IDC_PERMANENT                   3070
#define IDC_TEMPORARY                   3071
#define IDC_EXPORT_GRAPH                3072
#define IDC_EXPORT_GRAPH_BTN            3072
#define IDC_EDIT_HAUNCH                 3073
#define IDC_GIRDER_TEXT                 3073
#define IDC_FILL_HAUNCH                 3074
#define IDC_COMPUTE_HAUNCH_RADIO        3074
#define IDC_ADD_HAUNCH_RADIO            3075
#define IDC_COPY_HAUNCH_RADIO           3076
#define IDC_ADD_HAUNCH_EDIT             3077
#define IDC_ADD_HAUNCH_UNIT             3078
#define IDC_COMPUTE_HAUNCH_STATIC2      3079
#define IDC_COMPUTE_HAUNCH_STATIC       3080
#define IDC_COMPUTE_HAUNCH_STATIC3      3081
#define IDC_RADIO_SELECTED_GIRDER       3082
#define IDC_RADIO2                      3083
#define IDC_RADIO_SELECT_ALL_GIRDERS    3083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        217
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         3083
#define _APS_NEXT_SYMED_VALUE           3002
#endif
#endif
