///////////////////////////////////////////////////////////////////////
// PGSuper - Prestressed Girder SUPERstructure Design and Analysis
// Copyright © 1999-2013  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(22C18BFF-4D70-4677-824E-ACD08F89F575),
	version(1.00)
]
library PGSuper
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
   importlib("WBFLCore.tlb");

	[
		uuid(3FD393DD-8AF4-4cb2-A1C5-71E46C436BA0)
	]
	coclass BridgeAgent
	{
		[default] interface IAgent;
	};
};
