///////////////////////////////////////////////////////////////////////
// ExtensionAgentExample - Extension Agent Example Project for PGSuper
// Copyright © 1999-2018  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// ExtensionAgentExample.idl : IDL source for ExtensionAgentExample
//

// This file will be processed by the MIDL tool to
// produce the type library (ExtensionAgentExample.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "WBFLCore.idl"; // for the Agent plugin

[
	uuid(695550A1-EAEA-4019-A989-5778A6765574),
	version(1.0),
	helpstring("ExtensionAgentExample 1.0 Type Library")
]
library ExtensionAgentExampleLib
{
	importlib("stdole2.tlb");
	[
		uuid(C75182FE-7DAC-47A1-B87C-8BFA0F3C5D35),
		helpstring("ExampleExtensionAgent Class")
	]
	coclass ExampleExtensionAgent
	{
		[default] interface IAgentEx;
	};
};
