///////////////////////////////////////////////////////////////////////
// PGSuper - Prestressed Girder SUPERstructure Design and Analysis
// Copyright © 1999-2014  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the Alternate Route Open Source License as 
// published by the Washington State Department of Transportation, 
// Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but 
// distribution is AS IS, WITHOUT ANY WARRANTY; without even the implied 
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See 
// the Alternate Route Open Source License for more details.
//
// You should have received a copy of the Alternate Route Open Source 
// License along with this program; if not, write to the Washington 
// State Department of Transportation, Bridge and Structures Office, 
// P.O. Box  47340, Olympia, WA 98503, USA or e-mail 
// Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// WSDOTAgent.idl : IDL source for WSDOTAgent
//

// This file will be processed by the MIDL tool to
// produce the type library (WSDOTAgent.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "WBFLCore.idl";
import "PGSuperIEPlugin.idl";  // for the Importer/Exporter plugins

[
	uuid(3B6BF48B-C530-486E-918F-7705E13D6330),
	version(1.0),
	helpstring("WSDOTAgent 1.0 Type Library")
]
library PGSuper
{
	importlib("stdole2.tlb");

   [
		uuid(B1A19633-8880-40bc-A3C9-DDF47F7F1844),
		helpstring("WSDOTAgent Class")
	]
	coclass WSDOTAgent
	{
		[default] interface IAgentEx;
	};

   [
      uuid(5656F52E-4DC8-4299-8AD1-23EB3AE46353)
   ]
   coclass WSDOTComponentInfo
   {
		[default] interface IUnknown;
   };
	[
		uuid(E89CC143-53C9-43df-B1B4-E522769DE29B),
		helpstring("CurvelExporter Class")
	]
	coclass CurvelExporter
	{
		[default] interface IPGSuperDataExporter;
	};
	[
		uuid(E56801AC-B583-4e9e-A2D8-2AA64079BE15),
		helpstring("CurvelImporter Class")
	]
	coclass CurvelImporter
	{
		[default] interface IPGSuperDataImporter;
	};
	[
		uuid(16A21688-25B4-4118-ABF4-DD6D4983A2CD),
		helpstring("GenCompeExporter Class")
	]
	coclass GenCompExporter
	{
		[default] interface IPGSuperDataExporter;
	};
};
